atuinsh/atuin

- src/command/history.rs
- src/local/database.rs
I'd like to reduce the amount of SQL in the database code. Make it as
generic as possible, and later on perhaps expose a generic "execute"
function.
This function can be used by analysis commands, and the SQL can live
there - rather than database.rs being a huge bag of SQL.
> Neaten the history listing code

- Cargo.lock
- Cargo.toml
- README.md
- src/command/event.rs
- src/command/history.rs
- src/command/mod.rs
- src/command/search.rs
- src/local/database.rs
- src/local/history.rs
- src/main.rs
- src/shell/atuin.zsh
This totally removes the requirement for FZF! Also no longer lists all
the database contents and pipes them to something, and instead uses
SQLite for searching. Again, SQLite still needs optimizing! We're
literally using a LIKE query here, and something like the FTS module
would make more sense I think.
On top of this, at the moment the TUI is very... "initial
implementation". Ie, the code is a mess. It needs restructuring +
rethinking, but it works :) I'd like to include more stats in the TUI at
some point, without slowing it down too much!
Also automatically search for whatever the current command buffer is.
> Add TUI, resolve #19, #17, #16

- install.sh
The filename for the deb is versioned like '0.6.4', not 'v0.6.4'.
> Fix ubuntu install

- src/command/search.rs
Resolves #52
I would like a properly configurable approach to keybinding, but for now I can see how it might be jarring for ctrl-c to be a noop
> Allow using Ctrl-c to exit

- atuin-client/src/database.rs
- atuin-client/src/settings.rs
- src/command/mod.rs
- src/command/search.rs
Support fulltext search mode.
Fulltext search will report partial matches of commands, not just prefix
matches. Matches ctrl-r default behavior (on zsh at least).
TODO:
- <s>Is the way I'm doing string concat idiomatic rust?</s> It wasn't, but it is now
- <s>Should this be toggleable behind a config options?</s> Yes
- <s>Should this be a param to db.query method, toggling fulltext vs prefix search?</s> Yes
Fixes https://github.com/ellie/atuin/issues/72
> Support fulltext search of commands

- src/shell/atuin.bash
> Run shellcheck on bash file

- atuin-client/src/import/bash.rs
- atuin-client/src/import/mod.rs
- atuin-client/src/import/resh.rs
- atuin-client/src/import/zsh.rs
- src/command/import.rs
Creates a new trait
```rust
pub trait Importer: IntoIterator<Item = Result<History>> + Sized {
const NAME: &'static str;
fn histpath() -> Result<PathBuf>;
fn parse(path: impl AsRef<Path>) -> Result<Self>;
}
```
and a function `import` which will use the provided `Importer` type to perform a generic import.
It will:
1. Check for a `$HISTFILE` or call `I::histpath()?`
2. Check that the history file is a file (#66)
3. Parse the history file
4. Iterate over the parsed contents, saving them to the DB in batches
TODO: Tests :)
> Generic Importer Trait

- src/command/history.rs
- src/command/mod.rs
- src/command/search.rs
Should be useful for using other tools, such as FZF
Ref #68
> Allow listing or searching with only the command as output

- src/command/search.rs
These are nice key bindings that keep your hands at home row. Ctrl-g is less important considering ctrl-c and ctrl-d already do this, but it's muscle memory for me so I threw it in there.
> Emacs style ctrl-g, ctrl-n, and ctrl-p

- atuin-client/src/import/resh.rs
This change was made in #82 , but was missed out when it was converted to use the generic trait (in #71).
> Fix resh importer crashing on end of file

- atuin-client/src/encryption.rs
- atuin-client/src/settings.rs
- docs/sync.md
- src/command/login.rs
- src/command/logout.rs
- src/command/mod.rs
- src/command/register.rs
Also:
- Ensures that a key is generated as soon as a user registers!
- Ensures that "atuin key" will generate a key if needed, and doesn't
double base64 encode data
And a few other little fixes :)
Resolves #85
Resolves #86
> Add logout, only login if not already logged in

- src/command/search.rs
Puts numbers 0-9 next to commands *above* current selection.
Ctrl-<number> should activate them - but since Ctrl-<num> are
reserved by terminal, this does not currently work. Need to
find different sets of keyboard shortcuts.
Numbers are *above* current selection, since the user must use
the arrow keys to go over the commands below current selection
before reaching selection.
> Implement 'quick access' via Alt-<n>

- Cargo.toml
This allows us to produce a faster executable (which is useful in shells) at the expense of rarely spending more compilation time upon releasing a new version.
I do this in all of my rust projects, perhaps because they are too small for compilation time to really matter. We should measure next time we release and see how that goes.
> Increase number of optimizations on release builds.

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/config.toml
- atuin-client/src/database.rs
- atuin-client/src/settings.rs
- docs/config.md
Adds a new search mode "fuzzy" which matches as long as the characters in the query exist somewhere in the command in the same order. This is how e.g. SublimeText cmd+P search works
I'm a little worried about performance with large database files. With a ~1000 item database locally it runs no problem
> Add fuzzy text search mode

- src/command/history.rs
- src/command/init.rs
- src/command/mod.rs
- src/command/search.rs
The GitHub workflow configuration uses `cargo clippy -- -D warnings` which disallows warning. Therefore the workflow tests don't succeed. This fixes the annotations and code clippy warns about.
> Resolve clippy warnings

- src/command/login.rs
- src/command/mod.rs
- src/command/register.rs
This changes the arguments for `register` and `login` to be optional. If any arguments are not given, their content will be asked for interactively. 
This was added, because command-line arguments are readable system-wide in the process list and end up in the history. (See  #183)
Also: Great Project ^^
Closes:  #183
> feat: allow input of credentials from stdin

- Dockerfile
- docs/server.md
A small partial fix for #197 to make sure the dockerfile is up to date. Also pins the images so it won't break in future.
The changes to `cargo-chef` are just making it more like the new suggested dockerfile from their repo.
> fix: dockerfile with correct glibc

- .github/workflows/docker.yaml
- docs/server.md
Publish a docker image for each merge and each release for easier deployment for users wanting to host their own server
> chore: supply pre-build docker image

- atuin-server/src/router.rs
This simple change ended up improving the install time for me from `2:30s` to `20s`. Warp is very type heavy, and super complex types cause the compiler to be bottlenecked. When profiling, I found that rustc spent almost minute alone on monomorphisation.
You'd think that since this code is in the server crate, that you could just build that once and it would improve the build times in the core atuin bin, but that's sadly not the case.
Since this optimisation helps more in multithreaded workflows, github actions does not take full advantage of this since it uses single threaded VMs so the difference isn't noticeable there
Note:
It's worth noting that this adds a little bit of overhead to the server routes due to dynamic dispatch. But it's probably negligible
> chore: improve build times

- install.sh
Some people don't use sudo or have curl, sed or wget installed by default.
This adds a check, if sudo, curl and sed are installed and changes wget
to curl as this is the mostly used command in the script. If sudo is not
installed it uses su.
The printf was missing a newline at the end, which resulted in the eval
line being appended directly to the end of the previous line. This is 
similar to the problem from  #56.
Closes: #175
> fix: resolve some issues with install.sh

- install.sh
This is a follow-up PR for #228. It updates `install.sh` script to use `pacman` for installing `atuin` on Arch Linux, since the package is moved to the community repository.
> Update install.sh to use `pacman` on Arch Linux

- install.sh
Hello again! :bear:
I realized `install.sh` suggests using to the [atuin](https://aur.archlinux.org/packages/atuin) package for manual installation. However, that package is going to be removed soon. Also, I saw that there are no VCS or upstream-binary packages in the AUR. So I created them and changed that message to redirect users to the `-git` package instead.
- https://aur.archlinux.org/packages/atuin-git/ (VCS package) 
- https://aur.archlinux.org/packages/atuin-bin/ (Upstream binary package which is built on CD)
P.S. I also pushed e2ac898, which is a minor fix about suggesting Arch Linux users to install `lsb-release` from the community repository.
> Update messages in install.sh about the AUR packages

- README.md
- atuin-client/src/import/fish.rs
- atuin-client/src/import/mod.rs
- src/command/import.rs
- src/command/init.rs
- src/shell/atuin.fish
Closes #57
So, Fish YAML is not real YAML. So there's no point bringing out a YAML parser for this. Instead, we read line by line.
We use `- ` at the beginning to determine whether the line is a new entry. If we find a new entry line and we've found a `cmd: ...` value, we exit the loop and return our history item.
It's pretty fault tolerant, ignoring bad lines and missing values.
> Fish importing

- src/command/history.rs
- src/command/login.rs
- src/command/mod.rs
- src/command/server.rs
While working on #235, I realized that help messages for command line arguments are not shown.
```
$ atuin search --help
...
FLAGS:
-i, --interactive    
-h, --human          
--cmd-only       
--help           Prints help information
-V, --version        Prints version information
OPTIONS:
-c, --cwd <cwd>                      
--exclude-cwd <exclude-cwd>      
-e, --exit <exit>                    
--exclude-exit <exclude-exit>    
-b, --before <before>                
--after <after>                  
...
```
According to [structopt docs](https://docs.rs/structopt/0.3.25/structopt/index.html#help-messages), `help=` option should used for arguments whereas `about=` is used for subcommands. In Atuin, `about=` is used for both values.
In this PR, I've used `help=` option for arguments thus …
> Enable help messages for command line arguments

- src/shell/atuin.fish
It seems that `ATUIN_HISTORY` environment variable isn't used anywhere, and defining it loads your entire history into an environment variable. If you history gets too big, you'll get an error that your argument list is larger than the OS limit. On macOS this is 1MB.
Fixes #241
> remove unused environment var loading entire history into an env var

- src/command/search.rs
- src/shell/atuin.fish
Fixes #227 
These are both standard shell key binds, so we should be able to use them at the Atuin prompt as well.
> Add Alt+backspace and Ctrl+u keybinds for deleting by word and by line, respectively

- install.sh
dpkg is a backend tool not supposed to be used by end users for installing debs.
Also apt installs potentials dependencies.
> Replace dpkg with apt

- src/command/search.rs
Resolve #189
We were throwing an OutOfRangeError. This occurs when you attempt to
convert to a duration, and your input is <0. A value in the future would
have done this. This is especially noticeable during DST...
> Do not crash if the history timestamp is in the future

- install.sh
I was unable to install `atuin` on Ubuntu WSL. Even though detected properly by the script, it looks like the option was forgotten to be included in the distro selection.
In addition, `apt` refused to install the package from the tempfile unless it was carrying the `.deb` file extension. After adding that it worked. I assume it does not hurt to add it by default to the tempfile name.
> fix: get install.sh working on UbuntuWSL

- src/shell/atuin.bash
Based on https://github.com/wez/wezterm/commit/78ea214a96da7e9e8c8e5f3539bb788902eaff53 abd https://github.com/wez/wezterm/pull/1586/files#diff-ed9ac6e03535303bbfcddf25ca962776c502e1d0218946d7cc96319d142064a0R446-R449
> Restore bash 4.2 compatibility, only add hook once

- src/shell/atuin.fish
This change adds a binding for `Ctrl+r` and sets all the bindings to apply in both the `default` and `insert` modes (if it exists). The `insert` mode allows the keybindings to function as expected for users that use the vim keybindings in fish shell, which is quite common.
This matches the [behavior of fzf](https://github.com/junegunn/fzf/blob/205f885d6941eac47004779d9125df1463458fdd/shell/key-bindings.fish#L113-L121).
> Update fish bindings.

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
- atuin-server/src/router.rs
- atuin.plugin.zsh
- src/command/history.rs
- src/command/search.rs
```bash
$ atuin history list --cwd
Error: error returned from database: near "/": syntax error
Caused by:
near "/": syntax error
Location:
atuin-client/src/database.rs:316:19
```
1. The query into the database was not quoting the path. This fixes that issue.
2. Unused dependencies are removed:
```
atuin
- fork
atuin-client
- fern
- humantime
- indicatif
atuin-common
- eyre
- rmp-serde
atuin-sever
- chrono-english
- directories
- fern
- fork
- indicatif
- parse_duration
- rmp-serde
- unicode-width
- urlencoding
```
3. I fixed the `zsh` plugin by standardizing it according to `zdharma`. The reference can be found in the file. It results in the following:
```zsh
0="${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}"
0="${${(M)0:#/*}:-$PWD/$0}"
```
The `$commands` array is also loaded with `zmodload` …
> Fix `history list --cwd` errors

- Cargo.toml
This adds `rust-version = "1.59"` to `Cargo.toml` to indicate the minimum required version.
I tried compiling with rust 1.56 and got a bunch of compiler errors due to tuple destructuring being used, which apparently [requires rust 1.59](https://github.com/rust-lang/rust/commit/d258e92900739e7798ed4fccfbbb8cb0fe519acd). With this parameter new contributors should get a much more helpful error.
> Add rust-version to Cargo.toml

- atuin-client/src/settings.rs
- src/command/search.rs
Using this for a while I frequently ran into issues when the terminal was pretty slim, e.g. at the bottom of an IDE. So I've created a compact mode that saves 8 lines of precious terminal space.
I've added a new config option that allows to switch the style between `full`(the 'old' style), `compact` (the new one added in this PR) and `auto`, which toggles the `compact` style at a height of 14 lines (at 14 lines there are still 5 entries visible with `full` style). `auto` is used by default.
`compact` style
`full` style with my VS Code terminal for color reference.
> Add compact mode

- Cargo.lock
- Cargo.toml
- src/command/history.rs
- src/command/import.rs
- src/command/init.rs
- src/command/login.rs
- src/command/mod.rs
- src/command/register.rs
- src/command/server.rs
- src/command/stats.rs
- src/main.rs
Updated to use clap 3.1.x instead of structopt.
> Update to clap 3.1.x

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
f861893 Update to clap 3.1.x (#289)
e8f7aac Add compact mode (#288)
1e04c4c Add rust-version to Cargo.toml (#287)
222e52b Update Dockerfile
fae118a Improve fuzzy search (#279)
7cde55a Add code of conduct (#281)
d270798 Update config-rs (#280)
3248883 Update README.md
7f58741 Fix `history list --cwd` errors (#278)
e117b62 Update fish bindings. (#265)
4223ac6 Restore bash 4.2 compatibility, only add hook once (#271)
7651f89 Add support for blesh  (#267)
c2dd332 fix: get install.sh working on UbuntuWSL (#260)
84403a3 Bump reqwest from 0.11.7 to 0.11.9 (#261)
5005cf7 Bump serde_json from 1.0.73 to 1.0.75 (#262)
7fa3e1c Do not crash if the history timestamp is in the future (#250)
8d21506 use sqlite grouping rather than subquery (#181)
d36ff13 Replace dpkg with apt (#248)
> Release v0.8.1

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/settings.rs
- atuin-server/Cargo.toml
- atuin-server/src/settings.rs
Config like `ATUIN_DB_PATH` were being parsed as `db.path` rather than `db_path`.
This would technically be a breaking change, but atuin has no nested settings just yet, so crisis averted
> fix env config parsing

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
- atuin-client/src/encryption.rs
- atuin-client/src/settings.rs
- atuin-server/Cargo.toml
- atuin-server/src/settings.rs
- src/command/logout.rs
[fs-err](https://docs.rs/fs-err/2.7.0/fs_err/) is a drop in replacement for std::fs which provides better error messages.
This also addresses #270
> provide better error messages

- atuin-server/src/database.rs
- atuin-server/src/handlers/history.rs
- atuin-server/src/handlers/user.rs
By default read from the count cache - if there is no value there, then
do a full COUNT. The cache will be filled when the user posts up some
more history
Eventually I'd like to replace the full COUNT function with reading from
the cache, but that can only be done once all users have a cached value
> Use the count cache

- atuin-server/src/database.rs
I just deployed the older version and it was falling back on the full
count. Turns out this is because it won't upcast from INT4 to INT8
automatically, and it has to be manual
At some point the underlying total should be changed to int8, but also I
highly doubt anyone will have enough shell history to fill an int4 lol
> Fix SQL cache query

- .github/workflows/rust.yml
- Cargo.lock
- Cargo.toml
- README.md
- atuin-client/src/database.rs
- atuin-client/src/settings.rs
- docs/config.md
- src/command/client/history.rs
- src/command/client/search.rs
- src/command/client/stats.rs
Switch between different search modes to narrow down the history you
want - global search for all history, host for all history from your
current machine, session for the current shell session, and directory
for the current directory
The default can be configured via `filter_mode`
> History filter

- Cargo.toml
- atuin-client/Cargo.toml
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
89549b3 Bump uuid from 0.8.2 to 1.0.0 (#311)
831cc98 Fix typos in the docs. (#171)
7436e4f feature-flags (#328)
508d4f4 History filter (#329)
02c70de refactor (#327)
a9d1ece Added docker-compose.yml (#325)
b8bdd83 Bump clap from 3.1.10 to 3.1.11 (#323)
52a3d0c Bump tracing from 0.1.33 to 0.1.34 (#324)
79597b0 Bump clap_complete from 3.1.1 to 3.1.2 (#316)
5aca611 Allow for larger commands (#321)
9085485 tracing (#315)
98d70fb treat popos as ubuntu (#319)
d57f549 refactor commands for better separation (#313)
24e2971 Fix SQL cache query (#318)
fe05d86 Fix delete trigger (#317)
48747e3 A few minor tweaks (#314)
ed4e07d Use the count cache (#312)
6e11b8e Bump clap from 3.1.9 to 3.1.10 (#309)
44e417d Bump axum from 0.5.1 to 0.5.3 (#310)
b98a378 Add count trigger (#308)
7fe523a Bump sqlx from …
> Release v0.9.0

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
> sql builder

- .github/workflows/release.yaml
- .github/workflows/rust.yml
This PR adds `--locked` flag to `cargo build` commands in CI/CD workflows. This is beneficial for spotting the outdated lockfile issues mentioned in #336
> Use `--locked` flag for CI builds

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
Fixed to include an updated lockfile that was missed in the last release
Thank you for the rapid report @orhun!
a050faa Use `--locked` flag for CI builds (#337)
8737474 Update Cargo.lock (#336)
eab1dbf sql builder (#333)
> Release v0.9.1

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/src/api_client.rs
- atuin-client/src/history.rs
- atuin-client/src/sync.rs
- atuin-common/Cargo.toml
- atuin-common/src/utils.rs
- atuin-server/Cargo.toml
- src/command/client/history.rs
- src/command/client/search.rs
sha2 is much more trusted and up to date than rust-crypto.
Our use of TabWriter ended up causing some awkward behaviour. TabWriter tries to make each tab stop be at the same position, and the fact we had very varying sizes in our command stage, caused these tabs stops to be sometimes many lines down.
In my case, I had a single command span 5 lines, this caused all other commands to similarly span those same 5 lines without needing to.
The fix here is to swap the order of the command and the duration.
~~For a little flare, I've added some colour to the duration to be more consistent with some of our other setups~~ removed as I think our primary use case for this subcommand was interop with fzf, which does not support ansi
> history list

- atuin-server/src/database.rs
It's not ideal as we should be explicit about what is being queried!
A part one for sorting this all out :)
> Remove all select * from the server queries

- atuin-client/src/database.rs
I think chrono/sqlx was turning the datetime items into second based timestamps, whereas we store them in nano form
> fix db range query

- .gitignore
- .rustfmt.toml
- atuin-client/src/api_client.rs
- atuin-client/src/database.rs
- atuin-client/src/encryption.rs
- atuin-client/src/history.rs
- atuin-client/src/import/fish.rs
- atuin-client/src/import/mod.rs
- atuin-client/src/import/resh.rs
- atuin-client/src/import/zsh.rs
- atuin-client/src/ordering.rs
- atuin-client/src/settings.rs
- atuin-client/src/sync.rs
- atuin-server/src/database.rs
- atuin-server/src/handlers/history.rs
- atuin-server/src/handlers/mod.rs
- atuin-server/src/handlers/user.rs
- atuin-server/src/settings.rs
- src/command/client.rs
- src/command/client/event.rs
- src/command/client/history.rs
- src/command/client/import.rs
- src/command/client/search.rs
- src/command/client/stats.rs
- src/command/client/sync.rs
- src/command/client/sync/login.rs
- src/command/client/sync/register.rs
- src/command/server.rs
- src/main.rs
Imports sorted in order:
- stdlib
- external crates
- atuin/internal
> ignore JetBrains IDEs, tidy-up imports

- src/command/client/search.rs
This pull request adds a new option to the search command, allowing to limit the returned results from the database.
> Search: Allow specifiying the limited of returned entries

- .gitignore
- src/command/client.rs
- src/command/client/stats.rs
Solves for #18 .
Modifies `stats` to work without sub command 
This currently works as;
```
> atuin stats
> atuin stats last friday 
> atuin stats 01/01/2022
> atuin stats monday
> atuin stats march
```
> Adds stats summary 

- src/command/client/search.rs
For folks coming from [fzf](https://github.com/junegunn/fzf), ctrl-k and ctrl-j would be great to have as options for up and down respectively in the interactive search.
Thanks for the project! This looks great and I'm excited to use it.
> Add ctrl-k and ctrl-j for up and down

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
- atuin-client/src/import/bash.rs
- atuin-client/src/import/fish.rs
- atuin-client/src/import/mod.rs
- atuin-client/src/import/resh.rs
- atuin-client/src/import/zsh.rs
- src/command/client.rs
- src/command/client/history.rs
- src/command/client/import.rs
- src/command/client/search.rs
- src/command/client/stats.rs
- src/command/client/sync.rs
- src/command/mod.rs
- src/command/server.rs
- src/main.rs
The old API was clever, but sacrificed a lot of flexibility.
This is much more naive, simple and should be more flexible and probably more performant too
> Importer V3

- .github/workflows/docker.yaml
- Dockerfile
This PR updates the GH Action docker workflow to cross-build the docker
image for ARM using QEMU.
This theoretically works but takes about 2.5 hours for a clean build,
which may or may not be tolerable for each commit on `main`.
An action run where the dependencies are already cached needs about 15
minutes with this PR.
Closes #269
> Build ARM docker image in GitHub Actions using QEMU

- atuin-server/src/settings.rs
...respect ATUIN_CONFIG_DIR.
The current behaviour is problematic when running atuin server as a
system service with config dir in /etc/atuin.
> Don't create config dir for server in default location if not needed

- Cargo.toml
- src/command/mod.rs
I’m packaging atuin for Alpine Linux and I’m building the atuin client and server as separate binaries, provided in separate (sub)package.
> Allow to build atuin server without client

- docs/key-binding.md
Add the missing fish shell part into the documentation for ATUIN_NOBIND.
Binding to up is pretty problematic in fish, as if you want to navigate the pager for auto-suggestions, you tend to get a bit stuck.
> Add fish shell to key binding docs

- src/shell/atuin.fish
Binding on "up" can conflict with the default fish keybindings as when in tab-completion mode, you are supposed to be able to use arrow keys to navigate the grid of suggestions, however pressing "up" will open the tui instead.
This attempts to work around it by tracking when the user is probably in a tab completion mode by setting a variable that we use to determine whether to open atuin or perform the default fish up action
This should partially address the issues raised in #419
> Improve default fish keybindings

- Cargo.lock
- Cargo.toml
- src/command/client/sync/login.rs
- src/command/client/sync/register.rs
Addresses https://github.com/ellie/atuin/issues/344.
I've added a dependency of rpassword since I figured the library would be able to handle the password input better across different platforms compared to something that I would write. I'm also not sure if the Cmd struct for login and register should remain since there are no longer any "options" to use with them.
Do let me know if these changes make sense. Thanks!
> Adds password prompt for register and login

- src/command/client/search.rs
<h3 align="center"><img src="https://user-images.githubusercontent.com/47924309/168497142-b35d562b-e76a-4311-b7f1-939fadfe8fe9.gif" width="75%"/><br/><i>Demo</i></h3>
I added a field called _cursor_index_ to the _State_ struct. Every function interacting with the user input now has to use this value, so it's not a trivial change.
I added the following keybinds:
- Control + w (delete back one word)
- Control + a (go to the beginning of the line)
- Control + e (go to the end of the line)
These are the default bash keybinds for these operations, adding more should be fairly simple.
I also modified what I believe to be all places in the _search.rs_ file affected by this, namely the other keybinds and the draw functions.
For some reason, the _Key::Right_ and _Key::Left_ keybinds don't do …
> Implement cursor

- atuin-client/src/import/zsh_histdb.rs
Bug fix for zsh_histdb import where if a directory name or hostnames had non-ascii characters that the import would crash.
> Noyez fix dir hostname utf8

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
06ac9587 Show current version on server index (#436)
706b1aff Disable ARM docker builds (#438)
f2abc23a Update README.md
3c2b0550 Noyez fix dir hostname utf8 (#430)
3f5350de [feature] Add scroll wheel support to interactive history search (#435)
dcdde225 Fix text outline for dark mode
9ac0c60c Implement cursor (#412)
119ab9e0 Adds password prompt for register and login (#424)
e5df809d Noyez zsh histdb import (#393)
b08e2543 Improve default fish keybindings (#420)
4096c6ee Update README.md
cd2a3ab7 Add fish shell to key binding docs (#418)
b2782110 Bump clap_complete from 3.1.3 to 3.1.4 (#397)
ee66c0a1 Bump axum from 0.5.5 to 0.5.6 (#415)
4297e263 Bump tokio from 1.18.1 to 1.18.2 (#396)
dbd9ca53 Bump clap from 3.1.16 to 3.1.18 (#401)
a7c9d19d Bump tower-http from 0.3.2 to 0.3.3 (#399) …
> Release v0.10.0

- src/shell/atuin.bash
- Pass READLINE_LINE so current bash buffer is provided
- Bind `up` to atuin as is done for zsh/fish and mentioned in docs
- Clean up indentation/newlines
- Follow optional shellcheck "style" checks for escaping/encapsulating
Fixes #428
Fixes #431
> Enhancements to bash init script

- atuin-server/migrations/20220610074049_history-length.sql
- atuin-server/src/database.rs
- atuin-server/src/lib.rs
- atuin-server/src/settings.rs
This allows servers to decide the max length of each history item they
want to store! Some users might have much larger history lines than
others.
This setting can be set to 0 to allow for unlimited history length. This
is not recommended for a public server install, but for a private one it
can work nicely.
Resolves #416
> Add configurable history length

- atuin-server/src/router.rs
- atuin-server/src/settings.rs
- docs/server.md
I didn't want to set up a domain for this, so I attempted to add support for putting it in a different path.
> Add support for prepending a path to all routes for the server

- .github/dependabot.yml
Regarding the discussions in https://github.com/ellie/atuin/pull/506, I suggest to add the dockerfile in dependabot's scope.
It will create more PRs but will help keeping everything up to date :)
> Add dockerfile in dependabot scope

- src/shell/atuin.bash
- src/shell/atuin.fish
- src/shell/atuin.zsh
The use of `--` in the shell scripts prevents clap attempting to parse
the command name as a flag, in the case that it starts with `--`.
Previously, atuin would crash with the following error, if a command starting with `--` is used:
```shell
jamie@chronos (zsh) in atuin on  fix-double-dash via 🦀 v1.63.0 within  rust-nix-shell
<I> ➜ --example
error: Found argument '--example' which wasn't expected, or isn't valid in this context
If you tried to supply `--example` as a value rather than a flag, use `-- --example`
USAGE:
atuin history start [COMMAND]...
For more information try --help
```
> Fix atuin crashing on commands that start with --

- Cargo.toml
This adds support for installation via [binstall](https://github.com/ryankurte/cargo-binstall). It's simply a set of configuration settings that allows the binstall tool to locate precompiled binaries in the existing GitHub releases. This allows users of binstall to skip the compilation step if a prebuilt binary is available.
> Add binstall configuration

- atuin-client/migrations/20220806155627_interactive_search_index.sql
Related #475 (cc @Byron)
This PR adds an index intended to improve the query for interactive search
I was able to artificially create bad startup times for `atuin search --interactive` by adding several thousand entries to my history with the same command. This stresses the `max(timestamp)` for a given command because there is no index to relate timestamps to their respective commands. With this I was able to reproduce an over 2 second startup time which became well under 1 second after this change
Opening as a draft because I want to see if this impact is noticeable for more organic histories. You can test by manually creating this index on your `history.db`
NOTE: for local testing your system installed `atuin` will get angry if extra migrations are applied that it doesn't recognize. You …
> Add index for interactive search

- src/command/client/search.rs
- src/command/client/search/cursor.rs
- src/command/client/search/history_list.rs
- src/command/client/search/interactive.rs
- src/main.rs
This is a pretty fun one. Uses a custom `HistoryList` impl rather than the default `List` that `tui` provides. This means we can output the history rendering lazy rather than eagerly allocate on every render.
Average CPU usage of rendering seems to have halved, which is nice for battery and latency (although I haven't really observed much by eye).
This also has a fix for #244 by using a custom list state that is aware of the 10 row offset.
https://user-images.githubusercontent.com/6625462/189717736-bc1f7b7c-5c70-41b5-9639-f3f23f1055f3.mov
> custom history list

- src/command/client.rs
- src/command/init.rs
- src/command/mod.rs
Fixes an issue where gen-completions fails in restricted build environments while trying to create a config directory.
Settings::new() and Sqlite::new() are currently run unconditionally for every client command, even if those commands don't need access to the settings or database. This would cause running ```atuin gen-completions``` in a restricted build environment to fail while trying to create a path to the config directory.
This PR splits the client commands into two subsets, one subset that requires access to the settings/database and one that does not. Settings::new and Sqlite::new are then only called for the subset of commands that need them.
I think this is the most elegant approach to solving this issue, the other alternative would have been to move the calls to Settings::new …
> Allow stateless commands to be run without config/database

- src/shell/atuin.zsh
Since we pass $BUFFER to atuin search, retaining RBUFFER (the part of the buffer to the right of the cursor) on accepting a history replacement probably doesn't make sense. The advantage of setting RBUFFER and LBUFFER separately instead of setting BUFFER is that the cursor is positioned after the end of LBUFFER instead of remaining where it was before atuin was called.
Alternatively, _atuin_search() could pass $LBUFFER to atuin instead of $BUFFER which would allow the widget to replace parts of command lines (such as the initial parts of a shell pipeline), but I would prefer the default to replace the whole command line from the history.
A widget that only replaces parts of command lines could be added separately if there's interest in it, though users could always just add it themselves …
> Clear RBUFFER when accepting output from atuin

- atuin-client/config.toml
- docs/config.md
I came across #288 by accident, wanted to try compact mode but couldn't figure how to. Turns out the option wasn't added to `config.toml`. Hope that makes sense to add it.
Also added to `config.md`.
> Add `style` to config.toml and config.md

- src/shell/atuin.fish
PR #420 addressed the existence of pagination in a fish prompt by trying to track when pagination was enabled and disabled. This introduced atuin-specific bindings for common keys: `\t`, `\e`, `\r`, and `\n` which export a variable and informs the `_autiun_search` function to not show the TUI.
Fish has a commandline function that will instead tell you whether pagination is enabled so the user doesn't need to keep track of that state. This PR uses this function, `commandline -P` to replace the prior TUI supression scheme. Removing these extra function calls allows us to remove the additional bindings which were breaking fish vi key bindings.
Replacing the value for `bind -M insert \e` completely breaks vi mode by blocking the user from exiting insert mode. By removing these extra binds, …
> Fix compatability with fish vi key bindings

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/config.toml
- atuin-client/src/api_client.rs
- atuin-client/src/settings.rs
- atuin-common/src/api.rs
- atuin-server/src/handlers/mod.rs
- docs/config.md
- src/command/client.rs
- src/command/client/history.rs
- src/command/client/search.rs
- src/command/client/search/interactive.rs
- src/main.rs
Check for updates, and show a message if there is one available!
I'm going to be rolling out deletion support over several versions, as it's _complicated_ and changes how sync and history is transferred. This way, we make it more likely that people will follow the updates on time.
My Rust is a teeny bit rustier than I'd like, it's been a little while 😞
> Add automatic update checking

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-common/Cargo.toml
- atuin-server/Cargo.toml
- Bump sha2 from 0.10.5 to 0.10.6
- Bump uuid from 1.1.2 to 1.2.1
- Bump serde_json from 1.0.85 to 1.0.86
- Bump itertools from 0.10.4 to 0.10.5
- Bump serde from 1.0.144 to 1.0.145
> rollup of 5 dependency commits

- Cargo.lock
- atuin-client/Cargo.toml
Change `reqwest` to use platform native certs, so it' possible to sync with server, which uses cert signed by custom trusted root ca. 
Problem described in #570.
> Configure reqwest to use native platform certs

- atuin-client/src/import/fish.rs
Fish shell doesn't use the variable `HISTFILE` to set the shell history location, and instead always uses the default location in $XDG_DATA_HOME/fish/.
Closes #572
> Never use HISTFILE for fish shell import

- src/shell/atuin.fish
Fish shell has a private mode builtin, where commands are not written to the history file. This change only allows `atuin history start` when the fish shell is not in private mode.
See here for details on Private mode in fish: https://fishshell.com/docs/current/interactive.html?highlight=private#private-mode
Related #517
> Respect fish shell's builtin private mode

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/src/settings.rs
- docs/stats.md
- src/command/client/search.rs
- src/command/client/stats.rs
Hello 👋🏻 
I just spent a bit of time figuring out what the stats command can do and what the proper syntax is. I figured I'd spare some people some searching in the future by updating the documentation.
* Document the use of `chrono_english` and point to its documentation for date formatting.
* Document the fact that one can manipulate a 24h window, rather that just a specific day.
* Document the relationship with the `dialect` option in the configuration.
* Update the existing examples and add a few more.
Also, I think the stats command's help is a bit misleading for 2 reasons:
* The argument name `period` seems like a misnomer. Based on the code, the period is fixed, it's either 1-day or all of history. What the users really give is a starting point for that 1-day period.
* `period` is …
> docs: add more details about date parsing in the stats command

- src/command/client/search.rs
This enables scripts to more easily detect when no results are found.
> Exit with return code 1 when no results are found in `atuin search` command

- .github/workflows/release.yaml
Not entirely sure how to test this workflow.
I updated the runners as the current ones being used are deprecated, and GitHub really seems to want people to move to newer ones.
I'm confused: why weren't ARM64 builds being made? The workflow literally has cases to handle it...
Fixes https://github.com/ellie/atuin/issues/369
> Build ARM64 releases & update runners

- atuin-client/migrations/20220505083406_create-events.sql
- atuin-client/src/database.rs
- atuin-client/src/event.rs
- atuin-client/src/lib.rs
- atuin-client/src/sync.rs
- atuin-common/src/api.rs
- atuin-server/migrations/20220505082442_create-events.sql
- src/command/client/history.rs
- src/command/client/search/history_list.rs
Start storing an event log locally! 
This will allow us to eventually start syncing events, rather than pure history items.
When merging an event log, we will pair up CREATEs with DELETEs. If there is a pair, we won't create the history. If there is not a pair (and just a CREATE), then the item is created. I've also started on the server end of this, while I had the context in my head. Obviously it's no use just yet
I've been running this branch locally for a bit, and have had no issues.
> Add local event log storage

- src/command/client/search/history_list.rs
For long commands that had sections (i.e. whitespace) that started beyond the width of the list, an underflow error would occur. This fixes this error by avoiding trying to print a command section beyond this boundary.
Fixes #596
> fix #596: Avoid drawing a command section beyond the width  of the list

- atuin-client/config.toml
- atuin-client/src/settings.rs
- docs/config.md
- src/command/client/search/interactive.rs
fixes #422
This introduces a new setting that can configure the behaviour when pressing `Esc` in interactive mode. Currently with only 2 options, to either return the empty string (and keeping the commandline unmodified), or returning the currently written query so far.
> Add setting for keeping typed query when exiting

- docs/config.md
This section of the config docs just used the wrong example text.
Closes #584
> Fix minor typo in config.md

- .github/workflows/docker.yaml
The issues from the linked issue seemed to be closed, so I re-enabled arm docker builds to check.
[The build succeeded](https://github.com/patricksjackson/atuin/actions/runs/3485248571), and you can find the packages [here](https://github.com/patricksjackson/atuin/pkgs/container/atuin). I haven't had the chance to manually test it yet.
Closes #439
> Re-enable arm docker builds

- src/shell/atuin.fish
Clean up the `_atuin_bind_up` function for the fish shell.
* Gives control back to fish in search- or paging-mode
* Correctly handles multiline commands
A user can still enter fish's search-mode by invoking `up-or-search` directly, so we probably want to let them do that.
Tested manually
Closes #622
> Handle multiline commands in fish shell

- install.sh
Offers to fallback to installing from cargo when we can't determine the distro.
Closes #590
> install.sh: Fallback to using cargo

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/settings.rs
- docs/config.md
- src/command/client.rs
- src/command/client/search.rs
- src/command/client/search/interactive.rs
- src/shell/atuin.bash
- src/shell/atuin.fish
- src/shell/atuin.zsh
This PR allows overriding filter and search modes from CLI arguments:
```
--filter-mode <FILTER_MODE>    Allow overriding filter mode over config [possible values: global, host, session, directory]
--search-mode <SEARCH_MODE>    Allow overriding search mode over config [possible values: prefix, full-text, fuzzy]
```
The bash _up_ key bindings are updated to always use `session` filter mode when invoking atuin, and that choice may not be acceptable by other.
TODO:
> Allow overriding filter and search modes from CLI

- README.md
- docs/key-binding.md
- src/command/init.rs
- src/command/mod.rs
- src/shell/atuin.bash
- src/shell/atuin.fish
- src/shell/atuin.zsh
This allows users to disable the CTRL-R and Up Arrow bindings, independently from one another.
The default is to bind both, but by adding `--disable-ctrl-r` or `--disable-up-arrow` (or both!) to the invocation of `atuin init <shell>` in the shell rc file, each can be disabled.
> Rework `atuin init`

- atuin-client/src/database.rs
> Improve error message when $AUTIN_SESSION is not set.

- Cargo.lock
- Cargo.toml
- src/command/client/history.rs
- src/command/client/search.rs
- src/command/client/search/duration.rs
Fixes #619 
Hey, that's an easy one to implement but I'm not sure what's the best way to display it, here's a few examples:
```
❯ cargo run history list 2>/dev/null | tail -n1
2023-01-11 20:35:26     < /home/baptiste/github.com/BapRx/atuin >       cargo run history list 2>/dev/null | tail -n1   0s
❯ cargo run history list 2>/dev/null | tail -n1
2023-01-11 20:35:44     === /home/baptiste/github.com/BapRx/atuin ===   cargo run history list 2>/dev/null | tail -n1   0s
❯ cargo run history list 2>/dev/null | tail -n1
2023-01-11 20:36:00     (/home/baptiste/github.com/BapRx/atuin) cargo run history list 2>/dev/null | tail -n1   0s
❯ cargo run history list 2>/dev/null | tail -n1
2023-01-11 20:36:17     [/home/baptiste/github.com/BapRx/atuin] cargo run history list 2>/dev/null | tail -n1   0s
❯ …
```
> feat(history): Add new flag to allow custom output format

- atuin-client/config.toml
Looks like this snuck in in the original config file here https://github.com/ellie/atuin/commit/9f16f76bd8d15824e27e971245ea93271fe76b29#diff-28043ff911f28a5cb5742f7638363546311225a63eabc365af5356c70d4deb77R13
> Remove whitespace in template client config.tom

- src/command/client/sync/login.rs
If the given key on login in empty, keep the existing key file rather
than overwriting it with an empty file. This is useful if you log out
and want to log in again and still use the same key, or if you have
copied over the key file rather than providing it as input.
Before the first commit, an empty key file would be created if key
wasn't specified, and after that commit, the key file would not be
created if the key wasn't specified and stay empty if it was empty.
With the second commit the log command checks the key file if a key is
not specified and exits with an error message if either the key file
couldn't be opened or is empty. If a key is specified, the key file is
just created with it as before.
(Btw, great talk at fosdem!)
> Allow using existing key file on login

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/config.toml
- atuin-client/src/settings.rs
- src/command/client/history.rs
Adds a new `history_filter` setting through which users can specify a list of regular expressions that match commands that should not be recorded in the history.
Example configuration:
```toml
history_filter = [
"^secret-cmd",
"^innocuous-cmd .*--secret=.+"
]
```
Fixes #515
> Add `history_filter` setting to exclude commands from history

- src/shell/atuin.fish
When I try to do `atuin init` I get a error from fish, suggesting to replace `$*` with `$argv`.
This patch does that and makes fish accept with `atuin init fish --disable-up-arrow`. I did not do much testing after that though :-)
> fish: Fix `atuin init` for the fish shell

- .gitignore
- README.md
- atuin.nix
- flake.lock
- flake.nix
Add a flake.nix to facilitate easier development on NixOS, and to allow atuin to be installed using `nix profile`. Also add a nix section to the install instructions in the readme
> Add nix files and install instructions

- .github/workflows/docker.yaml
They're failing on ARM atm, maybe this will help
> Enable RUST_BACKTRACE for docker builds

- .github/workflows/docker.yaml
Docker builds are failing on ARM, let's see if they work on AMD.
Might be worth waiting until we have less C that needs building
This reverts commit f3894ef9c0c9d2d9effa963b116d0075d4e7a9e5.
> Revert "Re-enable arm docker builds (#616)"

- docs/docs/commands/stats.md
- docs/docs/commands/sync.md
- docs/docs/config/config.md
Add anchors while at it.
I verified by running the docs with `yarn start` locally
> [docs] fix some links between config and commands

- src/tui/buffer.rs
These tests expect `debug_assert!` to panic, so should only run in debug mode:
- `pos_of_panics_on_out_of_bounds`
- `index_of_panics_on_out_of_bounds`
I came across this problem when [my COPR build](https://copr.fedorainfracloud.org/coprs/cyqsimon/el-rust-pkgs/builds/) failed, because I ran `cargo test --release` in the build script.
> Disable 2 tests that shouldn't run in release mode

- atuin-server/src/handlers/user.rs
Fixes #739.
Note, this is why we don't want `Extension` anymore 😅, because it's dynamic and not static. `State` is static so if you don't provide the state it won't compile.
> fix registration

- flake.lock
Updates the rust version pinned in `flake.lock` to 1.67. The changes in this PR are a result of `nix flake update`.
> Update flake.lock to Rust 1.67

- default.nix
- flake.lock
- flake.nix
Support nix (non-flakes), continuation of #477.
- tested changes on top of v12.0.0 (cargo test fails for nix on v13.0.0)
```
[shell:~/atuin]$ nix-shell
[nix-shell:~/atuin]$ cargo build
[...]
Compiling atuin-client v12.0.0 (/root/atuin/atuin-client)
Compiling atuin-server v12.0.0 (/root/atuin/atuin-server)
Compiling atuin v12.0.0 (/root/atuin)
Finished dev [unoptimized + debuginfo] target(s) in 1m 34s
[nix-shell:~/atuin]$
```
```
[shell:~/atuin]$ nix-build -A packages.aarch64-linux.atuin
[...]
/nix/store/ri763ifjs3vrba8s3w64lan24j34mm54-atuin
```
> nix: add flake-compat

- atuin-common/src/utils.rs
These 4 tests cannot be run in parallel, because one of them could be unsetting an environment variable when another is expecting it to be set.
For an example, see [here](https://github.com/ellie/atuin/actions/runs/4306003050/jobs/7509233843).
> Fix race condition in directory tests

- atuin-client/src/import/bash.rs
Closes #745
- Imported history is now ordered correctly
- Timestamps (when `HISTTIMEFORMAT` is set) are handled correctly
> Rework Bash import

- atuin-client/config.toml
- atuin-client/src/settings.rs
- src/command/client/search/cursor.rs
- src/command/client/search/history_list.rs
- src/command/client/search/interactive.rs
For [[Feature Request] Custom keyboard shortcuts · Issue #610 · ellie/atuin](https://github.com/ellie/atuin/issues/610).
> feat: add common default keybindings

- atuin-client/src/settings.rs
- src/command/client/sync.rs
- src/command/client/sync/login.rs
- src/command/client/sync/logout.rs
When setting the `session_path` config to a non-default value, `auto_sync` and `sync_frequency` were having no effect for me.
After digging into the code, I noticed that `settings.should_sync()` and the `login` and `lougout` commands were reading `session_path` as `atuin_common::utils::data_dir().join("session")` which was not the same as the value I set in my `config.toml`.
This PR should standardize all the places that read `session_path` to `settings.session_path`, which was already how it was done in a few places including the `register` command.
**Note**: I've basically never written Rust before and while making these changes I'm attempting to get my local env setup for Rust dev, but things are still installing as I type this. So there's a good chance this doesn't even compile but …
> fix(client): always read session_path from settings

- src/command/client/stats.rs
Some people wanted `sudo` to be ignored, and then some commands like `cargo` and `git` are so prevelant that the stat isn't interesting. This addresses both of those, although it's a little opinionated for now
> add common prefixes and subcommands to stats

- install.sh
On my arch system, the value of `/etc/os-release` is `arch` rather than `Arch`, which caused the OS check to fail. This change uses `tr '[:upper:]' '[:lower:]'` to switch everything to lowercase so we don't need to worry about case-sensitive comparisons.
> fix(installer): use case-insensitive comparisons

- src/command/client/search/interactive.rs
Fixes the bug that I tried to fix in https://github.com/ellie/atuin/pull/754.
The bug was that it was not distinguishing between `Release` and `Press`. The "fix" *was* to throw away one  input. But this is pragmatic because:
- Git bash does not send both `Release` and `Press`.
- Cgywin compiles it for linux, runs it as linux, thus the fix wont work.
This fixes it by throwing away any `Release` ones.
> Fixes a bug on windows

- atuin-client/src/database.rs
- atuin-common/src/utils.rs
- src/command/client/history.rs
- src/command/client/search.rs
This PR uses the PWD environment variable if it is available instead of calling `env::current_dir()`.
Motivation: I was short on storage space in my main `/home/user` filesystem, so I moved all my `/home/user/workspaces` to another disk at `/home/newdisk/user/workspaces`, then created a symbolic link from `/home/user/workspaces` to `/home/newdisk/user/workspaces`.
To my dismay, when I searched my command history with the `directory` filter mode, nothing showed up.
For reference:
* https://github.com/rust-lang/rust/issues/93598#issuecomment-1028624102
* https://stackoverflow.com/a/71625035/316805
> Prefer PWD environment variable over cwd if available to better support symbolic links

- atuin-client/src/database.rs
- atuin-client/src/sync.rs
- src/command/client/search.rs
Our search command will de-dupe results by default. But... This isn't great for deleting! You don't want to run it over-and-over-and-over until all commands are deleted.
Loop the query, and keep on deleting what it returns until they are all gone.
> Delete all instances of a command

- src/command/client/search/interactive.rs
I set `exit_mode` to `return-query`, and since the introduction of https://github.com/ellie/atuin/pull/659, I'm often caught loosing everything I typed.
An additional improvement may be to add a visual indicator that we are on the last history item, thus giving an hint that pressing the arrow down key will exit.
> feat: respect exit_mode setting when exiting with arrow down keypress

- Cargo.lock
- Cargo.toml
- atuin-client/src/settings.rs
- src/command/client/search/interactive.rs
- Use crossterm and inline viewport
- Reposition cursor on exit and fix `The cursor position could not be read within a normal duration` errors due to blocking reads
> feat: add an inline view mode

- .github/workflows/release.yaml
Closes #144 
This adds musl build for atuin. The passing build is here https://github.com/InCogNiTo124/atuin/actions/runs/4494208666/jobs/7907368484
Some further points:
1. I am not familiar with binary stripping so musl build uses the default strip installed with musl-tools - it _should_ be correct but I could not verify that
2. I could not find the corresponding documentation for me to update. If there is any, please direct me to it :D
> Add musl build

- CONTRIBUTING.md
- atuin-server/src/handlers/status.rs
Thanks for finding this @YummyOreo!
tl;dr is that we have a count cache, as postgres isn't a great column store. This cache is built when a user pushes up history - if the user is new, they have not pushed up history. With the old endpoint, we fell back to a full count (this would only ever be needed once).
> Account for user not yet having count cache

- src/shell/atuin.nu
If you would press `Enter` it would record it. I don't think that this is intended.
> Fixes nushell recording empty commands

- src/shell/atuin.nu
Without the `=` I get the error on pressing `Ctrl + C`:
```
error: Found argument '-1' which wasn't expected, or isn't valid in this context
If you tried to supply '-1' as a value rather than a flag, use '-- -1'
Usage: atuin history end --exit <EXIT> <ID>
For more information try '--help'
```
> fix: record negative exit codes

- src/command/client/history.rs
- src/command/client/search.rs
- Add `{exit}` which returns the exit code
- Add `{relativetime}` which gives a relative time, e.g. "5h"
> Add more fields to `atuin search --format`

- atuin-client/src/database.rs
- src/command/client/search.rs
This flag allows the user to continue searching at an offset. This is useful for building tools that use atuin to search for previous commands and return only one result.
```
atuin search --limit 1
atuin search --limit 1 --offset 1
atuin search --limit 1 --offset 2
```
> Add `--offset` flag to `atuin search`

- atuin.nix
This change saves us from needing to keep a copy of the checksum in atuin.nix, so that Cargo.lock can remain as the sole source of truth for the dependency versions.
This fixes the nix build, as it currently fails because the `ratatui` dep is fetched from Conrad's git repo instead of the registry. I also added some comments to help maintain the package.
> fix: allow nix package to fetch dependencies from git

- .github/workflows/nix.yml
This adds an action that will run a `nix flake check`, which checks the nix configuration, and `nix build`, which builds atuin using the nix config. Failures in this workflow will indicate that flake.lock needs to be updated with `nix flake update` or a change is needed in the configuration files.
This requires #832 to pass. I verified locally using [act](https://github.com/nektos/act) that it succeeds with that change.
> feat: add github action to test the nix builds

- atuin-client/src/sync.rs
This can occur if history has been added + then deleted on a machine before it has a chance to be synced to a new one.
> Fix deleting history that doesn't exist yet

- atuin-client/config.toml
- atuin-client/src/settings.rs
- docs/docs/config/config.md
- Example `config.toml` now includes all the newest options
- Example `config.toml` now have default values consistent with the actual default (except for the paths)
- `settings.rs`, `config.toml`, and `config.md` now have uniform option order
> Updated client config docs

- src/shell/atuin.nu
Hi, nushell's `str substring` doesn't accept string argument, I'd like to propose a update to use nushell range instead
> update `str substring` usage to use range parameter

- atuin-client/src/import/fish.rs
I cherry picked the commit from #601. That PR was closed after some inactivity. 
On MacOS, atuin was looking for fish history under "$HOME/Library/Application Support".
Now atuin honors XDG_DATA_HOME, if set, and otherwise uses "$HOME/.local/share".
closes #682
> Use XDG data directory for fish import

- src/command/client/search/interactive.rs
This adds some common Emacs movement keys. Since Emacs mode is also the default for most shells the keys should be familiar to a lot of people. I kept accidentally adding `f`s and `b`s to the search buffer when trying to jump around ...
I also added an exception for a clippy lint caused by the additional match branches. It's not ideal but I'm not sure breaking up the function would be better.
> Add some emacs movement keys

- atuin-client/src/database.rs
- docs/docs/commands/search.md
- src/command/client/search.rs
Add `-r/--reverse` flag to `atuin search` to allow searching by oldest results first.
Example to find the oldest `cargo` command:
```
atuin search --limit 1 --reverse cargo
```
> Add `--reverse` to `atuin search`

- atuin-client/src/import/zsh.rs
I just had the same thing as the person in issue #850: I hadn't exported my $HISTFILE variable (which I think is probably not an uncommon thing to do; for users who *don't* use atuin it's usually only the shell, not other programs, that interact with the history file). I was able to find the github issue that described it, but figured it would be helpful to include this suggestion in the error message.
> Improve error message for issue #850.

- atuin/src/command/client/search.rs
- docs/docs/commands/search.md
It would make more sense to have an "atuin delete" or something for blowing away the whole lot. But, users will logically conclude that passing --delete with no query should delete the lot. So this puts a much more explicit switch to do what they want in the same place.
> Avoid accidentally deleting all history, but allow it if intended

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/api_client.rs
- atuin-client/src/encryption.rs
- atuin-server/Cargo.toml
- atuin-server/src/handlers/user.rs
- atuin/src/command/client/sync.rs
- atuin/src/command/client/sync/login.rs
I have tested to make sure that old hashed/encrypted blobs still work under the new libraries. All the tests pass but I want to be extra thorough so let's hold for now...
We originally intended to use https://github.com/RustCrypto/nacl-compat/tree/master/crypto_box for the secretbox replacement, but the have their own keygen on top (they use a public+private key pair to generate nonce and to generate a symmetric key. We already have the symmetric key so that abstraction on top does not work). The underlying impl is the one we are using here. nacl-compat has been audited, which would imply that `xsalsa20poly1305` also has been audited successfully.
`argon2` crate is maintained by the same `RustCrypto` group. This has no claim to be audited. I will review the code myself, but it has quite a …
> chore: uuhhhhhh crypto lol

- Cargo.toml
The package name was removed when `cargo.toml` was refactored to use `workspace.package`. This breaks the binary builds in actions, which depend on this key to generate a package name.
Re-add package name under `workspace.package`
> Re-added package name to workspace.package

- atuin/Cargo.toml
- atuin/README.md
Neither cargo-deb nor Cargo seem to like relative README paths to a parent dir. Using a symlink _does_ work
See https://github.com/kornelski/cargo-deb/pull/62, https://github.com/rust-lang/cargo/issues/5911
> Add symlink

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/history.rs
Minor feature, steal/copy history_filter and apply it to cwd.
> cwd_filter: much like history_filter, only it applies to cwd

- README.md
- docs/docs/index.md
- docs/zh-CN/README.md
Cloning does not automatically cd to the new directory, and we need to cd to "atuin" *inside* the cloned repository.
(Thanks to @YummyOreo for [pointing this out](https://github.com/ellie/atuin/issues/934#issuecomment-1535565743))
> docs: fix "From source" `cd` command

- docs/docs/commands/search.md
- docs/docs/config/key-binding.md
This commit fixes the spelling of "variables" in a couple of places.
> Correct typos in website

- atuin-client/src/import/bash.rs
- atuin-server/src/handlers/history.rs
#845 introduced a regression where we could loop forever when trying to sync bash history
This is because the server uses the postgres-native timestamp type, which only supports up-to microsecond precision. Incrementing by nanoseconds here meant that to the query, all history had the same timestamp. no bueno!
Use millis instead. They're likely to be safer for all future data processing, and are still faster than a human can spam a button,
> At least patch this on the server side so we don't loop forever

- atuin-client/src/encryption.rs
Keys saved with the old code would load with the new code. Keys saved with the new code would not load with the new code.
The old code didn't save a slice, but the new code does!
This tries both methods of loading, one of which will work. Some people will have been running main already, so it's too late to just break things
I'd still like to ditch msgpack tbh.
> Fix key regression

- atuin-client/src/api_client.rs
- atuin-common/src/api.rs
- atuin-server/src/database.rs
- atuin-server/src/handlers/user.rs
- atuin-server/src/router.rs
- atuin/src/command/client/sync.rs
- atuin/src/command/client/sync/delete.rs
- atuin/src/command/client/sync/unregister.rs
- docs/docs/commands/sync.md
This is implementing an account deletion option, similar to #266. I've made the following changes
* added a `remove_user` function to the database that deletes the user from `users`, `sessions`, and `history`
* added an API endpoint: currently this is the DELETE handler for the `/register` endpoint but could be moved. If this gets called by a logged in user, the account gets delete
* added the `unregister` command to the CLI
```shell
$ atuin unregister
```
I'm wondering how we should prevent accidental account deletion. We could ask the user provide their password, email, or username
```shell
$ atuin unregister -e user@example.com
```
Any suggestions? 
PS: Thanks for looking into this and thanks for building this, it's a really cool tool :blush:
> feat: add delete account option (attempt 2)

- atuin-client/src/settings.rs
- atuin/src/command/client/search/history_list.rs
- atuin/src/command/client/search/interactive.rs
After merging this, I'm working on configurable UI before v15
The idea there is that we can control much more than just compact etc, and toggle each part of the UI to preference. Including where the input bar is
Thanks @pdecat for most of the work here! Based this off of #808 
This does feel kinda weird with the up arrow binding
> Input bar at the top if we are in inline mode

- atuin-client/config.toml
Typo in config key `filter_mode_shell_up_key_binding` that's fixed by this commit, and while at it fix a minor typo in a comment.
Thanks for this project, I use it daily.
> Fix typo in `config.toml`

- docs/docs/self-hosting/docker.md
My Docker gave:
```
docker: Error response from daemon: create USER/.config/atuin: "USER/.config/atuin" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
```
-- so decided to make the path absolute. Can't hurt?
> Make volume path absolute

- atuin-server/src/lib.rs
Closes #676
This is my first significant exposure to Rust in general, especially async. I had to learn a lot of background for these few lines of code lol
Anyways, I tested it with a local docker-compose.yml and it seems to be working
(working =  it does not wait anymore for the timeout and SIGKILL, but it shuts down seemingly immediately with a corresponding message and exit code 0).
Further tests are welcome!
> Add graceful shutdown on SIGTERM

- README.md
The [community] repository no longer exists and has been subsumed into [extra], hence updating links accordingly.
> Update Arch Linux links in README

- docs/docs/commands/shell-completions.md
The "supported shells" link [here](https://atuin.sh/docs/commands/shell-completions) pointed to `README.md` instead of [`index.md`](https://github.com/ellie/atuin/blob/main/docs/docs/index.md)
> fix: Adjust broken link to supported shells

- atuin/src/command/client/search/interactive.rs
I noticed that when setting the new `invert` option several of the movement keys were upside-down. I've updated the keys to do the right thing depending on what the option is set to. I've also extracted the scrolling code into separate functions since the same few lines already had several copies.
> Fix movement keys in inverted mode

- atuin/src/command/client/search/interactive.rs
With this change Ctrl-d behaves differently depending on whether there is any input text available. If there is, it will delete the character to the right of the cursor if there is any. If there isn't it will instead quit interactive mode and leave the original shell command line unchanged.
This matches other line-based tools like bash and fzf.
> Make Ctrl-d behaviour match other tools

- atuin-client/src/api_client.rs
- atuin-client/src/database.rs
- atuin-client/src/history.rs
This PR allows you to set `ATUIN_HOST_NAME` and `ATUIN_HOST_USER` as a means of overriding the default values from the system calls. I found that controlling the hostname and user when using devcontainers in a container was extremely tedious and this will help a great deal in controlling how things are persisted in atuin.
I chose the names  `ATUIN_HOST_NAME` and `ATUIN_HOST_USER` to try to avoid confusion with a user's atuin username, but if anyone has any recommendations I'd be more than happy to change them.
> Add support to override hostname and username via env vars

- docs/docs/self-hosting/self-hosting.md
Small docs fix to make requirement of PostgreSQL 14 explicit in documentation. The docker and k8s examples already refer to PostgreSQL 14 images, and thus do not need fixing.
> Make requirement of PostgreSQL 14 explicit

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/record-migrations/20230531212437_create-records.sql
- atuin-client/src/database.rs
- atuin-client/src/kv.rs
- atuin-client/src/lib.rs
- atuin-client/src/record/mod.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- atuin-client/src/settings.rs
- atuin-common/Cargo.toml
- atuin-common/src/lib.rs
- atuin-common/src/record.rs
- atuin/src/command/client.rs
- atuin/src/command/client/kv.rs
Super basic PoC, that adds a few things
1. Introduce the concept of a records, and a record store
This stores a linked list of... data. Actually just anything! This data could be shell history, but for now is simple key-values. The idea here is to store it locally in a format that works much better for effective syncing. Note that we store it per host. This is intentional, as when sync works the idea is that machines will write their own local data, but read from all
2. Introduce key value store
This is both a cool feature that we wanted, but also a demo of the sync. Rather than mess with history sync from day 0, we can do it with something lower stakes. 
This is not final. I still need to implement sync, and I still need to "build" the history records into an actual kv store. The idea of …
> Key values

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
- atuin-client/src/encryption.rs
- atuin-client/src/history.rs
- atuin-client/src/history/builder.rs
- atuin-client/src/import/bash.rs
- atuin-client/src/import/fish.rs
- atuin-client/src/import/nu.rs
- atuin-client/src/import/nu_histdb.rs
- atuin-client/src/import/resh.rs
- atuin-client/src/import/zsh.rs
- atuin-client/src/import/zsh_histdb.rs
- atuin-client/src/message.rs
- atuin-server-database/src/models.rs
- atuin/src/command/client/history.rs
Also part of #882
Allow History to be created through typed builder interface, powered by [`typed-builder`](https://github.com/idanarye/rust-typed-builder) crate.
This allows to specify different required fields for a different scenarios:
1) entry, imported from shell history should have at least `command` and `timestamp` and _may_ have some other fields specified, if shell history stores them
2) entry, caught by hook – has `timestamp`, `command` and `cwd`. These are only fields accessible at hook's `start` phase, all the other ones (`duration`, `exit` and such) are added after command is executed, on an instance, queried from DB by id.
3) entry, queried from DB. In this case all fields are required, as we're querying the whole object as stored from DB.
I've also added documentation for …
> Builder interface for History objects

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/kv.rs
Messagepack is a nice serialisation format, but rmp-serde is not. serde is designed for self describing documents. Messagepack is not self describing, which makes it prone to breakages.
Common breakages include:
* reordering fields
* adding fields
* removing fields
By writing the encoding out explicitly, we can see clearer when the encode/decode change will cause a breakage. The record version is used to allow different encodings.
> remove rmp-serde

- atuin-client/src/api_client.rs
- atuin-client/src/encryption.rs
- atuin-client/src/sync.rs
- atuin/src/command/client/account/delete.rs
- atuin/src/command/client/sync/status.rs
I've tried making this change 2 times, but it was always part of a bigger PR that never got merged. Doing it separately now 👌
> remove decryption from api-client

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/record-migrations/20230619235421_add_content_encrytion_key.sql
- atuin-client/src/kv.rs
- atuin-client/src/record/encryption.rs
- atuin-client/src/record/mod.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- atuin-common/Cargo.toml
- atuin-common/src/record.rs
- atuin/src/command/client/kv.rs
- atuin/src/command/client/sync.rs
Using a combination of V4 PASETO/PASERK with randomized wrapped keys to encrypt the data of each record.
I've used a set of `DecryptedData`/`EncryptedData` types to ensure that we don't mistakenly write decrypted data to the database
TODO:
> record encryption

- docs/docs/key-binding.md
I don't think `set-env` exists 🤔 
```
❯ : set-env ATUIN_NOBIND = true
Error: nu::shell::external_command
× External command failed
╭─[entry #6:1:1]
1 │ set-env ATUIN_NOBIND = true
· ───┬───
·    ╰── did you mean 'let-env'?
╰────
help: No such file or directory (os error 2)
```
> Fix `nu` section in `key-bindings.md` - `set-env` -> `let-env`

- atuin/src/command/init.rs
- atuin/src/shell/atuin.nu
- docs/docs/key-binding.md
Greetings!
The Nushell team is working on removing `let-env FOO = ...` and moving code to use `$env.FOO = ...` as it's more honest about what's happening (rather than being scoped like a `let`). This PR should move atuin to use the supported syntax (assuming I didn't miss anything 😅).
> Update Nushell support to use supported $env update syntax

- atuin-client/Cargo.toml
- atuin-client/src/encryption.rs
I should have spotted this when I got rid of rmp-serde, but I missed it. The original `rmp_serde::to_vec(key.as_slice())` code didn't convert to `write_bin`, but rather [`write_array_len`](https://github.com/3Hren/msgpack-rust/blob/f4ad0d0257edfea460eb176cdb7d11ddfe97ba3b/rmp-serde/src/encode.rs#L615) and multiple [`write_uint` calls](https://github.com/3Hren/msgpack-rust/blob/f4ad0d0257edfea460eb176cdb7d11ddfe97ba3b/rmp-serde/src/encode.rs#L522-L537).
Thankfully this hasn't made it into a release yet, and in my testing, the incorrect code just wouldn't parse the key, rather than encrypting anything bogus. No harm done.
I never want to use a hidden encoding scheme ever again.
> fix key encodings again

- atuin-client/config.toml
- Updates outdated mac db_path default
- Adds windows db_path default
- Adds windows, mac, linux defaults for key_path and session_path
- Changes example session_path to be different to example key_path
Closes #1091
> Update config.toml path default comments

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/api_client.rs
- atuin-client/src/database.rs
- atuin-client/src/record/encryption.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- atuin-client/src/record/sync.rs
- atuin-client/src/settings.rs
- atuin-common/Cargo.toml
- atuin-common/src/lib.rs
- atuin-common/src/record.rs
- atuin-server-database/src/lib.rs
- atuin-server-postgres/src/lib.rs
- atuin-server/src/handlers/record.rs
sorry @ellie. i'm sure this will cause conflicts for your local changes 😓 
TL;DR
Creates a RecordId and a HostId type wrapper. Reduces potential for confusion of IDs.
Also: implement the Extend trait for RecordIndex and collect the database results directly into them
> use some fancy types

- atuin-server-postgres/src/lib.rs
Turns out we were not deleting from the count cache table!
> Delete the count cache row when a user is deleted

- atuin.nix
- flake.lock
The recent #1096 broke the Nix CI, this change fixes the nix build by disabling those tests. New tests that also use the postgres server will need to be excluded as well using additional '--skip' options or by keeping them all in the same excluded module. Adding a postgres server to make these pass is _technically_ possible, but probably not worth the maintenance burden for you.
For background, the `nix build` step runs the tests by default in an attempt to verify the correctness of the build. These tests are run in a sandbox with no network access, so it's fairly common that projects with complex test cases just won't work within it very easily.
Alternately we could just disable tests entirely in the nix build by using `doCheck = false;` instead of `checkFlags`. [See docs for …
> Disable server tests in the nix build

- atuin-server/src/router.rs
The fallback route handler `teapot()` responded with `HTTP 418` responses with an invalid response body "`☕`".
This PR fixes this urgent issue by replacing the response body with an actual teapot "`🫖`".
> fix(server): Teapot is a cup of coffee

- atuin-client/src/settings.rs
- atuin/src/command/client/search/interactive.rs
- docs/docs/config/config.md
This allows for more configuration around `show_preview`, specifically in the case where someone has shell commands spanning more than 4 lines in their history and need to differentiate between them with something other than the first few lines.
This change makes the following supporting changes:
- Update the preview renderer to split _lines_ when they go past the preview width, rather than splitting the whole string - this means that the preview is cleanly rendered even in cases where there are newlines
- Update the preview height size calculator to take into account existing newlines
A couple of other notes here:
- I've never written rust before, so very open to being told I've done something iffy here
- I think this strips out empty lines from the preview - I'm not sure the best way to …
> Add support for `max_preview_height` setting

- docs/docs/commands/commands.md
This PR adds the remaining (presently existing) sub-pages with command descriptions to the menu / commands overview list at https://atuin.sh/docs/commands/ 
There's a whole bunch of commands not documented at yet, but this is a start! 
Fixes https://github.com/atuinsh/atuin/issues/1139
> fix(docs): List all presently documented commands

- atuin-client/src/record/encryption.rs
I realised yesterday that PASETO payloads need to be encoded with JSON. If we want to support decrypting on non-rust platforms, we should be spec compliant for PASETO to make it easier.
<https://github.com/paseto-standard/paseto-spec/blob/master/docs/02-Implementation-Guide/01-Payload-Processing.md#payload-processing>
> All PASETO payloads must be a JSON-encoded object represented as a UTF-8 encoded string. The topmost JSON object should be an object, map, or associative array (select appropriate for your language), not a flat array or list.
Unfortunately, `rusty-paseto` doesn't enforce this behaviour, so I only noticed now :(
2 solutions:
1) Hacky (this one)
Just wrap the messagepack blob in base64 and then stuff it in a json object.
2) Might be slightly better
Don't use messagepack at …
> encode paseto payloads as json

- atuin-server-postgres/src/lib.rs
Under some sync circumstances, the record tails were being listed for other users. Beyond the existence of the tail, no data leaked
1. When actually trying to fetch the record, the server responds with a 401
2. Even if the above was not true, the client would not be able to decrypt the data
Tldr is that the index was not permissioned 100% correctly, but now is
> Fix index tail leak

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.zsh
This was initially in place for when we used a different terminal backend. That backend required that the terminal be in a specific mode, or otherwise key modifiers would not be correctly recognized. It was super frustrating.
Since the move to crossterm, we automatically switch to raw mode: https://github.com/atuinsh/atuin/blob/b48de9bd9d89fb9b6a0044a1b251e5b2ff116387/atuin/src/command/client/search/interactive.rs#L528
Should resolve #987, #650, #909, #492, #996
Should also supercede #1149
> Remove terminal mode switching

- README.md
Hello! This was pointing to the wrong (maybe an old?) location.
> Fix keybinding link in README

- install.sh
If we're running Ubuntu on non-amd64 we get an install error.  As there's no ARM package yet we can offer the user the option to install via cargo rather than install something that won't work.
> fix(ubuntu/arm*): detect non amd64 ubuntu and handle

- atuin-client/src/kv.rs
- atuin/src/command/client/kv.rs
1. BREAKING - default namespace is now called "default"
2. Build an in-memory hashmap from the kv store
3. Allow listing
I need to cache the hashmap next, probs with a write-through to avoid constant rebuilds.
Also check if BTreeMap is suitable. Sorted is useful for listing but there's probs a better ds to use.
> Add kv map builder and list function

- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-client/src/database.rs
- atuin-client/src/encryption.rs
- atuin-client/src/kv.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/sync.rs
- atuin-server-postgres/src/lib.rs
- deny.toml
Update a ton of dependencies (sorry)
Includes a new `deny.toml` using [cargo-deny](https://embarkstudios.github.io/cargo-deny/). Configured it to pass locally. I have no major opinions on how it will be used but it's a nice safety check in case new vulnerabilities are published.
Notable changes:
* sqlx 0.6 -> 0.7.
* [xsalsa20poly1305 was renamed to crypto_secretbox](https://rustsec.org/advisories/RUSTSEC-2023-0037.html)
* pinning serde <=1.0.171 (see https://github.com/serde-rs/serde/issues/2538)
The rest: whatever `cargo update` did
> Dependency updates

- atuin-client/src/history.rs
- atuin-client/src/lib.rs
- atuin-client/src/secrets.rs
- atuin-client/src/settings.rs
- atuin/src/command/client/history.rs
- docs/docs/config/config.md
I'd like to extend the regex list here very soon, but start off by automatically filtering out secrets. Do not store them in history!
I've included regex for:
1. AWS key id
2. Github pat (old and new)
3. Slack oauth tokens (bot, user)
4. Slack webhooks
5. Stripe live/test keys
#806 will need rebasing
> Automatically filter out secrets

- Dockerfile
This mitigates #1204 but isn't really a permanent fix.
> Explicitly use buster image for cargo-chef, mitigates #1204

- install.sh
Just a small stylistic cleanup. I was looking inside `install.sh` and spotted this `if` which can be less noisy as a `case`.
> Use `case` for Linux distro choice in `install.sh`

- atuin/src/command/client/history.rs
Adding {exit} to available History List command format options. Although implemented, it was not shown in the Help Screen. 
#1230 
```
atuin history list --help
List all items in history
Usage: atuin history list [OPTIONS]
Options:
-c, --cwd
-s, --session
--human
--cmd-only         Show only the text of the command
-f, --format <FORMAT>  Available variables: {command}, {directory}, {duration}, {user}, {host}, {exit} and {time}. Example: --format "{time} - [{duration}] - {directory}$\t{command}"
-h, --help             Print help
```
```
atuin history list --format '{directory}\t{command}\t{exit}'
/home cargo install --path . --target-dir target	0
/home atuin history list --help	0
```
> docs: document the available format options of History list command

- atuin/src/shell/atuin.fish
This was failing for commands that spanned multiple lines, and contained a backslash.
Thanks to @saulrh for suggesting the fix! I just tested and pushed it.
Resolves #1211
Resolves #1232
> Fix selecting complex fish commands

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/search/interactive.rs
- docs/docs/config/config.md
- docs/docs/key-binding.md
Adding another config option to setup Search Mode on KeyUp invocations.
Fixing #1216
> feat(keyup): Configure SearchMode for KeyUp invocation #1216

- atuin-client/src/api_client.rs
- atuin-client/src/record/sync.rs
- atuin-client/src/settings.rs
- atuin-client/src/sync.rs
- atuin/src/command/client/account/delete.rs
- atuin/src/command/client/sync/status.rs
- atuin/tests/sync.rs
- docs/docs/config/config.md
Resolves #691 
Should have had these a long time ago really 😳
> Add connect timeout and overall timeout

- atuin-client/src/database.rs
- atuin-client/src/history.rs
- atuin-client/src/secrets.rs
- atuin-client/src/sync.rs
- atuin/src/command/client/history.rs
`atuin history end` errors if the ID doesn't exist. This can happen if the user changes their database setting mid-command.
Fix: ignore these errors, and log a warning.
Additional: Removes all potential missing entry database queries and handles the options appropriately
> handle missing entries (fixes #1236)

- atuin-server-database/src/calendar.rs
- atuin-server-database/src/lib.rs
- atuin-server-postgres/src/lib.rs
- atuin-server/src/handlers/history.rs
no idea what this endpoint is for tbh, but I've fixed up the timezone support and simplified the logic
> calendar timezones

- .github/workflows/docker.yaml
This was previously enabled in #616 and then reverted in #730.
The `ghcr.io/atuinsh/atuin:main` docker image doesn't provide an arm variant, making it harder to self-host on arm using docker.
> Re-enable `linux/arm64` platform in CI docker build

- .github/workflows/docker.yaml
Reverts atuinsh/atuin#1276
Sorry, this is taking more than an hour to build. I'll pay for + setup a ARM machine for the next release, but it's pretty untenable as is
> Revert "Re-enable `linux/arm64` platform in CI docker build"

- .github/workflows/rust.yml
My self hosted runner is much faster, but my house was hit by lightning and the internet is down. I'm a few thousand miles away atm so won't be able to sort it for a while.
Tests broken by _nature_.
> Use github runners for unit tests (for now)

- atuin/src/command/client/history.rs
- atuin/src/command/client/search.rs
Adding this enables tools like fzf to handle multiline commands, in the
same way that `find -print0 | fzf --read0` does.
I'm happy to add documentation and changelog entries to this as suits you; just
let me know where to put them.
> Add --print0 to `history list`

- atuin-server/src/router.rs
- implement the GNU Terry Pratchet clacks overhead: http://gnuterrypratchett.com/
> A man is not dead while his name is still spoken

- atuin-client/src/database.rs
- atuin-client/src/sync.rs
- atuin/src/command/client.rs
- atuin/src/command/client/account.rs
- atuin/src/command/client/account/login.rs
- atuin/src/command/client/account/register.rs
- atuin/src/command/client/history.rs
- atuin/src/command/client/import.rs
- atuin/src/command/client/kv.rs
- atuin/src/command/client/search.rs
- atuin/src/command/client/stats.rs
- atuin/src/command/client/sync.rs
- atuin/src/command/server.rs
- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.fish
- atuin/src/shell/atuin.nu
- atuin/src/shell/atuin.zsh
1. `s/RUST_LOG/ATUIN_LOG/` for all shells (cc #642) 
2. unset `ATUIN_HISTORY_ID` for all shells (fixes #1261)
3. Add trace log for the running command
> clear history id

- .github/workflows/rust.yml
Reverts atuinsh/atuin#1279
Brought my runner back online woohoo
> Revert "Use github runners for unit tests (for now)"

- .github/workflows/docker.yaml
I wish the CI dev loop was nicer.
> Checkout repo so the manifest publish step can read git

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin-common/src/utils.rs
- atuin/src/command/client/search/interactive.rs
- atuin/src/command/init.rs
- atuin/src/shell/atuin.zsh
- docs/docs/config/config.md
`enter_accept` will make Atuin immediately accept an execute a command
when selected. It defaults to false in our binary, but the default
config enables it.
This means that users who already use atuin will not default to the new
behaviour unless they opt in, but new users will have it by default.
Thanks to @davidhewitt for the patch and bulk of this implementation!
Currently we have it just for zsh, but I'll follow up with other shells
(unless anyone beats me to it :D)
This also uses "tab" to select and edit a command
> Add enter_accept to immediately execute an accepted command

- atuin-server/src/lib.rs
- atuin/src/command/server.rs
I was sent a message with:
> `host = "mithril"`: `Error: invalid IP address syntax` why's it called host if it wants an IP
This makes the host field support more than just IPs, doing a getaddrinfo lookup if necessary
> allow binding server to hostname

- atuin-common/src/utils.rs
- atuin/src/command/client/search/interactive.rs
- atuin/src/shell/atuin.bash
It's a little less smooth than ZSH or Fish. The actual text to execute isn't entered before being eval-d like on the other shells, and if I try and set it then the command is inserted _after_ it is evaluated. ew.
Maybe explore BLE or similar in the future
> Add bash support to `enter_accept`

- docs/docs/self-hosting/self-hosting.md
For configuring a firewall you need to know if it's TCP or UDP.
> Document that the self-hosted port is TCP

- atuin/src/shell/atuin.nu
Redirects stderr to null in nushell, following instructions at https://www.nushell.sh/book/stdout_stderr_exit_codes.html#stderr
The other shell scripts already redirect stderr for the `atuin history end` call, so this is matching their functionality.
I've tested this locally but I have not written nushell before, so this may not be idiomatic.
Closes #1214
> fix(nushell): Ignore stderr messages

- .github/workflows/rust.yml
Reverts atuinsh/atuin#1295
Should be sorted THIS TIME. I just plugged it in and sorted it out, reconfigured so this shouldn't happen again.
> Revert "Revert "Revert "Use github runners for unit tests (for now)"""

- atuin-client/src/database.rs
- atuin/src/command/client/sync/status.rs
Introduced in #1272 
`history_count(false)` would result in counting _just_ the history that has been deleted. When it should be all history that has **not** been deleted.
I've also updated the status command so it's a bit clearer what is going on
> Fix deleted history count

- atuin/src/command/init.rs
- docs/docs/key-binding.md
The up-arrow keybinding triggers anytime the key is pressed, including in menus or multi-line commands. Disabling it by default for new users. See #1025 for additional context.
This leaves the binding in the init script but commented out, so users can enable it easily if needed.
> fix(nu): disable the up-arrow keybinding for Nushell

- .github/workflows/release.yaml
v2.0.0 of cargo deb added the revision number. I'd rather not change the output name of our file, so force cargo-deb to stick to the "old" behaviour
> Fix cargo deb usage

- atuin/src/shell/atuin.fish
Oops. `string match` is a bit too noisy, make it quiet. Also print the match before executing it.
Resolve #1335
> Silence fish string match

- atuin-client/config.toml
The "invert" setting was initially added to the default config in #1226 and the duplicate was introduced in #1241.
> Remove duplicate "invert" in default config

- atuin/src/shell/atuin.fish
Fixes 2 issues with the fish shell prompt when using `enter_accept`
1. Runs pre/post exec so the command is added to the atuin history.
2. Adds padding so that the repainting of the shell prompt doesn't overwrite the output.
This adds 2 lines of padding to account for prompts up to 2 lines tall, larger prompts will still cause repainting problems and smaller prompts will be getting an extra line. I don't think there's a way to know how tall the prompt is.
I haven't looked at whether zsh/bash have similar problems.
> fix(fish): improve output for `enter_accept`

- atuin/src/shell/atuin.bash
Very similar change to #1341, but for bash.
Bash's behavior here is worse than fish, as it only redraws the prompt line that has input (why we only need to add 1 additional line after the eval). It also does not show the prompt line at all on an echo. There's not really a way to get this to look normal AFAICT, aside from trying to redraw everything ourselves.
As an example, this is what running `ls`, `echo here`, then selecting `echo here` from the atuin menu will look like:
1 line prompt:
``` bash
$ ls
code downloads
$ echo here
here
echo here
here
$ cursor
```
2 line prompt:
``` bash
~promptfirstline/
$ ls
code downloads
~promptfirstline/
$ echo here
here
~promptfirstline/
echo here
here
$ cursor
```
> fix(bash): improve output of `enter_accept`

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.fish
Followup for #1341 and #1342. This clears the prompt of any command snippet the user entered before opening the atuin history search.
Both prompts still have issues with how the fake command looks after we've run it. Bash overwrite the whole prompt line with the command (See #1342), and I wasn't able to figure out how to clear the pre-existing cmd snippet from fish.
For the fish problem, as an example if you type `ech`, then hit ctrl+r and select `echo here` it will appear like this:
```
$ echecho here
here
$ 
```
I'm not sure how solid these fixes actually are, both shell's will cause a bit of confusion for users but I think it's the best we can do at the moment :shrug:
> fix(enter_accept): clear old cmd snippet

- atuin-client/src/database.rs
The initial list didn't correctly show all history while in workspace mode, while it worked totally as expected while searching. Fix this.
> fix: initial list of history in workspace mode

- flake.nix
This adds a [Nix overlay](https://nixos.wiki/wiki/Overlays) for the Atuin flake.
This makes it easier for a consumer to directly use the repo instead of the packaged version in nixpkgs, and it is fairly standard for this setup. The simple explanation is it lets you overlay the git version of Atuin on top of the standard list of packages.
> feat(nix): Add a nixpkgs overlay

- atuin.nix
- flake.nix
Atuin v17 relies on Appkit to build on Mac. This was pointed out in discord and found in the [Nixpkgs PR](https://github.com/NixOS/nixpkgs/pull/263530)
> fix(nix): Add Appkit to the package build

- atuin/src/command/init.rs
Improves the zsh keybindings so that we bind to the most common modes in ZSH.
Without this change we are only binding in the default keymap, and zsh's builtin history search would trigger in the others.
This also binds to 'k' in the vicmd map, since 'k' is the up key in that mode (and already bound to zsh's builtin `up-line-or-search` command).
> fix(zsh): bind in the most popular modes

- atuin/src/shell/atuin.zsh
Fixes #1351
This adds a check so that the up-arrow keybinding only triggers if it is on the first line of a buffer. This fixes the case where we are moving in a multiline command.
Alternatively: ZSH's builtin command for this, `up-line-or-search`, disables history entirely when the command is multiple lines. We could simply match that behavior instead.
> fix(zsh): Only trigger up-arrow on first line

- atuin/src/shell/atuin.fish
Closes #1368 
I reviewed and updated the options we use in the fish script, fixing several issues:
1. Removing the `--groups` option as reported in #1368, it's not needed if we're only testing whether the match exists.
2. Setting the correct scoping for variables. Setting all local variables to be local, `-l`, and removing the `-x` (export) setting for ATUIN_HISTORY_ID as it's unnecessary. The non-local variables (`s`, `h`, `hist`) were clobbering any user-defined variables with the same name.
3. Renaming `h` and `hist` to have an `ATUIN_` prefix, as those variables are accessible from user-defined code. Without this, using `enter_accept` with the history item `echo $h` would have given the user the script value of `$h` instead of their own.
> fix(fish): clean up the fish script options

- atuin/src/shell/atuin.fish
After checking again, I found fish's equivalent of zsh's `zle accept-line`. This change correctly handles the execute without resorting to any creative workarounds.
Note that the `repaint` in the middle here is needed, otherwise the prompt that contains the accepted command won't redraw.
> fix(fish): use fish builtins for `enter_accept`

- README.md
- atuin/src/shell/atuin.bash
- docs/docs/advanced-install.md
This is a fairly large rewrite of the bash integration using `enter_accept`. This improves the feature in bash, redrawing the prompt correctly, running the preexec/precmd functions, and adding the command to the bash history.
**Note that this does not fix #1372, which is not fixable in bash.** It would only be fixable if we can find an equivalent of `zle accept-line` in ble.sh. I worked on this change hoping that I would be able to find a fix but I was unable to find one.
Despite putting in a bit of effort to clean this up, I think we should remove the `enter_accept` feature on bash, or at least disable it by default, until we can find a solution to #1372. It is very surprising behavior and will confuse anyone using this in bash. @ellie?
I did identify a separate issue with bash-preexec …
> Bash `enter_accept` best effort fixes

- atuin/src/command/client/search/interactive.rs
- atuin/src/shell/atuin.bash
Ref #1384, #1372
It doesn't look like we will be able to get this to a point where it works well on bash. If this happens, we can enable it again
> Disable enter-accept for bash

- atuin/src/command/client/account/delete.rs
When I deleted my Atuin.sh account, I found the command did not delete the key or session files.
This caused `bail!`s from Atuin when querying the session status, or synchronising.
Of course, one shouldn't expect Atuin to be able to synchronise or query with the server when the account is deleted, but the relevant files were still present, so the behaviour was different to what we'd expect.
I discussed this with @ellie on Discord, and we came to the conclusion that I should open a PR, and submit a patch.
I'm not sure how well this PR fits in with the borrow checker, but I've run tests, a Nix build, and a Cargo build - all goes well. I have not tested on macOS or Windows; only NixOS.
> Make `atuin account delete` void session + key

- Cargo.lock
- atuin-server/Cargo.toml
- atuin-server/server.toml
- atuin-server/src/lib.rs
- atuin-server/src/metrics.rs
- atuin-server/src/router.rs
- atuin-server/src/settings.rs
- atuin/src/command/server.rs
- atuin/tests/sync.rs
I've setup a metrics server that serves prometheus metrics, when enabled. It runs on a totally separate server, to make it easier to not serve up public metrics.
I'll follow up with some more metrics, but the base http ones are pretty useful as-is. I won't need to scrape them from the reverse proxy any more
> feat: add metrics server and http metrics

- docs/docs/advanced-install.md
> Update Arch Linux package URL in advanced-install.md

- atuin/src/shell/atuin.fish
Closes #1404
This fixes the multiline handling in fish, and as a side effect it also removes the dependency on awk. We need to directly capture the command substitution into a string to preserve the newlines instead of setting it to a variable directly.
> fix(fish): accept multiline commands

- atuin/src/command/client/search/interactive.rs
- atuin/src/shell/atuin.bash
I was looking through old issues, and found this: https://github.com/atuinsh/atuin/issues/78#issuecomment-1555949322. It appears that @yannickulrich may have already implemented a fix for our bash `enter_accept` input issue back in their initial suggestion. 
It does work for me for some of the previously broken commands. `ssh` works fine, as does `read -p "Say something?" tosay; echo "Say: $tosay"`. I do not know if there are limitations.
I have intentionally made this a draft PR because I think it should be tested a bit more first (and there's probably some doc updates that need to happen). I don't know what issues there might be and we should probably test this out a bit before we re-enable it for everyone. We don't want to be causing further confusion if we can help it.
List of the …
> fix: reenable enter_accept for bash

- CHANGELOG.md
- CONTRIBUTORS
- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-server-database/Cargo.toml
- atuin-server-postgres/Cargo.toml
- atuin-server/Cargo.toml
- atuin/Cargo.toml
There's been a few fixes and features, so about time for release!
In the new year I shall introduce a more regular release cadence
> chore(release): prepare for release v17.1.0

- atuin-client/src/settings.rs
Before this change, when configuring only `common_subcommands` and not `common_prefix` (so it would take its default value), atuin produces an error message:
```
Error: could not load client settings  Caused by:     failed to deserialize: missing field `common_prefix`  Location:     atuin-client/src/settings.rs:456:26
Error: could not load client settings
Caused by:
failed to deserialize: missing field `common_prefix`
Location:
atuin-client/src/settings.rs:456:26
Error:: command not found
```
With this change, the fields can be specified separately and missing fields will take their default values.
> fix: don't require all fields under [stats]

- atuin/src/command/client/search.rs
Thanks for writing and supporting atuin!
I ran into a bug where if you combine the --limit and --deletion flags it would delete all of the matching entries instead of some limited number. For example:
```
user@nixos:~/ > cat asdf.txt 
user@nixos:~/ > qwerty1
qwerty1: command not found
user@nixos:~/ > qwerty2
qwerty2: command not found
user@nixos:~/ > qwerty3
qwerty3: command not found
user@nixos:~/ > atuin search qwerty
2023-12-10 19:08:42     qwerty1 39ms
2023-12-10 19:08:47     qwerty2 37ms
2023-12-10 19:08:52     qwerty3 37ms
2023-12-10 19:09:10     atuin search qwerty     0s
user@nixos:~/ > atuin search --delete qwerty --limit 1
deleting 018c5522b1447c778a2261d68cdfc6d4
deleting 018c552226ef71fc8a0efe9a9c376f6c
deleting 018c5521ddec717cbcac7581a229b6c6
deleting …
```
> Dissallow deletion if the '--limit' flag is present

- Cargo.lock
- Cargo.toml
- atuin/Cargo.toml
Went through a bunch of deps and updated them where possible. None of the breaking releases have any consequences for us as far as I could tell.
I also wanted to update axum to 0.7, but https://github.com/tokio-rs/axum/blob/main/examples/graceful-shutdown/src/main.rs looks like far too much code for graceful shutdown handling. I will revisit it again once they introduce a proper graceful shutdown API https://github.com/tokio-rs/axum/issues/2419
> chore(deps): update basically everything

- Cargo.lock
- Cargo.toml
- atuin-common/src/utils.rs
I happened to notice that uuid crate now has the v7 API stable
> uuidv7 stable

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/api_client.rs
- atuin-common/Cargo.toml
- atuin-common/src/api.rs
- atuin-server/src/router.rs
This ensured that the client cannot try and sync while running a greater major version than the server
So far, servers have been backwards compatible with _all_ clients. Clients have not been forwards compatible with all servers. The former is much easier to achieve than the latter.
Instead of clients reporting weird errors when servers don't respond as they should, ensure that servers are kept up to date.
> feat: add semver checking to client requests

- Cargo.lock
- atuin-server/Cargo.toml
- atuin-server/server.toml
- atuin-server/src/lib.rs
- atuin-server/src/settings.rs
- atuin/src/command/server.rs
- atuin/tests/sync.rs
- docs/docs/self-hosting/self-hosting.md
atuin as a project already includes most of the dependencies necessary for server-side TLS.  This allows `atuin server start` to use a TLS certificate when self-hosting in order to avoid the complication of wrapping it in a TLS-aware proxy server.
Configuration is handled similar to the metrics server with its own struct and currently accepts only the private key and certificate file paths:
```toml
[tls]
enable = true
cert_path = "/path/to/letsencrypt/live/FQDN/fullchain.pem"
pkey_path = "/path/to/letsencrypt/live/FQDN/privkey.pem"
```
Starting a TLS server and a TCP server are divergent because the tests need to bind to an arbitrary port to avoid collisions across tests.  The API to accomplish this for a TLS server is much more verbose.
> Add TLS to atuin-server

- atuin/src/shell/atuin.bash
With a single-line prompt, the last line of the output of the previous command is overwritten by the prompt rendered by `enter_accept` in Bash. I confirmed this behavior in all the terminals I tried, including xterm, lxterminal, terminology, terminator, mlterm, screen.
With the single-line prompt, `tput cuu` receives 0 as the parameter, but `tput cuu 0` emits the control sequence `\e[0A`, which *moves the cursor above by one line* unexpectedly.  This is because the parameter 0 for CUU means *the default value*, 1.
In this PR, to avoid moving the cursor when the prompt offset is 0, we check the offset value before running `tput cuu`.
> fix(bash): fix loss of the last output line with enter_accept

- atuin/src/command/client/search.rs
- atuin/src/command/client/search/interactive.rs
In these cases, I think that's a _little_ too pedantic.
> fix(clippy): ignore struct_field_names

- README.md
- atuin/src/shell/atuin.bash
There are three commits: 1) the check for the ble.sh version, 2) the ble.sh's adapter to the bash-preexec interface, and 3) the `accept-line` widget to run the accepted command. A detailed description can be found in each commit message.
> fix(bash): improve the support for `enter_accept` with `ble.sh`

- atuin/src/shell/atuin.bash
This PR resolves small issues of `enter_accept` for Bash without ble.sh. There are five different fixes, and again the details are in the commit messages. The original author @arcuru might have comments.
I plan to submit another PR for refactoring and a small performance improvement (which contains again 5 commits). If I should separate the PR into smaller chunks, please let me know. In such a case, I can re-submit those commits in separate PRs.
> fix(bash): fix small issues of `enter_accept` for the plain Bash

- atuin/src/shell/atuin.bash
This is the PR mentioned in #1467. We isolate the codes to emulate `accept-line` into a new shell function `__atuin_accept_line`.
> refactor(bash): factorize `__atuin_accept_line`

- atuin-client/src/settings.rs
- atuin/src/command/client/stats.rs
On many platforms, getting local timezone requires a call to get_env which is not thread safe. This means it conservatively doesn't work if a thread has been spawned (I believe sqlite is using a separate thread here).
Attempt to fix by acquiring the local tz as early as possible.
> fix(stats): time now_local not working on Linux

- docs/docs/integrations.md
I've added an integrations page to the docs. We can maintain a list of such integrations
> docs: add docs for zsh-autosuggestion integration

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.zsh
This PR contains two fixes related to the cancellation of the atuin search in the command line. One is for Bash, and the other is for Zsh.
I've noticed a quirk, which is specific to the Bash integration.
In the current implementation for Bash, the line content is lost when the user cancels the atuin search by pressing <kbd>ESC</kbd>, <kbd>C-g</kbd>, or <kbd>down</kbd> at the bottom line.  This is because the line content is set to the empty string returned by atuin on the cancellation of the search.
In the integrations for other shells, zsh and fish, the empty output is properly handled so that the line content is preserved:
https://github.com/atuinsh/atuin/blob/5bef19ba4cca71f90094f9d7c3c7d25a6d8af8a3/atuin/src/shell/atuin.zsh#L48-L50 …
> fix(bash,zsh): fix quirks on search cancel

- atuin/src/command/client/history.rs
- atuin/src/command/client/search/duration.rs
- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.zsh
This is a suggestion for a feature. If this is something you don't want, please don't hesitate to reject the PR.
ble.sh internally measures the command execution time using the builtin features of Bash. In particular, in bash >= 5.0, ble.sh uses `$EPOCHREALTIME` to measure the high-resolution execution time. The measured result is available in the shell variable `$_ble_exec_time_ata` in the `PRECMD` hook. `_ble_exec_time_ata` contains the execution time in the unit of microseconds.
In this patch, I suggest using this information for atuin to measure the command execution time, since the current duration measurement of atuin includes the fork time of atuin itself. Also, I added the units (us and ns) to display short duration in the search view.
In the second commit, I also implement …
> feat(shell): support high-resolution duration if available

- atuin/src/shell/atuin.bash
The parameter expansions for the prompt strings, `${PS1@P}`, is only available in bash >= 4.4.  In bash <= 4.3 with bash-preexec, the current implementation produces error messages.  There is no way to evaluate PS1 with bash < 4.4, so we give up the adjustments for multiline prompts in bash < 4.4 in this patch.
> fix(bash): fix error by the use of `${PS1@P}` in bash < 4.4

- atuin-client/src/import/zsh.rs
unescape those correctly rather than throw them away.
zsh side code:
https://github.com/zsh-users/zsh/blob/9f57ca4ac8ae071727b1d77cbb8c4c0d893b9099/Src/utils.c#L4889-L4900
I've finally found out what is missing in my atuin's view of history.
> fix(import/zsh): zsh use a special format to escape some characters

- atuin-server/src/settings.rs
Without TLS config, the server fails to load defaults. Until this is released, add this to your server config
```
[tls]
enable = false
cert_path = ""
pkey_path = ""
```
> fix(server): typo with default config

- atuin/src/command/client/search/interactive.rs
> refactor: use enum instead of magic numbers

- atuin/src/shell/atuin.bash
This fixes the second issue reported at https://github.com/atuinsh/atuin/issues/1003 by @gvlassis, i.e., the issue of "0s or wrong command duration".
The problem is that, with bash-preexec, the preexec hook may be called even for the commands executed by the keybindings.
* In particular, the preexec is called before the command `__atuin_history` is executed on pressing <kbd>C-r</kbd> and <kbd>up</kbd>.  In this case, `$1` passed to `__atuin_preexec` contains the last entry in the command history, so `atuin history start` is called for the last command.  As a result, pressing <kbd>C-r</kbd> and <kbd>up</kbd> clears the duration of the last command.  This causes the reported 0s duration.
* Furthermore, the precmd hook corresponding to the keybinding command will not be called, so the …
> fix(bash): avoid unexpected `atuin history start` for keybindings

- atuin/src/shell/atuin.bash
This applies the change for zsh-autosuggestions in https://github.com/atuinsh/atuin/pull/1506 to the code for blesh auto-complete.
> fix(bash): prevent input to be interpreted as options for blesh auto-complete

- atuin/src/shell/atuin.bash
When the user sets a custom value of `IFS`, the up keybinding may fail because the option `--shell-up-key-binding` passed to `__atuin_history` is broken by the word splitting of the shell.  For example, when the user sets `IFS=-`, `atuin` called from `__atuin_history` receives `shell up key binding <content>` as the search string.
```bash
$ IFS=-
$ echo [up] # <-- this does not work as expected
```
Note that the problem only happens with the plain Bash without ble.sh. The problem does not arise within ble.sh because ble.sh separates the user environment and the line-editor environment by saving/restoring the shell settings.  The keybindings are processed in the line-editor environment in ble.sh, so the custom `IFS` set by the user does not affect it.
In this patch, we properly quote the …
> fix(bash): work around custom IFS

- atuin/src/command/init.rs
- atuin/src/shell/atuin.bash
This PR includes three different fixes related to the keybinding to <kbd>up</kbd> in Bash. The descriptions are found in commit messages and in code comments.
> fix(bash): fix and improve the keybinding to `up`

- docker-compose.yml
- docs/docs/self-hosting/docker.md
- docs/docs/self-hosting/k8s.md
- docs/zh-CN/k8s.md
- k8s/atuin.yaml
The docker compose / k8s files all refer to an image without ARM support:
```
➜ docker pull ghcr.io/atuinsh/atuin:main
main: Pulling from atuinsh/atuin
no matching manifest for linux/arm64/v8 in the manifest list entries
```
This change refers to the image with ARM support, to enable usage on Linux arm64 and to improve performance on Apple Silicon machines.
> refer to image with multi-arch support

- atuin-server-postgres/migrations/20240108124837_drop-some-defaults.sql
The columns referred to in this PR, were for some reason created with defaults. When created years ago, they were `bigserial` not `bigint`.
The defaults were never actually used, as verified by
1. Checking the value of the sequences on the database
2. Checking the code
So we're safe to clean them up.
> chore: schema cleanup

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.fish
- atuin/src/shell/atuin.nu
- atuin/src/shell/atuin.zsh
When a child shell session is started from another shell session (let us call this parent session hereafter), the environment variable `ATUIN_HISTORY_ID` set by the *parent* session causes Atuin's precmd hook of the *child* session to be unexpectedly performed before the first call of Atuin's preexec hook.
For example, let us consider the case to run `bash` inside the terminal to start a new session.
```bash
[parent]$ bash
[child]$ echo some-commands
[child]$ exit
```
In this patch, we clear `ATUIN_HISTORY_ID` (possibly set by the parent session) on the startup of the session. The variable `ATUIN_HISTORY_ID` doesn't seem to be an environment variable in the fish integration, but we clear it also in the fish integration for consistency.
With this solution, when the user runs `source …
> fix(shell): fix incorrect timing of child shells

- .github/workflows/release.yaml
It never worked, and broke release building. I don't think we need musl debs, but if so ensure they don't break install scripts
Resolve #1500
> fix: disable musl deb building

- README.md
While Atuin is reliable and performs well under load, the activity graph service failed to scale so well. It was a Python service generating images for requests from a large series of data. For users with small amount of data this was fine, but for users with 100k+ lines of history it didn't respond well.
I'm going to be reworking it soon, but for now I'm taking it down rather than offer a less-than-optimal experience. It should be back soon :)
> docs: remove activity graph docs

- README.md
It is a common practice to use `-f` in Nushell configurations to avoid `Destination file already exists` error.
```nushell
🦄 nu
Error:   × Destination file already exists
╭─[/home/user/.config/nushell/env.nu:20:1]
20 │ starship init nu | save -f ~/.cache/starship/init.nu
21 │ atuin init nu | save ~/.local/share/atuin/init.nu
·                      ──────────────┬─────────────
·                                    ╰── Destination file '/home/user/.local/share/atuin/init.nu' already exists
22 │
╰────
help: you can use -f, --force to force overwriting the destination
```
> docs: fix `Destination file already exists` in Nushell

- atuin/src/shell/atuin.bash
This is just a cosmetic one. I originally planned to submit this after settling all the planned PRs, but some would overlap. I still have two planned PRs, but I'd like to submit this before those two.
Different coding styles and indentations are mixed in the current `atuin.bash`. In this PR, I try to normalize them. I separate the commits for each topic. These are more or less preferences, so if you would like the normalization the other way around, please specify it. I can adjust them (after the confirmation about the consequences if needed).
As usual, I left descriptions in commit messages.
> style(bash): use consistent coding style

- README.md
"backup" is a noun. "back up" is a verb.
I originally wanted to fix the https://atuin.sh/ website, which contains the same style error, but I couldn't find its source.
> Improve style

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.zsh
This is relatively trivial. I do not see the global variable `HISTORY` set by `__atuin_history` being documented. Also, the variable names are different for different shells (e.g. `output` in zsh, and `ATUIN_H` in fish), so this doesn't seem to be a part of the public interface of Atuin's integration. I'd suggest localizing those variables. Note that `ATUIN_H` in fish seems to be already local. I'm not sure how this is processed for the Nu shell integration, but I guess it would be processed without creating a variable.
I also localize `output` set by the Zsh integration. Even if we expose it on purpose, the variable name choice doesn't seem nice to avoid conflicts with the users' variables.
> refactor(bash): refactor and localize `HISTORY => __atuin_output`

- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.zsh
I decided to provide the timing with `EPOCHREALTIME` even without ble.sh. It is not as accurate in the case with ble.sh, but we may still support it in the same way as done in the Zsh integration.
I also would like to add a fix to the previous PR. I haven't carefully thought about the interference with a custom `IFS` possibly set by users. When the user have a custom `IFS`, the constructs `${duration:+--duration "$duration"}` might unexpectedly split by the word splitting. In this patch, we use the form `--duration=$duration` and properly quote it to prevent it from being split.
> feat(bash): support high-resolution timing even without ble.sh

- atuin/src/command/client/search/interactive.rs
Given some of the questions we've had lately, I think it's sensible to add extended help to the top of the Atuin window.
Future plans: Ctrl-<something else> to open up a help popup, with all common keys
It looks like this
> feat: add extended help

- README.md
- atuin/src/shell/atuin.bash
In a typical configuration of `.bashrc`, in an interactive session (where `$-` contains the letter `i`), it returns at the beginning of `~/.bashrc`. However, a different configuration is possible. In such a case, `eval "$(atuin init bash)"` can be called from non-interactive shells, and causes error messages related to the keybindings, i.e., the uses of the `bind` command in non-interactive shells causes warning messages. We can have a check also at the beginning of `atuin.bash`.
The requirement on the Bash version does not seem to be clarified anywhere, so I suggest explicitly specifying it to be bash >= 3.1.  This is the same as that of bash-preexec.
- As far as I tested it in Bash 3.1 and 3.2 with bash-preexec, it doesn't work perfectly, but it still works in not a too bad way with …
> fix(bash): work around bash < 4 and introduce initialization guards

- Cargo.lock
- Cargo.toml
- atuin/Cargo.toml
- atuin/src/command/mod.rs
This ensures no other user can read shell history data
Resolves #1250
> fix(perm): set umask 077

- atuin/src/command/mod.rs
Windows automatically doesn't allow other users to access other's files (unless they are a admin). So a replacement for windows isn't needed.
> fix(windows): disables unix specific stuff for windows

- atuin/src/command/client/search/interactive.rs
In the current `main` branch, I cannot read the selected tab title because the background and foreground colors are the same in terminals with the light background. Here is an example (where the red part is drawn by me):
This patch specifies the foreground color explicitly. After the fix, it looks as follows:
> fix(search): fix invisible tab title in light background

- atuin/Cargo.toml
- atuin/src/command/client/search/interactive.rs
The cli-clipboard crate doesn't compile on systems other than Windows, Linux and MacOS, e.g. on Android it fails to compile.
> chore: make clipboard dep optional as a feature

- atuin/src/command/client/search/interactive.rs
1. Some shells/terminals seem to directly bind ctrl-i to be tab :( Use ctrl-o for the inspector instead
2. Shorten the help text so it doesn't get squished
> fix: shorten text, use ctrl-o for inspector

- atuin/src/command/client/search/interactive.rs
Before submitting the change to the configuration interface of the newly introduced vim mode, I'd like to first refactor/fix the behaviors of corner cases. I left details in the commit messages.
@YummyOreo @ellie Could you check these?
> refactor(search): refactor vim mode

- atuin/src/shell/atuin.fish
- On fish 3.3 the bash-style `$(...)` doesn't work, we should use `(...)`
- Also quoting `"(moo)"` on older fishes gives a literal `moo`
- The result of a `(subcommand)` is a single token, so no need to quote it, anyway
Tested by making the change, executing `cargo run -- init fish > atuin.fish` and then copying and source that script on a system with fish 3.3, as well as 3.6 and observing both still work.
Fixes #1562.
> Fix fish integration on older fishes

- atuin-client/src/sync.rs
Imagine the scenario where a sync fails. The function touched here will never save the sync time.
That means that external to this function, the sync never happened. The next command will try and start one immediately.
The happy scenario is that this succeeds. The unhappy scenario is that this fails. Fails, and isn't saved, so we try again...
Should add proper backoff but this is a good start.
> fix(sync): save sync time when it starts, not ends

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/search.rs
- atuin/src/command/client/search/interactive.rs
- atuin/src/command/init.rs
- atuin/src/shell/atuin.bash
- atuin/src/shell/atuin.fish
- atuin/src/shell/atuin.zsh
This is a possible refinement to the vim mode as suggested in https://github.com/atuinsh/atuin/pull/1553#issuecomment-1890426150.
In this PR, we introduce three keymap modes, `emacs`, `vim-insert`, and `vim-normal` (which was extended from the current `VimMode`). When the config `vim` is enabled, the keys are processed with special rules for the current keymap mode. This is actually the same as the current `main`. The real behavioral change is related to the following config `keymap_mode`:
The keymap mode with which the Atuin search is started is controlled by the config `keymap_mode`. When `keymap_mode` is not specified, the keymap mode on the startup is determined based on the shell's keymap that started the Atuin search. When the config `keymap_mode` is specified, the keymap mode on …
> feat(search): introduce keymap-dependent vim-mode

- atuin-common/src/utils.rs
- atuin/src/command/client/history.rs
- atuin/src/command/client/search.rs
- atuin/src/command/client/search/history_list.rs
- atuin/src/command/client/stats.rs
Detail of change is in the commit message but easiest steps to reproduce is to open a new terminal and run the following
```sh
echo one
echo '^[[31mtwo' # with `^[` entered as literal using ctrl-v + ctrl-[
echo three
atuin history list -s
```
With the previous behaviour, the control sequence would not be visible (and therefore not copyable) and everything after the second 'echo' would be red.
Running `atuin search -i --filter-mode session` afterwards would display the `echo two` command as `echo '[31mtwo'`. Selecting it would print `echo 'two'` without the control sequence and two onwards in red.
> Stop control characters being printed to terminal

- atuin-server/src/handlers/v0/record.rs
We have uploaded, so this follows. Now that it's (in `main`) used for sync, I'd like to monitor properly while testing
To watch for: reasonably similar upload/download when used across machines, rather than the higher values we saw for the old sync
> feat: add metrics counter for records downloaded

- atuin-common/src/utils.rs
Instead of using their equivalent hex codes.
> Escape control characters using caret notation

- atuin/src/command/client/search.rs
Previous 'fix' to prevent control sequences being interpreted when they
shouldn't have been also prevented them being used when they should have
been. This checks if the output is to a terminal (where control
sequences shouldn't be interpreted) before escaping control characters.
> Print literal control characters to non terminals

- atuin/src/command/client/search/interactive.rs
This was missed in the initial change to escape control characters.
> Escape control characters in command preview

- atuin-client/config.toml
- atuin-client/src/database.rs
- atuin-client/src/kv.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/sync.rs
- atuin-client/src/settings.rs
- atuin/src/command/client.rs
This should fix #1503
I wasn't able to trigger enough IO pressure for the SQL connection to be a problem.
This adds `local_timeout` to the client config. This is a float, and represents the number of seconds (units in line with the other timeouts, though those are ints). Users may well want to reduce this if they regularly have issues, but by default I think 2s is fine and avoids a non-responsive system in bad situations.
> fix: add acquire timeout to sqlite database connection

- atuin/src/command/client/search/interactive.rs
Kitty terminal was sending `shift-a` as `shift` + `a` and not `A`, and we have no special handling of shift, so atuin was only acknowledging lowercase `a`.
https://sw.kovidgoyal.net/kitty/keyboard-protocol/#report-alternate-keys fixes it for me, although I don't know if this has any other side-effects
> fix: report alternate keys so shift still works

- atuin/src/command/client/search/interactive.rs
References:
- https://github.com/atuinsh/atuin/pull/1553#pullrequestreview-1819957698
- https://github.com/atuinsh/atuin/pull/1570#discussion_r1453397004
- https://github.com/atuinsh/atuin/pull/1595#issuecomment-1903775396
> refactor(search): refactor handling of key inputs

- atuin-client/src/history/store.rs
- atuin/src/command/client/history.rs
Make the history store init idempotent
This ensures the user cannot import the same data from the database multiple times
Useful for the case where the user toggles the record store sync on/off, and to ensure accidents don't lead to store bloat.
> feat: make store init idempotent

- atuin-client/src/database.rs
Related: https://forum.atuin.sh/t/search-ignoring-commands/74/5?u=ellie
When a user ran a duplicated command, but in another session, it was removed by filters. This is because the subquery that was once used did not have the same filters applied as the main query.
Instead of messing with subqueries, `group by` instead. This aligns with the search() function
> fix(history): dedupe was removing history

- atuin/src/command/client/history.rs
The latest in the control characters saga. I opted for the nested enum option as
it made accessing the history fields easier in the FormatKey implementation.
> fix: Only escape control characters when writing to terminal

- atuin/src/shell/atuin.bash
Fixes https://github.com/atuinsh/atuin/issues/1617
This contains an extra commit dc2afa7, which counts the newlines in the prompt result using Bash's built-in features. The previous implementations used the external command `wc` with the command substitution, which involves 3 forks and 1 exec so is slow. We can count newlines by first removing all the characters except for the newlines and then counting the number of remaining characters.
> fix(bash): strip control chars generated by `\[\]` in PS1 with bash-preexec

- atuin/src/command/client/history.rs
Improve the errors reported when a format string is not valid, eg
atuin search cargo --format '{invalid}'
gives
history output failed with: The requested key "invalid" is unknown
instead of
history output failed with: formatter error
Was the runtime-format library forked/written for use in atuin - it looks like
the timelines match? How feasible would it be either vendor the parts atuin
needs or refactor it so that the API exposes errors in a more conventional way?
I notice the repo doesn't have issues enabled or I'd raise it there.
> Fix: Check for format errors when printing history

- atuin-client/Cargo.toml
- atuin-client/src/api_client.rs
- atuin-client/src/settings.rs
- atuin/Cargo.toml
In the packaging rules of some Linux distributions, the software's self-update check needs to be permanently turned off
This commit will make it easier for these users to
> chore: add feature to allow always disable check update

- atuin/src/command/client/search/history_list.rs
- atuin/src/command/client/search/interactive.rs
This makes it much more obvious whether you're in normal or insert mode.
> feat(ui): When in vim-normal mode apply an alternative highlighting to the selected line

- atuin/src/command/init.rs
- atuin/src/shell/atuin.bash
This is a suggestion for the keybinding to <kbd>/</kbd> motivated by @Nemo157's comments https://github.com/atuinsh/atuin/pull/1553#issuecomment-1892022291 and https://github.com/atuinsh/atuin/pull/1570#issuecomment-1892163553.
Also, I suggest removing keybinding to <kbd>C-r</kbd> in the `vicmd` keymap of Zsh since it overwrites the existing widget (redo) which is not a search. Since this involves removal of a keybinding, I think we need to discuss it carefully.
See also the commit message.
> feat(shell)!: bind the Atuin search to "/" in vi-normal mode

- atuin/src/command/client/search/history_list.rs
Fixes issue from https://github.com/atuinsh/atuin/pull/1574#discussion_r1467552000 (though, I wasn't able to reproduce, the failure implies that `PREFIX_LENGTH` is inadequate for some situations, and the previous implementation would have been overwriting the already printed duration).
> fix: Skip padding time if it will overflow the allowed prefix length

- atuin/src/command/init.rs
- atuin/src/shell/atuin.zsh
- docs/ru/key-binding_ru.md
- docs/zh-CN/key-binding.md
This is another suggestion. See the commit message.
For more contexts, the following is the list of how the other zsh frameworks name their widgets:
- https://github.com/jeffreytse/zsh-vi-mode ... `zvm_*`
- https://github.com/babarot/zsh-vimode-visual ... `vi-visual-*`
- https://github.com/junegunn/fzf/blob/master/shell/key-bindings.zsh ... `fzf-*-widget`
- https://github.com/ohmyzsh/ohmyzsh/
- `plugins/{fuck,history-substring-search,man,per-directory-history,sudo,shrink-path}` ... `<PLUGIN>-*` (where `<PLUGIN>` is the name of the plugin)
- `plugins/{npm,percol}` ... `<PLUGIN>_*`
- `plugins/git-escape-magic` ... `<PLUGIN>.*`
- `plugins/{globalias,copybuffer,fancy-ctrl-z}` ... `<PLUGIN>` (These define a single widget that has the same name as the plugin)
- `plugins/zsh-navigation-tools` …
> feat(zsh): update widget names

- atuin-client/src/api_client.rs
- atuin-common/src/api.rs
- atuin-server-database/src/lib.rs
- atuin-server-postgres/src/lib.rs
- atuin-server/src/handlers/user.rs
- atuin-server/src/router.rs
- atuin/src/command/client/account.rs
- atuin/src/command/client/account/change_password.rs
- atuin/tests/sync.rs
Fixes #1374
This PR both adds an API endpoint to the server (`PATCH /account/password`) and adds a corresponding cli command to use it. To change an account password, both a valid session and the current account password are necessary (the current password being verified to ensure it can't be changed without already knowing the password). This simply modifies the hash in the database, returning 200 on success. I tried to keep the code style similar to the surrounding code, so hopefully it is fine :)
By the way, while implementing this, I did notice that the delete account endpoint has no type of verification whatsoever, and doesn't even have a confirmation on the CLI, which kind of makes the required password for changing the password pointless as you can just delete re-register as a …
> Add change-password command & support on server

- atuin.nix
For a few reasons
1. This step is really, really slow. I don't think there's sufficient value in a slow CI step to keep it
2. Whenever we add an integration test it needs to be added to the ignore list. I want to keep friction on adding such tests as low as is possible.
3. We already run tests in a bunch of places, so I don't think this is needed
Ref: #1123
> chore: disable nix tests

- atuin-client/src/history/store.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- atuin-client/src/record/sync.rs
- atuin/src/command/client/account/delete.rs
- atuin/src/command/client/account/register.rs
- atuin/src/command/client/history.rs
- atuin/src/command/client/sync.rs
Automatically import history from the old DB when record sync is enabled.
This means that users only need to add
```
[sync]
records = true
```
to use the new system.
I've tested this on systems that already have record sync enabled + have already init-d the records. As well as those that used the old sync, and then enabled record sync.
> feat: automatically init history store when record sync is enabled

- Cargo.lock
- atuin-client/src/record/mod.rs
- atuin/Cargo.toml
- atuin/src/command/client/history.rs
- atuin/src/command/client/store.rs
- atuin/src/command/client/store/push.rs
- atuin/src/command/client/store/rebuild.rs
- atuin/tests/common/mod.rs
- atuin/tests/sync.rs
- atuin/tests/users.rs
This allows the user to _push_ records from the current host, without full syncing.
Coming next:
1. Push, along with `--force`/`--rewrite`. This will allow a host to overwrite the remote store. If you would like to change an encryption key, this is more or less the only way to do so. Think of it like `git push --force`
2. Pull
> feat: add store push

- atuin-client/src/encryption.rs
Now that local history is stored encrypted, new_key should not overwrite an existing one. This may be frustrating, but will remove the risk of Atuin generating a new key and the user losing their old one.
> fix: never overwrite the key

- flake.nix
I accidentially broke my atuin database by executing `atuin` from the PR I was working on without setting these variables and had to manually roll back my local database.
That shouldn't happen, so we set the database and record store path in the devshell to something that does not overwrite our normal databases. We also warn if these files already exist, because when entering the devshell, a user might want to start from a clean slate here.
> Set ATUIN_ variables for development in devshell

- .github/workflows/release.yaml
- .github/workflows/rust.yml
I can now use this instead of the mac under my desk!
No more CI approvals required 🥳
> chore(ci): use github m1 for release builds

- atuin/src/shell/atuin.bash
Fixes #1668
The descriptions are found in commit messages.
> fix(bash/preexec): erase prompt last line before Bash renders on it

- atuin/src/shell/atuin.bash
The current implementation assumes terminfo names for the `tput` command, but some implementations of `tput` only accept termcap names. See the commit messages for the details. This PR includes refactoring/performance improvements for `tpu` in the second commit.
> fix(bash/preexec): support termcap names for tput

- atuin-client/src/database.rs
On my ZFS system, commands were being blocked by history insertion due to `FULL` durability being enabled by default in SQLx for the WAL, sometimes for over a second, but at least half the time there was at least 500ms before the command was run. According to the [documentation](https://www.sqlite.org/pragma.html#pragma_synchronous), `NORMAL` is recommended.
With this change, my terminal commands are no longer being blocked.
- [x ] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [ x] I have checked that there are no existing pull requests for the same thing
> set durability for sqlite to recommended settings

- atuin-client/src/history.rs
- atuin-client/src/settings.rs
- atuin/src/command/client/stats.rs
Means we don't try and load timezones in tests, as this fails due to multiple threads.
Also allow specifying '0' or 'utc' as a timezone
> fix(tests): add Settings::utc() for utc settings

- Cargo.lock
- atuin-client/Cargo.toml
- atuin-client/src/history/store.rs
- atuin-client/src/record/sync.rs
Replace lots of logging with some progress bars. This looks much nicer
I'd like to move it out of the atuin-client crate and into the atuin crate. But first, I want to decouple a lot of the record moving, so it can wait until that's done.
> feat: add progress bars to sync and store init

- atuin/src/command/client/search/interactive.rs
The `Stdout::new` function first enters an alternate screen then later enables enhanced keyboard mode.
In `Drop`, we need to do this in the opposite order: disable enhanced keyboard mode then exit alternate mode.
Fixes #1693
> fix: reorder the exit of enhanced keyboard mode

- atuin/src/command/client/search/interactive.rs
The current 'i' binding to switch to insert mode is entirely unintuitive since what I almost always want to do is append to the current query. The fact that the cursor extends past the current input (which vim doesn't do with default settings) adds to the problem. The 'a' key is what I would reach for, but 'A' makes a lot of sense too so I added that.
The 'h' and 'l' bindings for moving the cursor also help makes things a bit more usable.
> feat: Add 'a', 'A', 'h', and 'l' bindings to vim-normal mode

- atuin-client/src/history/store.rs
Instead of lots of small sqlite transaction, do one monster one.
A single tx with 100s of 1000s of rows should be fine on all systems
A very unscientific test shows this to be roughly 10x faster
> perf: optimize history init-store

- atuin/src/command/client/search/history_list.rs
For the following situation:
```
$ atuin search -i --inline-height 15
[     HOST     ] query
> 1m    19d ago item 1
1 0s    1mo ago item 2
2 0s    1mo ago item 3
3 0s    1mo ago item 4
4 0s    1mo ago item 5
5 0s    1mo ago item 6
Atuin v17.2.1 [...]
```
Scrolling to item 6 results:
```
[     HOST     ] query
0s    1mo ago item 3
0s    1mo ago item 4
0s    1mo ago item 5
> 0s    1mo ago item 6
Atuin v17.2.1 [...]
```
With this patch it becomes:
```
[     HOST     ] query
1m    19d ago item 1
0s    1mo ago item 2
0s    1mo ago item 3
0s    1mo ago item 4
0s    1mo ago item 5
> 0s    1mo ago item 6
Atuin v17.2.1 [...]
```
> fix(ui): don't preserve for empty space

- atuin/src/command/client/search/interactive.rs
Fixes https://github.com/atuinsh/atuin/issues/1719
The background is explained in the commit mesasge.
I know there is tension between the readline bindings and Atuin's specific bindings for the available key-sequence space, but I think <kbd>C-m</kbd> cannot be used for Atuin's feature anyway because it can only be used with the terminals with an extended keyboard protocol.
> feat(search): process Ctrl+m for kitty keyboard protocol

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/stats.rs
This resolves #1714.
I add a `ignored_commands` option to `stats` so that common commands that you don't want showing up in stats can be skipped.  
- I am unsure what the default for this option should be: I left it empty so as to keep it consistent with existing behaviour.  Happy to change that if you want.
- I added a test for this, which required updating the return signature for `compute_stats` -- I think in the long run the way to test this is by splitting out `compute_stats` from the function that prints the results, but I thought that might be too much for this PR.  Happy to take a stab at this if you disagree.
Output on my machine, using `ignored_commands = ["cd", "vi", "ls"]`:
(before)
```
> target/release/atuin stats
[▮▮▮▮▮▮▮▮▮▮] 903 cd
[▮▮▮▮▮▮▮▮▮ ] 874 vi
[▮▮▮▮▮▮    ] 619 ls …
```
> add 'ignored_commands' option to stats

- Cargo.lock
- Cargo.toml
- atuin-config/Cargo.toml
- atuin-config/src/lib.rs
- atuin-config/src/shell.rs
- atuin-config/src/shell/bash.rs
- atuin-config/src/shell/fish.rs
- atuin-config/src/shell/xonsh.rs
- atuin-config/src/shell/zsh.rs
- atuin-config/src/store.rs
- atuin/Cargo.toml
- atuin/src/command/client.rs
- atuin/src/command/client/config.rs
- atuin/src/command/client/config/alias.rs
- atuin/src/command/client/default_config.rs
- atuin/src/command/client/init.rs
- atuin/src/command/client/init/bash.rs
- atuin/src/command/client/init/fish.rs
- atuin/src/command/client/init/xonsh.rs
- atuin/src/command/client/init/zsh.rs
- atuin/src/command/mod.rs
```
atuin config alias set k kubectl
```
to set an alias. in this example, alias k -> kubectl
```
atuin config alias delete k
```
to delete an alias, in this example deleting the one we just set.
Aliases will be copied across shells, and across machines. All that's needed is a shell reload (in the future maybe let's remove that too)
> feat: support syncing aliases

- atuin/src/shell/atuin.bash
Reverts atuinsh/atuin#1509
cc @akinomyoga 
Looks like this is causing some of the "bash not recording commands" issues, from what I've managed to replicate. I'd rather take inaccurate timings vs missed commands :/
> Revert "fix(bash): avoid unexpected `atuin history start` for keybindings"

- atuin/src/shell/atuin.bash
> Revert "Revert "fix(bash): avoid unexpected `atuin history start` for keybindings""

- atuin/src/shell/atuin.bash
Explanations are in the commit message. I've quickly tested it locally and confirmed that the user commands are at least not missing, but I think @ellie can also test it locally to carefully see the behavior.
Refs. #1003, #1509, #1727, #1728, [Forum 175](https://forum.atuin.sh/t/atuin-bash-and-ble-sh/175)
> fix(bash): rework #1509 to recover from the preexec failure

- atuin-client/src/database.rs
This pr adds a new search mode called "exact" as skim calls it, in which the query are matched as substrings of the target. In this way, there are much fewer results than the so-called fuzzy search mode, thus provide more relevant results as long as the query is correct.
I usually can't relate fuzzy results to my queries, so I always use this kind of substring match. There is also a full text search mode, which I find less useful as only one substring can be provided.
> feat: add an exact search mode

- atuin/src/shell/atuin.nu
This should be merged when the next version of *Nushell* releases, where it'll change the `commandline` syntax.
> refactor(nushell): update `commandline` syntax, closes #1733

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/search/interactive.rs
If the config option is set the `false`, using the up/down key won't exit the TUI when scrolled past the first/last entry.
Example:
```
[keys]
scroll_exits = false
```
The default is `true`, which is the current behavior.
/ref https://forum.atuin.sh/t/add-option-to-stop-down-arrow-exiting-search/94
fixes #922
> feat(client): add config option keys.scroll_exits

- atuin/src/command/client/history.rs
Closes https://github.com/atuinsh/atuin/issues/1742 by implementing the new `atuin history prune`  subcommand discussed in this issue. This command defaults to removing matching lines, which can be previewed via the `--dry-run` command flag.
TODO:
> feat: add history prune subcommand

- atuin-client/src/import/zsh_histdb.rs
This PR do two things:
1. Imports `exit_status` and `session` columns from zsh-histdb
2. Converts `duration` to nanoseconds for importing
> fix(import/zsh-histdb): missing or wrong fields

- atuin/src/command/client/config/alias.rs
This PR tries to clarify the info messages when working with aliases. No functional changes were made.
The delete message mentions which alias with which value was deleted so that the user can confirm that this is indeed the alias they wanted to remove. If not, they can reset it again. In case of an error, the error message format of `rm` is followed: `problem: reason` (`rm: cannot remove 'file': No such file or directory`).
The set alias message clearly separates the beginning and end of alias `name=value` from the normal text. Otherwise, one needs to parse the `name=value with name=value2` where `with` blends in with the end of the `value`.
```
$ atuin config alias set m "make run"
Overwriting alias m=make with m=make run
Overwriting alias 'm=make' with 'm="make run"'.
```
If the …
> Clarify operation result for working with aliases

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- atuin-client/Cargo.toml
- atuin-server-database/Cargo.toml
- atuin-server-postgres/Cargo.toml
- atuin-server/Cargo.toml
- atuin/Cargo.toml
I backported a fix + released v18.0.2, but also need to ensure `main` is up to date with the latest version.
I didn't want to release everything on `main`, just the fix. Hence this :)
> chore(release): prepare for release v18.0.2

- atuin/src/command/client/search/interactive.rs
atuin no longer panics, if the inspector is invoked from an empty search window.
fixes #1713
> fix(client): no panic on empty inspector

- atuin-client/src/settings.rs
Composer is the de facto standard dependency manager for PHP, similar to NPM for node. This PR updates the `common_subcommands_default` so that composer is included by default like similar tools for node.
> Add PHP package manager "composer" to list of default common subcommands

- atuin/src/command/client/search/interactive.rs
Add 'I' binding to vim-normal mode (a la 'A' introduced in #1697) to jump into vim-insert mode at the beginning of the search input.
Also add '/' and '?' bindings to vim-normal mode to clear the search input and jump into vim-insert mode. This mimics the UX in e.g. `set -o vi` (bash) or `bindkey -v` (zsh) mode when you are using 'k' and 'j' to browse history lines and can type '/' or '?' to start a new search. (In a perfect world it would target the search in the forward or backward range starting at your current position in the history, but this is a reasonable first step.)
> feat: Add '/', '?', and 'I' bindings to vim-normal mode

- Cargo.lock
- atuin/Cargo.toml
- atuin/src/command/client/stats.rs
This addresses feedback in #1054
Closes #1054
> Enable multiple command stats to be shown using unicode_segmentation

- .github/workflows/update-nix-deps.yml
Adds a github action that will update the Nix dependencies once a month, and can also be triggered manually.
I ran this in my fork, and confirmed it works as expected. See https://github.com/arcuru/atuin/actions/workflows/update-nix-deps.yml and https://github.com/arcuru/atuin/pull/56
> feat(nix): add update action

- atuin-client/config.toml
- atuin-client/src/settings.rs
I've been using atuin on my Linux box for some time now and I have noticed that a few commands that are used rather often are not in the list of common_subcommands.
This change adds these commands to the list.
see also https://github.com/atuinsh/docs/pull/38
> feat(stats): add linux sysadmin commands to common_subcommands

- atuin/src/command/client/search/interactive.rs
in Vim/Neovim there is alias for `<Esc>` mapping -- `<C-[>`. it is useful if your `<Esc>` key is hard to hit on your keyboard.
for reference:
- https://vimhelp.org/insert.txt.html#i_CTRL-%5B
- https://neovim.io/doc/user/insert.html#i_CTRL-%5B
> feat: add `CTRL+[` binding as `<Esc>` alias

- atuin/src/command/client/init.rs
Fixes #1025
This seems to work, see the nushell docs for `until`, and how it can account for the menu handling: https://www.nushell.sh/book/line_editor.html#until-type
> fix(nushell): readd up-arrow keybinding, now with menu handling

- .github/workflows/release.yaml
- Cargo.lock
- Cargo.toml
- atuin/Cargo.toml
- atuin/src/command/gen_completions.rs
- atuin/src/command/mod.rs
As mentioned on Discord, I noticed that clap offers completion generation for nushell in a separate crate. I went ahead and implemented these for the existing gen-completions command.
Some extensive implementation notes:
- When installing the new dependency, I also updated the clap and clap_complete versions in the manifests. I thought it couldn't hurt to have the whole group up to date when installing a new part. Looking at the lock file changes, I believe it had these versions already installed anyway.
- I moved the gen-completions code into a new module, similar to the other commands. With the extra impl it took up quite a bit of space in `mod.rs` otherwise.
- After trying out a few variants of composing the two crates into one command, I landed on defining an enum ourselves and adding …
> feat(nushell): add nushell completion generation

- Cargo.lock
- atuin/Cargo.toml
- atuin/src/command/client.rs
- atuin/src/command/client/doctor.rs
This should help a bunch with diagnosing support issues
I've built it to output a datastructure as YAML. The reason here is that in the future, we can easily build functions that will take setup information and suggest fixes for common problems.
Or even automatically fix them!
Plugin detection right now has a couple notes
1. It only detects bash preexec or ble. This is most of what we are concerned about at the moment
2. It relies on running env in a shell subprocess. Many env vars that are useful to detect plugins are not exported. This is the only easy way I can see right now, though it is kinda gross.
> feat: add atuin doctor

- atuin/src/command/client/search/interactive.rs
fixes #1792
Padding did not help. The only way was to decrease the width by 2 in non-compact mode.
> fix: missing characters in preview

- atuin/src/command/client/sync.rs
Only check lengths and suggest a store re-init _after_ the sync.
> fix(sync): check store length after sync, not before

- install.sh
Hi.
- [✔️ ] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [✔️ ] I have checked that there are no existing pull requests for the same thing
* I searched issues for "bash 3.2" and got nothing relevant.
I'm on OS X, version `Sonoma 14.2.1 (23C71)`, which ships an ancient version of bash (3.2).
Atuin doesn't work under bash 3.2. it runs when I hit "up", but then when I hit enter, the command doesn't get put into the line to be run if I hit enter a second time.
Of course, the first thing to do with that is to upgrade to a recent version of bash using homebrew.
Unfortunately, that doesn't always take fully, resulting in bash 3.2 getting run... sometimes.
This adds a guard to install.sh, erroring out, saying that Atuin doesn't work in bash 3.2.
> Guard against ancient versions of bash (3.2) where Atuin does not work.

- atuin-client/config.toml
- atuin-client/src/settings.rs
- atuin/src/command/client/search/interactive.rs
From https://github.com/atuinsh/atuin/issues/1754
Yet to do local testing, but this is what I had in mind.
> Add config setting for showing tabs

- atuin-client/src/settings.rs
- atuin/src/command/client.rs
Read settings earlier on, to reduced risk of being in a multithreaded env
if we fail to read the timezone, fallback to UTC. This is only used for display, as we always stored UTC anyway. The user can still specify a different tz if they wish
> fix(tz): attempt to fix timezone reading

- atuin/src/shell/atuin.nu
Somewhat recently in Nushell, we added a [CLI option](https://github.com/nushell/nushell/pull/11550) to disable command history. This is very similar to fish's private mode. Like in #577, this PR skips `atuin history start` if history is disabled.
> Nushell: check if command history is disabled

- atuin-server/src/handlers/v0/record.rs
Settings the record size limit to 0 had issues. Inverting the condition works better.
> fix(sync): record size limiter

- Cargo.lock
- atuin-client/src/api_client.rs
- atuin-client/src/database.rs
- atuin-client/src/history.rs
- atuin-client/src/import/xonsh.rs
- atuin-client/src/import/xonsh_sqlite.rs
- atuin-client/src/import/zsh_histdb.rs
- atuin-client/src/lib.rs
- atuin-client/src/utils.rs
- atuin/Cargo.toml
- atuin/src/command/client/search/interactive.rs
Hi!
I've been trying to get atuin set up on the illumos machine I built for work @oxidecomputer, and I ran into a few issues which are fixed here:
1. The `clipboard` feature was only supported on Windows, Mac and Linux. I've added a platform gate for that.
2. The `atomic-write-file` crate needed an update to the version of `nix` -- that is included.
3. As part of this, I found a [security bug](https://rustsec.org/advisories/RUSTSEC-2024-0020.html) in the whoami crate. The bug has been fixed upstream and I've included it (it's required to prevent a crash that happens on illumos).
whoami 1.5.0 deprecates the `hostname` function, which produced some fresh warnings. While fixing the warnings I also took the liberty of doing some code rearrangement, adding a few functions that wrap some common …
> make atuin compile on non-win/mac/linux platforms

- atuin.nix
Small change, as nixpkgs is starting to require meta.mainProgram to be set for the package. I also updated the link to the nixpkgs package after some refactoring in that repo broke the link. They don't intend to move it again.
> fix(nix): set meta.mainProgram in the package

- atuin-client/src/settings.rs
- atuin-client/src/settings/dotfiles.rs
- atuin/src/command/client/dotfiles/alias.rs
- atuin/src/command/client/init.rs
- atuin/src/command/client/init/bash.rs
- atuin/src/command/client/init/fish.rs
- atuin/src/command/client/init/xonsh.rs
- atuin/src/command/client/init/zsh.rs
While it only costs a few ms, dotfiles is not yet as optimised as it should be. Running the whole store build _is_ fast, but could be faster. I don't want to add the cost to all users, only those using dotfiles.
With a few hundred aliases set, building the alias list takes me around 20ms. Imo init should only be "read a prebuilt list", with no compute required.
> feat(dotfiles): add enable setting to dotfiles, disable by default

- .github/workflows/rust.yml
Followup to #1825.
I also tried getting FreeBSD to work, but didn't get too far sadly. I don't have the time to debug this so I just put in a comment for now. (With my changes, Atuin works great on FreeBSD as well.)
> chore(ci): add cross-compile job for illumos

- atuin-client/src/history/store.rs
- atuin/src/command/client/history.rs
- atuin/src/command/client/sync.rs
This means that users do not have to run `init-store` manually any longer. With the performance improvements lately, it is also unlikely to take much time to init a store.
> feat: add automatic history store init

- docker-compose.yml
this is a small adjustment to be sure the setup works if a custom db name is set via env
> docs: use db name env variable also in uri

- atuin/src/command/client.rs
- atuin/src/command/client/info.rs
Fixes #1542 
Adds `atuin info` that prints config locations and version information (see below). This could be a sub command, but IDK what command it would fall under. Possible a new command like `atuin config` that would reset the config (just an idea)?
```
Config files:
client config: ~/.config/atuin/config.toml"
server config: "~/.config/atuin/server.toml"
client db path: "~/share/atuin/history.db"
key path: "~/.local/share/atuin/key"
session path: "~/.local/share/atuin/session"
Env Vars:
ATUIN_CONFIG_DIR = "None"
Version info:
version: 18.0.2
```
> feat: adds info command to show env vars and config files

- atuin/src/command/client/search/interactive.rs
Fixes #1753
As discussed in #1753, I think this should ideally be fixed in `crossterm`, but there are general limitations by the terminal protocols and the support by the terminals in the market. I here instead suggest solving this at Atuin's side. The description is found in the commit message and also in a code comment.
> feat(search): process [C-h] and [C-?] as representations of backspace

- Cargo.lock
- atuin-server-postgres/Cargo.toml
- atuin-server-postgres/src/lib.rs
To avoid more dupes of https://github.com/atuinsh/atuin/issues/1860, exit the server with a relevant error when PG is outdated.
This is pulling the `server_version_num` info (you can manually get it with a `SHOW server_version_num;` query). It's value is `major * 10000 + minor`, so 160002 for version 16.2. This could allow you to also check the minor version in the future if needed.
```
docker run -e POSTGRES_PASSWORD=password -p 54322:5432 postgres:13
ATUIN_DB_URI=postgres://postgres:password@localhost:54322/postgres ./target/debug/atuin server start 
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://postgres:password@localhost:54322/postgres" }
Caused by:
Other(unsupported PostgreSQL version 13, minimum required is 14
Location: …
```
> feat(server): check PG version before running migrations

- atuin/src/command/client/search/interactive.rs
This means we can prefix all Atuin keybindings with ctrl-a, totally eliminating the risk of collisions with readline/etc.
The only downside here is that ctrl-a no longer moves to the beginning of the line, as in readline.
> feat: add atuin prefix binding

- install.sh
KDE Neon is based on Ubuntu 22.04, but the OS List for Ubuntu-based distros does not have the string "neon".  This commit adds it.
> Update install.sh to support KDE Neon

- atuin/src/command/client/doctor.rs
- atuin/src/shell/atuin.bash
Partial fix for #1849 
This is *one possible approach* to solve #1849. Depending on what we want to specifically detect, we might need adjustments. For the implementation details, please see the commit message and changes. There is an extra commit 68a5d5aa that fixes the function names and code comments for the current approach using `shell -ic command` and shell variables.
I added a new environment variable `ATUIN_PREEXEC_BACKEND` in `atuin/src/shell/atuin.bash` to detect if any preexec backend is correctly set up for Atuin in the Bash session that executed `atuin doctor`. However, one might want to check the default shell setup but not the setup in the caller session. Currently, the shell name is determined by the shell that executed `atuin doctor`. In that sense, it would be natural to …
> fix(doctor): detect preexec plugin using env ATUIN_PREEXEC_BACKEND 

- atuin-client/config.toml
Enable sync v2 by default for new installs
Later, I will change the default for all existing installs.
> feat: sync v2 default for new installs

- atuin-client/src/api_client.rs
> fix: report non-decodable errors correctly

- atuin/src/command/client/search/interactive.rs
The `ctrl-a` shortcut (to jump to the beginning of the line) was replaced by the prefix.
tmux handles it in a way so that if `ctrl-a` is the prefix, `ctrl-a a` will jump to the beginning of the line.
This change implements the same machanism in atuin.
P.S.: I didn't open an issue, because it is a follow-up to #1875
> feat: add 'ctrl-a a' to jump to beginning of line

- atuin-client/src/record/sync.rs
- atuin-common/src/utils.rs
- atuin-dotfiles/src/shell/bash.rs
- atuin-dotfiles/src/shell/fish.rs
- atuin-dotfiles/src/shell/xonsh.rs
- atuin-dotfiles/src/shell/zsh.rs
- atuin-dotfiles/src/store.rs
- atuin/src/command/client/history.rs
- atuin/src/command/client/init/bash.rs
- atuin/src/command/client/init/fish.rs
- atuin/src/command/client/init/xonsh.rs
- atuin/src/command/client/init/zsh.rs
- atuin/src/command/client/store/pull.rs
- atuin/src/command/client/store/rebuild.rs
- atuin/src/command/client/sync.rs
- atuin/src/main.rs
- atuin/src/sync.rs
Previously, we'd rebuild all aliases from sqlite every single time the shell started. This is... ok? 
But not great.
With more aliases, we get slower shell starts. On a new-ish macbook pro this isn't too bad, but I imagine it gets worse with older hardware, and especially spinning rust.
This PR builds aliases into cached files every time they are mutated - either locally, or from sync. From there, starting a new shell is pretty much just reading and printing a file.
I've also neatened up the store "building" code a bit
I'd like to follow up with removing the async runtime from the init path if possible, as that is adding overhead and isn't needed to read the cached file. If the cache doesn't exist, we can start tokio and build it.
There's some obvious duplication here that could be …
> perf(dotfiles): cache aliases and read straight from file

- .codespellrc
- .github/workflows/codespell.yml
- CHANGELOG.md
- atuin-client/src/record/encryption.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- atuin-client/src/record/sync.rs
- atuin-server/src/handlers/mod.rs
- atuin/src/command/client/search/engines/skim.rs
- atuin/src/command/gen_completions.rs
> Add codespell support (config, workflow) and make it fix some typos

- atuin/src/shell/atuin.bash
In #1533, I used `return 0` for the "include guards" of Atuin's initialization. However, I noticed that it would unexpectedly cancel the entire processing of `~/.bashrc` because it is evaluated by `eval`. This is my fault. In this PR, I suggest enclosing the entire content of the integration code within a `if`-statement.
I expect the impact of `return 0` would not be so big since the problem only happens when (i) `~/.bashrc` is sourced twice in an interactive session, (ii) `eval "$(atuin init bash)"` is performed outside the interactive sessions, or (iii) it is performed in a very old version of Bash for which Atuin's doesn't offer the support. For case (ii), with a typical `.bashrc` starting with `case $- in *i*) ;; *) return ;; esac` (or equivalent), `eval "$(atuin init bash)"` is …
> fix(bash): do not use "return" to cancel initialization

- atuin/src/shell/atuin.nu
I have no idea why this works, but it does! The problem was that when atuin was syncing after a command, it would print the progress bar, this fixes it!
> feat: prevents stderr from going to the screen when syncing nushell

- README.md
I noticed that the problem of missing commands with `bash-preexec` is not mentioned in README. This PR adds a mention.
Also, the quick instruction at the beginning of README doesn't mention the possible minor problems with Bash integration, so I added a link to the later Bash section, which describes the problems in more detail.
As another change, I made those "notes" more outstanding using [the GFM blockquote](https://github.com/orgs/community/discussions/16925) so that users do not miss them. There are still reports by users who missed those notes (like #1921).
> docs(bash-preexec): describe the limitation of missing commands

- Cargo.lock
- atuin-common/Cargo.toml
- atuin-common/src/lib.rs
- atuin-common/src/shell.rs
- atuin-dotfiles/src/shell.rs
- atuin/src/command/client/doctor.rs
- atuin/src/command/client/dotfiles/alias.rs
Add a subcommand to import aliases to Atuin
Currently this only supports POSIX-ish shells (bash/zsh/fish)
Fish isn't truly POSIX compliant, but the output of `alias` matches the expected behaviour
> feat(dotfiles): add alias import

- atuin/src/shell/atuin.bash
See the commit message for the description. This applies the change suggested by @gvlassis in https://github.com/atuinsh/atuin/pull/1484#issuecomment-2047068582.
> feat(bash/blesh): use `_ble_exec_time_ata` for duration even in bash < 5

- atuin-client/src/settings.rs
Context:
update checking runs asynchronously to allow DB and UI rendering to occur concurrently with the otherwise superficial update check system.
The file accesses that take place during this check run synchronously on the main thread and can block the runtime from running the render routine. I wouldn't expect the file accesses to take long but filesystems can be weird I guess?
(extra context, [tokio::fs::File also does spawn_blocking](https://docs.rs/tokio/latest/src/tokio/fs/file.rs.html#567-570), so I would stick with fs-err here for the better error messages and not use tokio::fs)
> fix: use spawn_blocking for file access during async context

- atuin-client/src/api_client.rs
- atuin-client/src/history.rs
- atuin-client/src/record/sqlite_store.rs
- atuin-client/src/record/store.rs
- ui/backend/Cargo.lock
- ui/backend/src/main.rs
- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/App.css
- ui/src/App.tsx
- ui/src/components/Drawer.tsx
- ui/src/components/HistoryList.tsx
- ui/src/components/dotfiles/Aliases.tsx
- ui/src/components/history/Stats.tsx
- ui/src/pages/Dotfiles.tsx
- ui/src/pages/History.tsx
- ui/src/pages/Home.tsx
- ui/src/state/models.ts
- ui/src/state/store.ts
1. Start on a home page, can sort onboarding/etc from there
2. Introduce zustand for state management. It's nice!
Did a production build and clicked around for a while. Memory usage seems nice and chill.
> feat(gui): work on home page, sort state

- crates/atuin-dotfiles/src/shell.rs
Ref #1953
Added a test case and fix
cc @rigrig, does this resolve the issue for you?
> fix(dotfiles): alias import with init output

- crates/atuin-common/src/utils.rs
- crates/atuin-dotfiles/src/store.rs
We want to quote all aliases when setting config. Aliases in the store may be quoted, but may also be unquoted.
First normalise to unquoted, then quote.
> fix(dotfiles): unquote aliases before quoting

- crates/atuin-server/src/handlers/v0/record.rs
P99 is usually <100ms which is excellent, but occasionally has big spikes to 1000ms. This is only on the record index.
I don't want this to get out of hand. I've ran a few test queries and they all complete very fast, and are purely index scans.
Hopefully this helps figure out if it's a specific user with tonnes of stores or something? Otherwise there could be something up with my db.
I should probably also figure out some proper log levels or tracing lol.
> chore: add some more debug logs

- crates/atuin/src/shell/atuin.nu
I added `(version).major` and others like it in https://github.com/nushell/nushell/issues/12561 to make atuin's life easier regarding version parsing.
At the moment we obviously have to keep the support for older versions but in a year (or more?) we will be able to reasonably just use the new members I think and make that part of the script much cleaner 🤞
> nushell: use version.(major|minor|patch) if available

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search/interactive.rs
This is a follow-up PR to #1804. It implements an enum and adds a new table `[preview]` (should be used for `max_preview_height` and `show_preview` when the new settings are implemented, although the keys should be renamed then) and the `show_preview_auto` option has been renamed as mentioned in https://github.com/atuinsh/atuin/pull/991#issuecomment-2081664065
```yaml
[preview]
strategy = auto (default) | static (max_of_all_cmds)   # was show_preview_auto
```
However, I am contemplating whether to change the naming:
strategy -> mode
auto -> dynamic
I believe 
- `mode` is used in other settings and thus it might be more consistent.
- `dynamic` as it determines the height dynamically. `auto` also fits, so I really have no clue which one is better.
@ellie what do you think?
> refactor: preview_auto to use enum and different option

- Cargo.lock
- Cargo.toml
- crates/atuin-client/src/sync.rs
- crates/atuin-dotfiles/src/shell.rs
- crates/atuin/Cargo.toml
- crates/atuin/src/command/client/dotfiles/alias.rs
- crates/atuin/src/command/client/search/interactive.rs
- crates/atuin/src/command/client/stats.rs
At the moment there are far too many edge cases to handle importing aliases.
1. We need an interactive shell to print aliases. Without it, most shells won't report much.
2. Many people have their shells print things on startup (graphics, fortunes, etc). This could be detected as an attempt to set an alias.
Rather than spend the next year finding import edge cases, I'm
disabling it for now. There's probably a better way we can do this?
> fix(dotfiles): allow clearing aliases, disable import

- crates/atuin-client/config.toml
Sorry, I forgot the quotes...
```toml
```
> fix(config): add quotes for strategy value in comment

- Cargo.lock
- crates/atuin-client/src/database.rs
- crates/atuin-client/src/history/store.rs
- crates/atuin-daemon/Cargo.toml
- crates/atuin-daemon/src/server.rs
- crates/atuin-daemon/src/server/sync.rs
Ensure all stores are properly rebuilt
Also fix the max backoff interval
> fix: add incremental rebuild to daemon loop

- README.md
- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin-daemon/src/client.rs
- crates/atuin-daemon/src/server.rs
- crates/atuin/src/command/client/history.rs
Add support for the daemon on windows using tcp.
fixes #2011
> feat(daemon): add support for daemon on windows

- crates/atuin-client/src/settings.rs
- crates/atuin-client/src/settings/dotfiles.rs
- crates/atuin-server/src/settings.rs
The server has enable, the client has enabled. I've seen at least one person make this mistake, so imo it makes sense to alias the two
> fix: alias enable/enabled in settings

- crates/atuin-client/src/encryption.rs
This PR is related to #1199, but does *not* fix it. It only corrects the error message: the operation is an attempt to decrypt and is failing, but the error thrown says something about encrypting. Whatever is causing the error remanis unresolved, but at least the confusing/contradictory message can be fixed.
> Fix bogus error message

- Cargo.lock
- crates/atuin-server-postgres/Cargo.toml
- crates/atuin-server-postgres/src/lib.rs
Hi,
I think this is a bit of a niche fix since I imagine not tons of people self-host and perhaps it's something those who are running servers _do_ want, so I won't be the least bit bothered if this isn't merged.
Previously, in the event that there was a configuration issue and the atuin server failed to connect to PostgreSQL, it would log the database URI including the password.
For example, if the password authentication failed the following log message would be printed:
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:definitelymypassword@db.example.com/atuin" }
This change sets the password to "****" when printing it via Debug:
Error: failed to connect to db: PostgresSettings { db_uri: "postgres://atuin:****@db.example.com/atuin" }
Hopefully few people use …
> fix: redact password in database URI when logging

- crates/atuin-client/src/record/sync.rs
- crates/atuin-client/src/settings.rs
- crates/atuin-client/src/sync.rs
- crates/atuin-daemon/src/server/sync.rs
- crates/atuin/src/command/client/account/change_password.rs
- crates/atuin/src/command/client/account/delete.rs
- crates/atuin/src/command/client/account/login.rs
- crates/atuin/src/command/client/account/logout.rs
- crates/atuin/src/command/client/store/push.rs
- crates/atuin/src/command/client/sync/status.rs
I've also added Settings::logged_in, as there are a few places where we switch on login state.
With this change, logging out/in with the daemon running is ok! Previously, sync would stop working. It would either always be logged out, or keep trying to make requests but get a 403.
> fix(daemon): do not try to sync if logged out

- crates/atuin-client/Cargo.toml
- crates/atuin-client/src/import/mod.rs
- crates/atuin-client/src/import/replxx.rs
- crates/atuin/src/command/client/import.rs
As discussed in Discord, this feature should be useful for managing history of applications which use https://github.com/AmokHuginnsson/replxx . One notable example would be ClickHouse.
I'll try to integrate atuin into clickhouse-client later.
> Support importing from replxx history files

- .codespellrc
Several dictionaries suggest keeping the hyphen. In fact, it's generally a good idea to hyphenate with too many adjacent vowels.
> chore(codespell): ignore CODE_OF_CONDUCT

- crates/atuin/src/command/client.rs
- crates/atuin/src/command/client/history.rs
The client commands would open sqlite, even if not 100% required
Remove this for
1. history start/end with daemon enabled
2. shell init
Init seems to be around 2ms faster on my system, with this change.
> perf: only open the database for commands if strictly required

- Cargo.lock
- Cargo.toml
- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin-daemon/Cargo.toml
- crates/atuin-daemon/src/server.rs
- ui/backend/Cargo.toml
This avoids issues with clients attempting to connect to the daemon while it's starting, systemd creates the socket early and will queue connections up until the daemon is ready to accept them. It also allows delaying starting it until it's needed.
You can see an example usage at https://github.com/Nemo157/dotfiles/commit/967719ddc17c1d0060240106df1ca14c058936d2
> feat: support systemd socket activation for daemon

- crates/atuin-client/src/api_client.rs
For Atuin Cloud, we rate limit login attempts (and a few other endpoints). Ensure that the user gets a descriptive response
For self hosted users, if you wish to rate limit, I'd suggest configuring this with your reverse proxy.
> chore: handle rate limited responses

- crates/atuin/src/shell/atuin.bash
See the commit message. This fixes a problem reported at https://forum.atuin.sh/t/up-arrow-error-commands-not-saved/339
> fix(bash): fix a workaround for bash-5.2 keybindings

- install.sh
Issue https://github.com/atuinsh/atuin/issues/2031 was caused by an outdated rustc version. 
The build should ideally fail with a better error message (is the workspace's `rust-version` lower than this dep's?), but in the meantime let's log both cargo and rustc versions to help with support.
> install.sh: log cargo and rustc version

- crates/atuin-client/src/database.rs
- crates/atuin/src/command/client.rs
- crates/atuin/src/command/client/doctor.rs
Report the sqlite version to detect unsupported versions possibly brought in by third-party patching.
We could also grab the `libsqlite3_sys::SQLITE_VERSION` constant, but it requires listing this transitive dependencies in the deps, as sqlx_sqlite does not re-export this constant. Opening a sqlite connection also allows querying the build flags, which we might want to log too.
> feat(doctor): report sqlite version

- crates/atuin-client/src/api_client.rs
Closes https://github.com/atuinsh/atuin/issues/2030 - unless you downgraded `api.atuin.sh` by mistake, this is misleading error reporting on non-200 responses:
- Use the `handle_resp_error` helper on the registration and login code paths for consistency. Tune its strings to be a bit more generic, feel free to reword
- Only check the server version if the request is a 200 (if we get a 503 from the CDN, the version check would run and wrongly report)
- Remove the version fallback from `ensure_version` if the header is not preset. Since we bumped the major version, the fallback is not needed + the header has been present for 6 months
Tangentially related, should `handle_resp_error` directly call `ensure_version` now, to ensure a consistent behaviour?
> fix(client): better error reporting on login/registration

- .github/workflows/update-nix-deps.yml
This CI schedule runs on forks, creating PR notification that could be confusing to contributors. Change workflow setup to only run on the canonical repo. People can still run it manually if they wish.
> chore(ci): don't run "Update Nix Deps" CI on forks

- Cargo.toml
`rust-version` on the workspace is set to 1.70 while env_logger requires 1.71 and  clap requires 1.74. Bumping accordingly.
You can check it with `cargo hack check --rust-version -p atuin --all-targets --ignore-private`, as documented in [the cargo book](https://doc.rust-lang.org/cargo/guide/continuous-integration.html#verifying-rust-version). This could be automated before releases if you have the insanity points to spend on GA.
Fixes #2031
> chore(deps): raise MSRV to 1.74 to match dependencies

- systemd/atuin-server.service
- systemd/atuin-server.sysusers
Fixes https://github.com/atuinsh/atuin/issues/1864.
> Add Systemd config for self-hosted server

- Cargo.lock
- crates/atuin/Cargo.toml
- crates/atuin/src/command/client/doctor.rs
Closes #2081. 
The output will look a bit uglier, but it does the job. Here's my machine
```bash
{
"atuin": {
"version": "18.2.0",
"sync": null,
"sqlite_version": "3.44.0"
},
"shell": {
"name": "bash",
"default": "bash",
"plugins": [],
"preexec": null
},
"system": {
"os": "Ubuntu",
"arch": "x86_64",
"version": "23.10",
"disks": [
{
"name": "/dev/sda2",
"filesystem": "ext4"
},
{
"name": "/dev/sdb1",
"filesystem": "ext4"
},
{
"name": "/dev/sda2",
"filesystem": "ext4"
}
]
}
}
```
> Fix 2081: Replace serde_yaml::to_string with serde_json::to_string_yaml

- CHANGELOG.md
- CONTRIBUTORS
- Cargo.lock
- Cargo.toml
- crates/atuin-client/Cargo.toml
- crates/atuin-daemon/Cargo.toml
- crates/atuin-dotfiles/Cargo.toml
- crates/atuin-history/Cargo.toml
- crates/atuin-server-database/Cargo.toml
- crates/atuin-server-postgres/Cargo.toml
- crates/atuin-server/Cargo.toml
- crates/atuin/Cargo.toml
First, rather than the weekly tagging I've been doing for a while, I'd like to formalise the process a little. This means that the release process runs much more often, and hopefully because streamlined and more reliable.
Second, test out `cargo-dist` by cutting a prerelease :)
> chore(release): v18.3.0-prerelease.1

- ui/backend/Cargo.lock
- ui/backend/Cargo.toml
- ui/backend/src/main.rs
- ui/backend/src/update.rs
- ui/src/App.tsx
- ui/src/components/LoginOrRegister.tsx
- ui/src/state/store.ts
Ensure there is only one running instance of the UI, and foreground it if we try to open another
(will also be useful when the UI embeds a sync daemon, in the future)
> feat(ui): setup single-instance

- flake.lock
- flake.nix
Closes #2089 
This PR moves the nix flake to using a rust toolchain provided by fenix (https://github.com/nix-community/fenix), which downloads the toolchain declared in `./rust-toolchain.toml`, removing the requirement on nixpkgs to update rustc for us to bump MSRV.
When the value in `./rust-toolchain.toml` is changed, the nix build must be run locally once (with `nix build -L`). This will print the new sha256 hash for the new rust toolchain, that must then be inserted into `flake.nix` before the build will succeed. This may be automatable via a github action - that is not included in this PR.
> De-couple atuin nix build from nixpkgs rustc version

- .cargo/audit.toml
Ignore RUSTSEC-2023-0071
This is because rsa is in our lockfile. We do not actually require rsa, and it is not a part of `cargo tree`
It's pulled in by sqlx, even though we're not using it. This is a known bug with cargo
See
- https://github.com/launchbadge/sqlx/issues/3211
- https://github.com/rust-lang/cargo/issues/10801
Also note that Atuin's encryption does not use RSA, and never has
> chore: add audit config, ignore RUSTSEC-2023-0071

- crates/atuin-client/src/settings.rs
> fix: unitless sync_frequence = 0 not parsed by humantime

- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search/interactive.rs
> feat(tui): configurable prefix character

- crates/atuin-client/config.toml
The commented-out config lines seem to show the default value for each config option.
This isn't true for `scroll_exits`, which actually defaults to `true`.
> Fix `scroll_exits` default in `config.toml`

- ui/src/App.tsx
- ui/src/pages/Home.tsx
- ui/src/state/store.ts
> feat(gui): cache zustand store in localstorage

- crates/atuin-client/src/secrets.rs
Add secret key filters for `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AZURE_STORAGE_ACCOUNT_KEY`, and `GOOGLE_SERVICE_ACCOUNT_KEY`.
I don't know how common these environment variables are. I know there are a lot of libraries that look in AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env vars for credentials, but I've done a bunch of searching and it seems like that pattern is less common for the other cloud providers?
> filter out various environment variables containing potential secrets

- Cargo.lock
- crates/atuin-client/src/api_client.rs
- crates/atuin-common/Cargo.toml
- crates/atuin-common/src/api.rs
- crates/atuin-common/src/utils.rs
- crates/atuin-server-database/src/lib.rs
- crates/atuin-server-database/src/models.rs
- crates/atuin-server-postgres/migrations/20240621110731_user-verified.sql
- crates/atuin-server-postgres/src/lib.rs
- crates/atuin-server-postgres/src/wrappers.rs
- crates/atuin-server/Cargo.toml
- crates/atuin-server/src/handlers/user.rs
- crates/atuin-server/src/router.rs
- crates/atuin-server/src/settings.rs
- crates/atuin/src/command/client/account.rs
- crates/atuin/src/command/client/account/verify.rs
- crates/atuin/tests/common/mod.rs
Add `atuin account verify` for verifying the user account email address
This is not required, and so far has no real benefit. It can be used in a follow up for resetting passwords. 
We've used Postmark for the forum for a long while now, and I'm super happy with it. Verified emails is only really beneficial for Atuin Cloud, so I'm not currently considering a generic SMTP server approach. Happy to do so if people want it, but I'd rather not maintain something nobody is using.
> feat: add user account verification

- crates/atuin-server-postgres/src/lib.rs
A couple of newer tables were missed - data is correctly cleaned up
> fix: ensure we cleanup all tables when deleting

- crates/atuin-client/src/secrets.rs
Inspired by #2174 I've added GitLab personal access tokens to the list of secret patterns.
> feat: Add GitLab PAT to secret patterns

- CHANGELOG.md
- crates/atuin-client/src/secrets.rs
- OAuth access tokens
- refresh token
- app installation token
- PAT v2
Fixes #2199
> feat: add several other GitHub access token patterns

- install.sh
For a long time I wanted to try and prioritise using package managers, so we would have the smallest impact on the users machine possible. Unfortunately with this change, the install script will no longer be doing this.
Firstly, we're limited by which package managers we are in. The fallback to build from source _really_ sucks on systems like a raspberry pi (running a flavour of debian). For that specific case, it's worth noting that Debian's repositories are very stable - even if we were packaged there, Atuin would rapidly become so out of date that it would no longer sync. Hence the proliferation of ppas.
Increasing the breadth of package managers we are included in becomes tricky in terms of support. Some have much stricter requirements than others, including dynamic linking as much as …
> chore: do not use package managers in installer

- install.sh
> chore(install): use posix sh, not bash

- crates/atuin-client/src/secrets.rs
Jumping on secrets filtering bandwagon from https://github.com/atuinsh/atuin/pull/2174 and https://github.com/atuinsh/atuin/pull/2196
I frequently use these in my work, so it would be nice to have them filtered out by default. No worries if you rather keep the builtin list small, but I think the `npm` one is probably widely used enough to justify including here.
Disclaimer: I work for Pulumi and adding Pulumi's token format here.
> feat: Add npm, Netlify and Pulumi tokens to secret patterns

- crates/atuin-server-postgres/migrations/20240614104159_idx-cache.sql
Let's stop that P99 from creeping up eh?
Postgres doesn't like group by aggregates very much (it's OLTP afterall). I'll follow up with the actual caching logic
> perf: create idx cache table

- crates/atuin-server-postgres/src/lib.rs
- crates/atuin-server/src/settings.rs
Most of the time, we will only be writing one row. So nothing major!
In the future we may want to use something like redis, but I'd like to keep the stack minimal for as long as possible.
Don't use this data yet - once enough has been written, it can be verified against current behaviour
Follow up on #2140
> perf: write to the idx cache

- crates/atuin-server/src/handlers/mod.rs
- crates/atuin-server/src/settings.rs
- crates/atuin/tests/common/mod.rs
The server usually runs unstable Atuin, and is well monitored. But let's not advertised the unstable version to clients, as they will notify users there is an update available.
> feat: allow advertising a fake version to clients

- Cargo.lock
- crates/atuin-server-postgres/Cargo.toml
- crates/atuin-server-postgres/src/lib.rs
I've tested it, but let's run with a consistency check for a while. We're not exposing cached data to users just yet, and will switch over once we've confirmed the cache does not serve stale data.
Risks of stale data are mostly clients DoS-ing the server, as they won't see up-to-date information.
> feat: monitor idx cache consistency before switching

- crates/atuin-client/src/record/sqlite_store.rs
- crates/atuin-server-postgres/src/lib.rs
While the idx cache has been consistent in almost all cases, there have been some inconsistencies.
1. They existed temporarily, but seem to have sorted themselves out with further sync traffic
2. They only existed for a small number of users, and for a very small period of time
I suspect this is because the cache was updating the max idx to be the max from a single request. This meant that if records were uploaded slightly out of order, the idx in the cache would potentially be reduced temporarily
Fixes as follows:
First, only update the idx cache to be the greatest of either the existing value or the new one. It should never decrease.
Second, ensure that when the client pages through the record store, it does so in order
> fix: idx cache inconsistency

- crates/atuin/src/command/client/doctor.rs
- crates/atuin/src/shell/atuin.bash
Currently, to set up Atuin with ble.sh in Bash, we require `ble.sh` to be loaded before `eval "$(atuin init bash)"`. This PR removes this requirement by using the shell variable `BLE_ONLOAD`, which is a hook called by `ble.sh` in its loading phase.
The hook has existed for a long time, but I was forgetting it. I remembered it and used it to run Atuin's integration on ble.sh's loading. I also update the corresponding message in `atuin doctor`.
> feat(bash/blesh): hook into BLE_ONLOAD to resolve loading order issue

- crates/atuin/src/command/client/search/interactive.rs
Previously, you could only navigate to the beginning of the line using `ctrl-a a`. Pressing `ctrl-a` twice (`ctrl-a ctrl-a`) was captured by the prefix mode trigger, preventing navigation to the beginning of the line. This PR makes it possible to navigate to the beginning of the line using either `ctrl-a a` or `ctrl-a ctrl-a`.
> fix(search): Press ctrl-a twice should jump to beginning of line

- Cargo.lock
- crates/atuin/Cargo.toml
- crates/atuin/src/command/client/search/interactive.rs
Unfortunately I don't think this is covered by the tests, so I am not sure how correct it is. I've mostly followed the example [here](https://github.com/1Password/arboard/blob/master/examples/set_html.rs)
---
closes #2028
@ovv Could you give it a try? the current fix here seems to work on my end, but I don't think it's reliable
> Replace `cli-clipboard` with `arboard`

- ui/backend/src/pty.rs
- ui/backend/src/run/pty.rs
Ensure that when the users presses "stop", the child process is properly terminated
Previously _most_ processes would stop ok, but some would not. An example of one that didn't would be an interactive ssh process. 
With this patch, the process is sent KILL and stops. 
We should probably consider being a bit gentler.
> fix(gui): kill child on block stop

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search/interactive.rs
Uses max_preview_height as a fixed value to prevent the list from "jumping".
> Fixed preview height

- .gitignore
- crates/atuin/src/command/client/history.rs
fixes  #2227
Just updated the conditional here to check the `exit` param instead of `h.exit` since it seems like the latter will always be `-1` here as that's the default value. Also changed the operator to `>` instead of `!=` just to reflect the fact that exit codes are expected to only be positive integers 0-255
I also added `.envrc` to the `.gitignore` file as using `direnv` for development was recommended in the CONTRIBUTING doc
> Fix logic for store_failed=false

- Cargo.lock
- crates/atuin-client/Cargo.toml
- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin-client/src/theme.rs
- crates/atuin-history/src/stats.rs
- crates/atuin/src/command/client/search/interactive.rs
Following the [discussion](https://forum.atuin.sh/t/release-v18-4-0-beta-2/417/9) about the 18-4-0.beta-2 release, I made the suggested styling change. This PR now:
* makes default named "default" not ("")
* uses `ContentStyle` internally, rather than `Color`, allowing for unset colours
* tidies up `theme.rs` for internal consistency
* avoids explicit use of colours _except_ in the stats, where it is colouring the indicator bars, and will fallback to the original set if the colours are unset
* allows any Crossterm-deserializable colour to be given, via an `@` prefix: `@ansi_(255)` or `@dark_grey`, providing a means to reference ANSI codes [**needs documented**]
As a result, changes will be needed in the docs.
> Restore default theme

- ui/backend/Cargo.lock
- ui/backend/Cargo.toml
- ui/backend/capabilities/migrated.json
- ui/backend/src/main.rs
- ui/backend/src/run/pty.rs
- ui/package.json
- ui/pnpm-lock.yaml
- ui/src/components/runbooks/editor/blocks/RunBlock/index.tsx
- ui/src/pages/Dotfiles.tsx
On Windows, we need to send \r\n. On mac/linux, just \n. Sending the windows-style leads to a double enter
Also
1. Added a new plugin to detect platforms
2. Updated the backend
3. fixed an overflow bug
> fix(gui): double return on mac/linux

- crates/atuin/Cargo.toml
- crates/atuin/src/command/client/history.rs
> fix atuin-daemon optional dependency

- crates/atuin-client/src/theme.rs
Restores the colours from 18.3.0, which had changed due to a naming mismatch between ratatui and crossterm. This can be seen in the [ratatui compatibility code](https://github.com/ratatui-org/ratatui/blob/b344f95b7cfc3b90221c84cfef8afcf6944bafc1/src/backend/crossterm.rs#L275).
To make sure, here are three versions - the most recent 18.4.1 beta (bright), the current fix and 18.3.0 running bash in default xterm config without RCs.
> fix(theme): Restore original colours

- crates/atuin-client/src/database.rs
- crates/atuin-client/src/kv.rs
- crates/atuin-client/src/record/sqlite_store.rs
- crates/atuin-client/src/record/sync.rs
- crates/atuin-client/src/settings.rs
- crates/atuin-dotfiles/src/store.rs
- crates/atuin-dotfiles/src/store/var.rs
This make it possible to control the timeout of SQLite operations in test. And `ATUIN_TEST_LOCAL_TIMEOUT` defaults to the default local_timeout, which is actually used in the client. Instead of a small timeout (0.1), this change makes the test less likely to fail and better imitate the default behavior.
SQLite operation timeout was first introduced from #1590, including connection and store timeout. The env `ATUIN_TEST_SQLITE_STORE_TIMEOUT` which added by #1703 only specify the store timeout. This commit doesn't deprecate `ATUIN_TEST_SQLITE_STORE_TIMEOUT`, but control it by setting its default to the new env `ATUIN_TEST_LOCAL_TIMEOUT`.
The reason is the same as #1703, but this time it fails due to connection timeout: [archriscv.felixc.at/.status/log.htm?url=logs/atuin/atuin-18.3.0-1.log](h …
> test: add env ATUIN_TEST_LOCAL_TIMEOUT to control test timeout of SQLite

- Cargo.lock
- crates/atuin-server/Cargo.toml
- crates/atuin-server/src/handlers/user.rs
Not 100% sure how this was working and then broke, perhaps due to another update elsewhere
```
postmark email request failed: Client { source: Communication { source: reqwest::Error { kind: Request, url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("api.postmarkapp.com")), port: None, path: "/email", query: None, fragment: None }, source: hyper_util::client::legacy::Error(Connect, "invalid URL, scheme is not http") } } }
```
> fix(mail): enable correct tls features for postmark client

- Cargo.toml
- crates/atuin/src/command/client/search/interactive.rs
- flake.lock
- flake.nix
- rust-toolchain.toml
> chore: update to rust 1.80

- Dockerfile
- flake.lock
- flake.nix
- rust-toolchain.toml
fixes #2360
https://blog.rust-lang.org/2024/08/08/Rust-1.80.1.html
`1.80.1` fixes a fairly nasty miscompilation, but that's not my motivation for opening this PR.
If I'm understanding correctly, because the rust patch version was not specified in `rust-toolchain.toml`, nix automatically upgraded to the new version. This broke the hash in `flake.nix` causing the flake to fail to build. Making this upgrade to `1.80.1` explicit, fixes this issue.
> chore: update rust to `1.80.1`

- crates/atuin-client/src/api_client.rs
This was introduced in my PR #1615 without being noticed somehow, I just happened to look at the diff of that PR and saw the macro I must have accidentally left in it. I just checked and it does indeed print the request when you attempt to change your password in the CLI, whoops!
> Remove debug statement when changing account password

- Dockerfile
The runtime needs to use the same debian release as the build environment, otherwise this just crashes on startup
> Update Dockerfile to use Bookworm for both runtime and build

- crates/atuin/src/command/client/search/interactive.rs
In the event there are no results and up is pressed, saturating_sub() should be used to avoid underflowing the usize. This was already present on scroll_down().
fixes #2393
> fix(tui): don't panic when search result is empty and up is pressed

- crates/atuin-daemon/src/client.rs
Recently, it seems, the socket location for the daemon moved and this caused me to scratch my head briefly since I saw errors from the client connecting to the daemon, but the daemon was clearly running and the socket seemed to exist.
This patch includes more context when the client fails to connect to the daemon. The path is included to help the user understand where the client was looking, and `wrap_err_with()` is used to show the user the cause of the error. This changes the error message from:
```
Error: failed to connect to local atuin daemon. Is it running?
```
to:
```
Error: failed to connect to local atuin daemon at /run/user/1001/atuin.sock. Is it running?
Caused by:
0: transport error
1: No such file or directory (os error 2)
2: No such file or directory (os error 2)
```
> fix(daemon): Add context to error when unable to connect

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin-client/src/theme.rs
- crates/atuin/src/command/client/search/history_list.rs
- crates/atuin/src/command/client/search/interactive.rs
Adds an ultracompact mode only for search (interactive.rs) and not the inspector.
* adds a config parameter to set a line height at which to switch to ultracompact
* ~~introduces a simplified inspector tab, with only previous-current-next commands as rows, in compact mode~~
* ~~allows navigation through session history within the inspector (so compact inspector view is still useful)~~
* in ultracompact view, compresses indicator row into prompt, removes any non-command lines (except help if show_help is true)
* additional tests, although keen for input on how best to do these
* documentation (once configuration/semantics are aligned on)
> Ultracompact Mode (search-only)

- .github/workflows/docker.yaml
Not 100% sure why we had this in the first place, but we definitely don't need it here
> fix: disable the actuated mirror on the x86 docker builder

- crates/atuin/src/command/client/search/cursor.rs
- crates/atuin/src/command/client/search/interactive.rs
This PR adds an additional key response for the right arrow key in the interactive history view. The right arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
The command is only selected if the cursor is in the right-most position, otherwise it allows for scrolling through the input text.
Left arrow exits if cursor is at the beginning of the line.
Closes issue #2005
> Right Arrow to modify selected command

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/history.rs
- crates/atuin/src/command/client/search.rs
- crates/atuin/src/command/client/search/engines.rs
- crates/atuin/src/command/client/search/interactive.rs
Closes #1417
Closes #1654
cc @hco @matthiasbeyer @dasJ 
This is a continuation of the work started in #1655 and #1717.
These pull requests appear to be abandoned, as there has been no activity in them for more than 5 months.
The configuration setting has been renamed according to https://github.com/atuinsh/atuin/pull/1655#issuecomment-1938310766.
> feat(client): add filter mode enablement and ordering configuration

- crates/atuin-client/src/secrets.rs
Update to use AWS env vars, replace duplicated entries.
`AWS_SECRET_ACCESS_KEY` the secret paired to Access Key IDs
`AWS_SESSION_TOKEN` the secret session token for STS sessions
AWS Access Keys should be caught by the test above for `"AKIA[0-9A-Z]{16}"` though this might also be updated to use a matching format with these two entries (including the env var name).
Relates to https://github.com/atuinsh/atuin/pull/2174
AWS documentation: https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html
> feat(client): update AWS secrets env var handling checks

- Cargo.lock
- crates/atuin-common/Cargo.toml
- crates/atuin-common/src/utils.rs
- crates/atuin-history/Cargo.toml
- crates/atuin-server-database/Cargo.toml
- crates/atuin-server-postgres/Cargo.toml
- crates/atuin-server/Cargo.toml
- crates/atuin/Cargo.toml
These dependencies are unused in actual code, and the test I've removed is a remnant from a move to use an external library -- it was useful to show that the mechanical transformation was correct, but it's only testing that library nowadays.
> chore: Remove unneeded dependencies

- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search.rs
Use `if let` rather than `is_some()` followed by `unwrap()`, and coerce errors instead of calling `unwrap()` when available.
> style: Avoid calling `unwrap()` when we don't have to

- crates/atuin/src/command/client/wrapped.rs
I noticed a crash when there is no history entries for the specified year, 2023 in my case, so I added a simple check and message.  
I'm not sure of the behavior if someone has no history for 2023 but has some for 2024 and does a `atuin import`. If it's not recommened, please let me know and I will update the error message. Feel free to change it too.
Before:
After:
> fix(wrapped): fix crash when history is empty

- crates/atuin/src/shell/atuin.bash
I noticed that if a new child Bash session is started by `enter_accept`, the `preexec` hook provided by bash-preexec is not triggered at all. This is because the child Bash session inherits the environment variable `READLINE_POINT` of the parent shell session, and `bash-preexec` considers we are still processing the Atuin menu even when a new user command is processed inside the child Bash session.
Consider the following bashrc:
```bash
source ~/.mwg/git/rcaloras/bash-preexec/bash-preexec.sh
preexec() { echo "[$FUNCNAME]"; }
precmd() { echo "[$FUNCNAME]"; }
eval "$(atuin init bash)"
```
With the current `main` branch, we first start a new child session by manually typing the command `bash` and running it:
```console
$ bash        # <-- This starts a new child Bash session
[preexec]    # …
```
> fix(bash): fix `preexec` of child Bash session started by `enter_accept`

- crates/atuin/src/command/client/search.rs
-------
This mirrors the addition to `history` from #1274, but with search too.
Ther are history search implementations for shells that are set to
search instead of running the history command.
> Add the --print0 option to search

- crates/atuin/src/command/client/search/interactive.rs
If the result set is empty and thus the TUI does not show any entries, a panic occurs when a user invokes 'delete' via `Prefix (Ctrl-A) d` or `Ctrl-D` in the inspector..
> fix: panic when invoking delete on empty tui

- crates/atuin-client/src/history.rs
- crates/atuin-client/src/secrets.rs
Improves the performance of `History::should_save` by constructing the `SECRET_PATTERNS` `RegexSet` only once with a `LazyLock`.
This speeds up `atuin history prune` by ~100x (~7s to ~70ms on my machine) (lol).
> perf: cache `SECRET_PATTERNS`'s `RegexSet`

- Cargo.lock
- Cargo.toml
Resolves: https://github.com/atuinsh/atuin/issues/2428
Resolves: https://github.com/atuinsh/atuin/issues/2012
config 0.15.8 contains the fix for https://github.com/rust-cli/config-rs/issues/579 which causes the crash mentioned in the ticket here.
I tested the resulting `atuin` binary manually, in a non-Unicode directory on my Linux box - the atuin binary I use daily (18.3.0) crashes due to `PWD` being non-Unicode, and the built atuin binary does not. I did not run any further tests (is CI enough for this?) or look if anything in particular changed in config's API across the changed versions.
> chore(deps): Update config to 0.15.8

- crates/atuin-server/src/handlers/health.rs
- crates/atuin-server/src/handlers/mod.rs
- crates/atuin-server/src/router.rs
- docker-compose.yml
- k8s/atuin.yaml
This adds an endpoint at `/healthz` which returns success. This is useful for both docker-compose and Kubernetes deployments to ensure the server is still.
> feat(health): add health check endpoint at `/healthz`

- crates/atuin-client/src/history.rs
I noticed the following after working on #2543:
I pressed and held the enter key a few times in order to go to the bottom of the screen to check how Atuin behaved, and now it thinks I love empty commands. 😄 
Even if it shouldn't happen for others that much, I suppose it makes no sense saving these, so this PR removes that.
> fix: don't save empty commands

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search/interactive.rs
The arrow key behavior in interactive search was changed in #2453, make it configurable via keys.exit_past_line_start and keys.accept_past_line_end.
> feat: make new arrow key behavior configurable

- crates/atuin-client/src/database.rs
- crates/atuin-client/src/record/sqlite_store.rs
- crates/atuin-client/src/settings.rs
- crates/atuin-common/src/utils.rs
- crates/atuin/src/command/client.rs
- crates/atuin/src/command/client/doctor.rs
- crates/atuin/src/command/client/init.rs
- crates/atuin/src/command/client/search.rs
Check atuin setting paths (eg. `db_path`) for broken symlinks on initialization and disable all shell hooks + print error message.
sqlite doesn't create db files even with `.create_if_missing` when the db files are a broken symlink. This would cause sqlite to error and atuin to panic on every single keypress.
Also improves related error handling when calling atuin client commands directly.
closes https://github.com/atuinsh/atuin/issues/2504
> fix: improve broken symlink error handling

- crates/atuin/src/shell/atuin.zsh
by using infer-next-history and then up-history.
This is very helpful to execute consecutive commands with accept-line-and-down-history.
> feat(zsh): try to go to the position in zsh's history

- crates/atuin-client/src/settings.rs
I noticed that the two had drifted - makes sense to go down to 5m anyway. We have no issues with users setting this to 0
> chore: align daemon and client default sync freq

- crates/atuin/src/command/client/search/interactive.rs
Previously:
- If the prefix is **not** `ctrl-a`: It will add an `a` character. 
- expected: Going to the beginning of line
With this fix:
- If the prefix is **not** `ctrl-a`: It will go to the beginning of line
This solves https://github.com/atuinsh/atuin/issues/2548
As I'm understanding it, if `ctrl-a` is the prefix, it will be caught earlier in the function, and if it is not the prefix, then this will act as "go to the beginning of line". 
I have manually tested this on my end and it works on my laptop at least. I didn't see any tests for key inputs specifically in the file. Let me know if there are specific tests that you would like me to add for this!
> feat: Use readline binding for ctrl-a when it is not the prefix

- crates/atuin/src/command/client/search/inspector.rs
Changes
---
Fixes https://github.com/atuinsh/atuin/issues/1578.
Adds two new rows for HOST and USER info in the inspector. Looks like this:
> chore: show host and user in inspector

- crates/atuin-client/src/import/bash.rs
- crates/atuin-client/src/import/mod.rs
- crates/atuin-client/src/import/replxx.rs
- crates/atuin-client/src/import/resh.rs
- crates/atuin-client/src/import/xonsh.rs
- crates/atuin-client/src/import/xonsh_sqlite.rs
- crates/atuin-client/src/import/zsh.rs
Xonsh history import fails as of 18.4.0 (in the default xonsh configuration) because $HISTFILE is actually a directory in that case. This change sets up the xonsh json importer to check for a *directory* instead of a regular file, and also makes it clearer that other importers expect a regular file.
> fixes #1884: HISTFILE can be a directory or a file

- crates/atuin-daemon/build.rs
Modify paths specified in the atuin-daemon build script to make tonic-build print the correct cargo:rerun-if-changed paths when the build script is run.
Fixes the atuin-daemon crate being rebuilt unconditionally, even if .proto files are unchanged.
> fix(build): change atuin-daemon build script .proto paths

- crates/atuin/src/command/client/search/interactive.rs
Pulled from https://github.com/atuinsh/atuin/pull/2543 Fixes interactive mode in fish where the terminal wasn't being displayed properly.
fixes #1289
Co-authored-by: Lucas Trzesniewski <lucas.trzesniewski@gmail.com>
I will note that this seems to draw over-top the current prompt which seems to be different than what things like fzf do.
here are two photos to constrat:
I think it would better to draw it below the current prompt to match the style of fzf but at least it does fix the corrupted prompt of #1289
> Better inline height display

- crates/atuin/src/shell/atuin.zsh
atuin will reset it so after exiting atuin without executing a command, bracketed paste mode is disabled until a command is executed. This breaks e.g. the bracketed-paste-url-magic widget.
This change will re-enable it if it's enabled; when it's disabled or unavailable, $zle_bracketed_paste[1] will be empty string.
> feat(zsh): re-enable bracketed paste

- crates/atuin-client/src/sync.rs
Fixes #2645
This is really weird
1. I have not touched this code in _years_. It has not changed. In recent rust versions, it has a typeerror (see linked issue)
2. This does not occur when running `cargo build`, in release mode or otherwise. It only occurs with `cargo install`
3. I can't find any other occurences of this typeerror online - unsure if it is a compiler regression? The code here is not very complex at all.
> fix: typeerror in client sync code

- crates/atuin-client/src/kv.rs
- crates/atuin/src/command/client/kv.rs
This PR adds support for "removing" entries from the kv store by encoding `Option`s instead of raw values.
* Adds `atuin kv delete`, aliased as `atuin kv rm`
* Updates `KV_VERSION` to `"v1"`
* Changes `KvRecord::value` to be `Option<String>`
* Updates `KvStore::set` to take an `Option` as the value
* Updates MessagePack serialization:
* If the value is `Some`, we encode a one byte boolean `true` before the encoded value
* If the value is `None`, we only write a one byte boolean `false` and no value
* Updated the array length to `4`, even if we don't encode a value
@ellie I'm not sure if you had other plans or ideas for newer versions of the kv serialization, happy to discuss!
Closes #2655
> feat(kv): Add support for 'atuin kv delete'

- crates/atuin-history/src/stats.rs
This PR updates `atuin_history::stats::compute` so that it makes a best attempt at ignoring leading environment variables when calculating the stats. This includes a new helper function `strip_leading_env_vars` that has a few tests at the bottom of the file.
Closes #2594
> fix(stats): Ignore leading environment variables when calculating stats

- .github/workflows/rust.yml
- crates/atuin-dotfiles/src/shell.rs
clippy::redundant_clone is pretty safe and helps cleanup some useless code, found a few instances of it in the codebase so though its worth adding to CI
> fix: add redundant clones to clippy and cleanup instances of it

- crates/atuin/src/shell/atuin.zsh
An extra newline was written to the terminal and caused issues. See https://github.com/atuinsh/atuin/pull/2646#issuecomment-2757157442.
> fix(zsh): fix an error introduced earilier with support for bracketed paste mode

- crates/atuin/src/command/client/kv.rs
Something got lost between #2660 and the paging PR, and deleted keys show up in `kv list` — this PR fixes that.
> fix(kv): Filter deleted keys from `kv list`

- crates/atuin/src/shell/atuin.zsh
Or those widgets may behave badly when calling them too quickly. We don't need calling them anyway as this is not considered to be user action, and if our calls fail, the history position is unchanged.
Issue introduced in #1469.
> fix(zsh): avoid calling user-defined widgets when searching for history position

- crates/atuin/src/command/client/init/fish.rs
Closes: #2672
I think this was introduced in #2616 - typing the literally characters `u p` lead to opening the TUI, as we were still executing the fish 4 bindings on fish 3.7.
> fix: fish up binding bug

- crates/atuin/src/command/client/scripts.rs
* Adds `atuin scripts ls` and `atuin scripts rm` as aliases for `atuin scripts list` and `atuin scripts delete`
* Allows piping from stdin when stdin [isn't a terminal](https://doc.rust-lang.org/beta/std/io/trait.IsTerminal.html)
> feat: Add 'atuin scripts rm' and 'atuin scripts ls' aliases; allow reading from stdin

- Cargo.lock
- Cargo.toml
- crates/atuin-daemon/Cargo.toml
Updating these together in order to avoid compatibility logos packages
- Bump protox to 0.8
Nothing notable changed afaict, although a license change should come up for it soon.
- Bump interim to 0.2
Didn't find a changelog to investigate, so I am not sure about the impact.
(dependabot is stalled because it can only have 5 open PRs. I personally think renovatebot is a better tool because it can group dependencies and it has a dashboard to view all pending updates)
> Update protox and interim

- crates/atuin-client/src/database.rs
- crates/atuin/src/command/client/history.rs
> feat: delete duplicate history

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
This PR adds `jj`, the CLI for the [Jujutsu VCS](https://jj-vcs.github.io), to the default list of `common_subcommands`. As with `git`, `jj` makes extensive use of subcommands.
> feat(stats): add jj to default common subcommands

- crates/atuin/src/shell/atuin.zsh
Resolves #2704 
After seeing a reproduction case that @BinaryMuse found, it seems like the error is occurring in the shell. Opening a new shell stops it from happening
This change reverts all changes to atuin.zsh since 18.3.0
> fix: zsh + omz selecting the wrong item from history

- crates/atuin/src/command/client/search/interactive.rs
Edit: after testing, I don't think this resolves the issue. HOWEVER I would like to make this change regardless
I can't replicate that issue just yet so i have _no idea_
It could be a classic race condition. When the UI selects an entry, it only stores the index of the selected item, not the actual entry itself. Then later, when it comes time to actually return the command, it goes back to the results array and grabs whatever is at that index. This is fine most of the time...
BUT - if anything changed the results array between selection and execution (like a new search query being processed), the index would still point to the same position, but that position might now contain a completely different history entry! 🫠
There's another potential cause too. We have the main loop, that handles …
> fix: selection vs render issue

- CONTRIBUTING.md
- crates/atuin-client/src/settings.rs
- crates/atuin-client/src/settings/scripts.rs
- crates/atuin/src/command/client/scripts.rs
- crates/atuin/src/command/client/store/rebuild.rs
- crates/atuin/src/sync.rs
This PR allows setting the Atuin scripts DB path for development, similar to the KV and history DB path overrides.
> chore: Allow setting script DB path

- crates/atuin-client/src/import/mod.rs
I tripped over this when installing atuin. A small change in the error message might help someone in the future.
My history file is in a nonstandard location. `atuin import bash` couldn't find it and said `Try setting $HISTFILE`. The problem is, my `HISTFILE` *is* set:
~~~
% atuin import bash
Atuin         
======================
🌍          
🐘🐘🐘🐘       
🐢          
======================
Importing history...
Importing history from bash
Error: Could not find history file "/home/kosak/.bash_history". Try setting $HISTFILE
Location:
crates/atuin-client/src/import/mod.rs:106:9
% echo $HISTFILE && ls -l $HISTFILE
/home/kosak/.bash_history_kosak
-rw------- 1 kosak kosak 891140 May 14 18:30 /home/kosak/.bash_history_kosak
~~~
The problem is, setting it isn't enough. It needs to be set and …
> fix: clarify that HISTFILE, if used, must be exported

- crates/atuin/src/shell/atuin.nu
Some improvements to the atuin init script for nushell
- Minimum supported version bumped to `0.93.0` (Released `2024-5-1`)
Following #1963, this nushell release is more than a year old and enables doing `if (version).major > ...` without more complications (having to check the version to see if you can check the version more ergonomically is kind of ridiculous). For a program like nushell, I don't think it makes much sense to support even older releases. I have tested this script in both `0.93.0` and latest (`0.104.2`).
- Use `random uuid -v 7` if available.
Nushell has a command for creating uuids in the core library, and it is considerably faster than calling the external `atuin uuid`, saving precious milliseconds at startup. Includes module magic to make it compatible with older …
> feat: nushell init script enchancements

- crates/atuin/src/command/client/history.rs
People may think it would keep only one copy, but it didn't work that way.
I'm sorry for people who lost their history due to this, e.g. https://github.com/atuinsh/atuin/issues/2015#issuecomment-3032340594 and #2727.
> fix: refuse "--dupkeep 0"

- Cargo.lock
- crates/atuin-client/Cargo.toml
- crates/atuin/Cargo.toml
The only breaking change in `indicatif` 0.18 is that the `console` dependency is updated to [0.16.0](https://github.com/console-rs/console/releases/tag/0.16.0); the breaking change in that release is that crates that depend on `console` with `default-features = False` may need to explicitly enable the new `std` feature.
> Update indicatif to 0.18.0

- crates/atuin-client/src/lib.rs
- crates/atuin-client/src/plugin.rs
- crates/atuin/src/command/external.rs
Cover the case where users try to `atuin update` but they did not use the install scripts. Also covers other plugins (I have a few in mind)
Longer term things like `kv` should be a plugin
> feat: add info for 'official' plugins

- Cargo.lock
- crates/atuin/Cargo.toml
- crates/atuin/src/command/client/scripts.rs
Support `$EDITOR` with args
```sh
export EDITOR="code --wait"
atuin scripts new test
```
> feat: Support multi part commands (Fixes #2836)

- Cargo.lock
- crates/atuin-server-postgres/Cargo.toml
- crates/atuin-server-postgres/src/lib.rs
Only really useful for Atuin cloud
Given a % chance, either use the idx cache or use the old aggregation query
This is to enable us to test rollout the idx cache, without breaking all queries in weird ways. Can monitor for a change in http codes/etc, and easily roll back.
This is intentionally NOT a setting, as it will be removed very soon.
> feat: add IDX_CACHE_ROLLOUT

- crates/atuin-client/src/database.rs
- crates/atuin-common/src/utils.rs
- crates/atuin-daemon/src/client.rs
- crates/atuin-daemon/src/server.rs
- crates/atuin-scripts/src/execution.rs
- crates/atuin/src/command/client/search/interactive.rs
This fixes a few build warnings and issues reported by Clippy on Windows.
This is essentially the second commit of #2714, updated with a few new lints.
> fix: build warnings and Clippy issues on Windows

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
- crates/atuin/src/command/client/search/history_list.rs
- crates/atuin/src/command/client/search/interactive.rs
Adds config show_numeric_shortcuts (default: true). When false, hides numeric badges 1–9 in the interactive search; indicator remains for selection. Adds example key to config.toml. Closes #2766.
> feat(tui): add show_numeric_shortcuts to hide 1-9 shortcuts (#2766)

- crates/atuin/src/command/client/search/interactive.rs
- crates/atuin/src/shell/atuin.bash
- crates/atuin/src/shell/atuin.fish
- crates/atuin/src/shell/atuin.zsh
I noticed that `command_chaining` requires `enter_accept` to be enabled in order to work. I suppose this wasn't intentional, so this PR dissociates these two features.
Also, xonsh doesn't handle `__atuin_chain_command__:`, so I separated the shell lists for these features.
One question though: is `__atuin_chain_command__:` necessary? Atuin could return the input query with the selected command appended, and that would be compatible with all shells. I suppose `query.join(" ")` could change the whitespace in some cases, but is there another reason?
> fix: dissociate `command_chaining` from `enter_accept`

- crates/atuin-common/src/shell.rs
- crates/atuin-common/src/utils.rs
- crates/atuin/src/command/client/search/interactive.rs
- crates/atuin/src/shell/atuin.bash
- crates/atuin/src/shell/atuin.fish
- crates/atuin/src/shell/atuin.xsh
- crates/atuin/src/shell/atuin.zsh
I had this waiting around since #2861, but needed to know what you'd chose to do with `__atuin_chain_command__`, so I didn't include it. It's just a cleanup anyway.
I initially figured maintaining several lists such as `utils::is_zsh() || utils::is_fish() || utils::is_bash()` wasn't pretty, so I refactored it (there's now a single list, but I still think it's better than before).
The scripts now use a single environment variable (`ATUIN_SHELL`), I didn't think it should be a problem but maybe there's something I missed. In any case, running one shell from another should be more reliable.
> refactor: shell environment variables

- crates/atuin-client/config.toml
- crates/atuin-client/src/settings.rs
`dotnet` is basically the equivalent of `cargo`.
> feat(stats): add dotnet to default common subcommands

- crates/atuin/src/command/client/init/fish.rs
https://github.com/atuinsh/atuin/pull/2677 introduced logic based on `$FISH_VERSION` to determine how to bind keys in fish.
However, this env var is not exported to child processes, as you can see by running `sh -c 'echo $FISH_VERSION'` from fish.
Instead, we can simply push the if statement into the actual fish code that we generate, since fish is aware of its own version, and then we can decide which binding syntax to use.
> fix: fish up binding

- crates/atuin-client/src/secrets.rs
This change tries to more accurately capture & filter secret keys by using regular expressions for the key contents, rather than trying to detect the environment variable names. For example rather than filtering matches for `AWS_SECRET_ACCESS_KEY`, this will filter for strings that take the shape of an AWS key. This provides two real benefits & 1 tangential benefit:
- (Biggest benefit): Prior to this change, if a typo is made in the keys name (e.g. `AWS_SECERT_ACCESS_KEY=<my-actual-key>`) the credential was leaked. With this change the key will still be filtered.
- (Small benefit) When trying to test commands with fake tokens (e.g. `AWS_SECRET_ACCESS_KEY=foo my-command`) then these are filtered out, which isn't always exactly desirable, as test commands like these are useful for …
> feat: more accurately filter secret tokens
