src/command/history.rs
src/command/mod.rs
src/local/database.rs
src/local/history.rs
src/local/import.rs
src/main.rs

Make better use of references. Overall, less allocs

tidy some stuff

---

Cargo.lock
Cargo.toml
src/command/import.rs
src/command/mod.rs
src/command/stats.rs
src/local/database.rs

For example
atuin stats day yesterday
atuin stats day last friday
atuin stats day 01/01/21

Add stats command

---

src/command/history.rs
src/command/import.rs
src/command/mod.rs
src/command/stats.rs

I'm finding less and less to nitpick on ;)

Some more minor changes

---

Cargo.lock
Cargo.toml
README.md
src/command/mod.rs
src/command/stats.rs
src/main.rs
src/settings.rs

Add config file support

---

.github/workflows/release.yaml
.github/workflows/rust.yml

Add some cache steps to speed up CI

cache builds

---

install.sh

Fixes issue #56 
I have added same change to bashrc file as well, but I don't use bash. If its not correct, let me know I will remove it.

Add a newline when editing shell rc files

---

README.md
docs/key-binding.md
src/shell/atuin.bash
src/shell/atuin.zsh

This should resolve #59 and resolve #51
I would still like to have more configurable key bindings! Though this could certainly happen within the respective shell config instead.

Add ATUIN_NOBIND

---

install.sh

Put cargo install in the right place

---

atuin-client/src/import/resh.rs
src/command/import.rs

When I wrote this importer (#69) I failed to notice that one of my last changes broke it. This fixes that.

Fix resh importer, and change error handling method

---

src/shell/atuin.bash

Ref https://github.com/ellie/atuin/issues/68

Fix bash integration to set the session

---

src/command/search.rs

Use format! instead of string concat

---

CHANGELOG.md
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-common/Cargo.toml
atuin-server/Cargo.toml

Release v0.7.1

---

docs/sync.md

Fix doc links in sync.md

---

README.md

Addex to homebrew via https://github.com/Homebrew/homebrew-core/pull/77138﻿

instructions to install without tap

---

Cargo.lock
atuin-client/Cargo.toml
atuin-client/src/database.rs
atuin-client/src/import/resh.rs
atuin-client/src/lib.rs
atuin-client/src/ordering.rs
atuin-client/src/settings.rs

this closes https://github.com/ellie/atuin/issues/177
I extracted the actual minspan code to https://github.com/mwotton/minspan along with some tests: there are also some basic integration tests in the fork.
Please fold, spindle and mutilate my code at will: I don't have a lot of experience in Rust and it's probably not at all idiomatic. (Or let me know what's wrong and I'll try to fix it.)

Reordered fuzzy search

---

atuin-client/src/encryption.rs
atuin-client/src/import/resh.rs
src/command/login.rs
src/command/mod.rs
src/command/register.rs

Editor picked up some new lint rules, fun :)

chore: some new linting

---

atuin-client/src/settings.rs
src/command/mod.rs

`eyre` contexts allow better error analysis in panics

chore: add more eyre contexts

---

CHANGELOG.md
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-common/Cargo.toml
atuin-server/Cargo.toml

Resolve #221 and #212
Also very long overdue, sorry for the delay. Been busy with life this year :)
I should be giving Atuin some more attention soon

Release v0.7.2

---

CHANGELOG.md
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-common/Cargo.toml
atuin-server/Cargo.toml

Add Fish support! Finally 🚀 
Also some other contributions, detailed in the release notes :))
Thank you to everyone who got involved for this release!

Release v0.8.0

---

atuin-client/src/database.rs

you probably don't want to keep the actual test in, but it was quite significantly faster on my machine.

use sqlite grouping rather than subquery

---

src/shell/atuin.bash

See https://github.com/akinomyoga/ble.sh/wiki/Manual-%C2%A71-Introduction#user-content-fn-blehook for more details

Add support for blesh 

---

atuin-server/src/settings.rs

remove default db uri

---

README.md

https://ports.macports.org/port/atuin/

README: add MacPorts installation instructions

---

atuin-client/src/api_client.rs
atuin-client/src/database.rs
atuin-client/src/encryption.rs
atuin-client/src/history.rs
atuin-client/src/import/fish.rs
src/command/stats.rs
src/main.rs

use the bail macro
replace client database errors
remove dead code

A few minor tweaks

---

atuin-server/migrations/20220421073605_fix_count_trigger_delete.sql

I've tested this again by deleting my full history and re-syncing, all
good.

Fix delete trigger

---

atuin-server/migrations/20220421174016_larger-commands.sql

Followup: Limit command length client side too

Allow for larger commands

---

docker-compose.yml
docs/server.md

Updated documentation on how to run own atuin with docker-compose

Added docker-compose.yml

---

docs/config.md
docs/search.md
docs/sync.md

This PR fixes some typos in the docs.

Fix typos in the docs.

---

atuin-client/src/database.rs

oops 😳
basically, empty queries just had an `and` or a `where` with no actual specifier after it, which sql hated

Fix empty queries with filters

---

atuin-server/migrations/20220426080938_history-index.sql

This speeds up a whole bunch of our queries by a *lot* :)

Add btree index on history table

---

src/command/client/import.rs

fix import auto for bash

---

atuin-server/migrations/20220426172813_user-created-at.sql

There are actually a large number of users of the public server now!

Add created_at column to users

---

Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-server/Cargo.toml

Please see individual commit messages.

Cleanup dependencies – disable unnecessary or unused features

---

src/command/client/event.rs
src/command/client/search.rs

Allows you to scroll quickly through the history search using mouse wheel/trackpad instead of just with keys

[feature] Add scroll wheel support to interactive history search

---

.github/workflows/docker.yaml

These are failing and need investigating

Disable ARM docker builds

---

atuin-server/src/handlers/mod.rs

This will be useful for update prompts :)

Show current version on server index

---

Dockerfile
atuin-client/src/history.rs
atuin-client/src/settings.rs

* Bump base images to fix several critical vuln
* Run the container as non root
I would also suggest to use a tool like [renovate](https://github.com/renovatebot/renovate) to auto bump the base images.

Securize Dockerfile

---

Cargo.lock
Cargo.toml
src/command/client/history.rs
src/command/client/search.rs
src/command/client/search/duration.rs
src/command/client/search/interactive.rs

Adjusts the current default layout a tad by making it slightly more compact and aligning the search box with the results for a smoother searching experience
Old:
New:

update default layout

---

Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-client/src/sync.rs
atuin-common/Cargo.toml
atuin-server/Cargo.toml

1) Release a bunch of adjustments, including perf improvements from @conradludgate 
2) Also switch to just using one big version number

Release v11

---

README.md
install.sh

Atuin has been added to the [Termux package repository](https://github.com/termux/termux-packages/pull/11961).

Add installer support for Termux

---

atuin-client/src/api_client.rs
atuin-client/src/database.rs
atuin-common/src/api.rs
atuin-server/src/handlers/history.rs
atuin-server/src/handlers/mod.rs
atuin-server/src/handlers/user.rs

To address bad error messages in #504

add some error messages

---

install.sh

Add message begging for help lol 🐢

---

atuin-client/src/settings.rs

I think this makes the most sense

Make fuzzy search the default

---

README.md

Add Antigen plugin manager instruction.

Update README.md with antigen instruction.

---

src/command/client/search/cursor.rs
src/command/client/search/interactive.rs

- Ignore tab key in interactive mode
- Support home and end keys in interactive mode
- Support delete key in interactive mode

Add support for some additional keys in interactive mode

---

Cargo.lock
Cargo.toml
atuin-client/src/database.rs
src/command/client.rs
src/command/client/history.rs
src/command/client/import.rs
src/command/client/search.rs
src/command/client/search/duration.rs
src/command/client/search/event.rs
src/command/client/search/interactive.rs
src/command/client/sync.rs
src/command/client/sync/login.rs
src/command/contributors.rs
src/command/init.rs

Instead of https://github.com/ellie/atuin/pull/612

Switch to using ATUIN_LOG instead of RUST_LOG

---

src/command/client/search/interactive.rs

Fixes #621
Signed-off-by: Baptiste Roux <arte.but.posix@gmail.com>

chore(#621): Exit atuin when pressing down arrow on most recent entry

---

README.md

see https://github.com/badges/shields/issues/8671
also, nice talk at FOSDEM :)

Fix CI build badge

---

Cargo.lock
Cargo.toml
atuin-client/src/encryption.rs
src/command/client/sync.rs
src/command/client/sync/login.rs

display mnemonic key

---

Cargo.lock
Cargo.toml
src/command/client/search/interactive.rs

@conradludgate Pretty sure that's all we need 🤷‍♀️ 
didn't want to clobber your branch though

[rebase] make update_needed check lazy

---

install.sh

Dont't fail is a Linux system does not provide lsb_release, try to read the distro from /etc/os-release in this case.

Make the install script more robust

---

src/command/client/stats.rs

Should fix the error @pdecat found!

Check before unwrapping in stats

---

atuin-server/src/handlers/history.rs
atuin-server/src/handlers/user.rs
atuin-server/src/router.rs

This is a first step to use https://github.com/ellie/atuin/pull/491 to implement https://github.com/ellie/atuin/issues/356 on top of the Axum 0.6. I thought it might be easier to review with smaller PRs. 
I think that adding integration tests might be a good next step, to have less chance of defects?

Add support for generic database in AppState

---

src/command/client/search/history_list.rs
src/command/client/search/interactive.rs

Revert "Remove shortcut numbers"

---

atuin-client/src/settings.rs
src/command/client/search/interactive.rs

This addresses https://github.com/ellie/atuin/issues/405
TODO:

Show preview of selected command

---

atuin-client/src/settings.rs
src/command/client/search.rs
src/command/client/search/interactive.rs

Up arrow filter_mode setting default to global filter mode

---

Cargo.lock
atuin-server/Cargo.toml
atuin-server/src/handlers/user.rs
atuin-server/src/settings.rs

I find it super motivating when people use my stuff, so this makes it _even easier_ to know when someone new signs up!

Add register notification webhook

---

atuin-client/src/database.rs
src/command/client/search.rs
src/command/client/search/interactive.rs

Mixing filters done in Rust with filters done in SQL is _no bueno_.
Been meaning to do this for a while anyways. Search params are getting a bit fat but oh well!
Resolves #768

Fix before/after combined with limit

---

src/command/client/stats.rs

The stats unique count was only counting unique prefixes, not unique full commands. It seems this was not preferred, so now I'm counting unique commands separately from the prefixes

fix new stats unique count

---

src/command/client/search/interactive.rs

Fixes this [issue](https://github.com/ellie/atuin/issues/786)

fix: paste into terminal after switching modes

---

atuin-client/src/encryption.rs
atuin-client/src/history.rs

I forgot it isn't backwards compatible... This should fix any sync issues resulting from the deletion PR
Will switch to a new encoding in the future

Support old msgpack

---

README.md
atuin-client/src/import/mod.rs
atuin-client/src/import/nu.rs
atuin-client/src/import/nu_histdb.rs
src/command/client/import.rs
src/command/init.rs
src/shell/atuin.nu

See [NuShell support · Issue #687 · ellie/atuin](https://github.com/ellie/atuin/issues/687).

feat: add *Nushell* support

---

atuin-client/src/database.rs
src/command/client/search.rs
src/command/client/search/engines/db.rs
src/command/client/search/interactive.rs

As title says, instead of filtering a vec, now it's in the query

client filtering done in query

---

Cargo.lock
Cargo.toml
atuin-common/src/api.rs
atuin-server/src/handlers/status.rs
src/command/client/sync.rs
src/command/client/sync/status.rs

Useful for debugging, checking the state of things, and for if you forget your username!

Add `atuin status`

---

atuin-client/src/import/bash.rs

Handle empty lines when importing from Bash

---

src/command/client/stats.rs

Filter `atuin stats` with day, week, month and year filer by using `atuin stats today`, `atuin stats week`, `atuin stats month`, `atuin stats year`.

Atuin stats with day, month, week and year filter

---

.github/workflows/release.yaml

man I dislike actions strongly
just need to trigger this for the older commit

Add workflow dispatch for release

---

docs/docs/config/key-binding.md

I believe these shortcuts should be in the same section as shell shortcuts, so I added them there.

Add keyboard shortcuts to the Config/Keybinding chapter.

---

atuin/LICENSE

It can't cope with relative paths :/

Copy license for cargo-deb

---

Cargo.lock
atuin/Cargo.toml
atuin/src/command/client/history.rs

fix broken pipe on history list

---

README.md

Fix broken i18n links in README.md.

docs: Fix broken links in README.md

---

README.md

Update README.md: Disable update check for offline mode

---

README.md
docs/docs/index.md

Include bash preexec warning

---

README.md
atuin-server/src/handlers/user.rs
docs/docs/commands/sync.md

* validate usernames on registration
* improve login password incorrect error message
* update docs for registration with passwords (fixes #949)

validate usernames on registration

---

Cargo.lock
atuin-client/src/sync.rs
atuin-common/src/api.rs
atuin-server/Cargo.toml
atuin-server/src/database.rs
atuin-server/src/handlers/history.rs
atuin-server/src/handlers/status.rs
atuin-server/src/lib.rs
atuin-server/src/settings.rs
atuin-server/src/utils.rs

Allow server configured page size

---

atuin/src/command/client/account/register.rs

feat: do not allow empty passwords durring account creation

---

atuin-client/src/kv.rs
atuin/src/command/client/kv.rs

Add namespaces, they will be useful in my next PR 👀

Add namespaces to kv store

---

docs/docs/advanced-install.md
docs/docs/guide/index.md
docs/docusaurus.config.js
docs/src/pages/index.js
install.sh

We were lacking some docs here really. Walk new users through getting installed and signed up!
Coming next
- Common config (how to disable the up arrow lol)
- Troubleshooting
- Community config/integrations

Revamp getting started guide

---

atuin-common/src/api.rs
atuin-server-database/src/lib.rs
atuin-server-postgres/src/lib.rs
atuin-server/src/handlers/mod.rs

Thought it would be fun to collect some cool stats, maybe put them on atuin.sh.

Add total history count to the index API

---

docs/docusaurus.config.js

I broke things a little, hopefully fixed soon...

Try adjusting docs root

---

.github/workflows/nix.yml
.github/workflows/rust.yml
Cargo.lock
atuin-server/src/lib.rs
atuin/Cargo.toml
atuin/tests/sync.rs

To run tests locally, now we need a postgres server running. That can be setup using docker
```
docker run -e POSTGRES_USER=atuin -e POSTGRES_PASSWORD=pass -e POSTGRES_DB=atuin -p 5432:5432 -d --rm postgres
```

some simple server tests

---

atuin-client/src/settings.rs

We currently sync once per hour, which is actually far too conservative. Increase sync rate!

Drop default sync frequency to 10m

---

Cargo.toml
README.md
atuin.nix
docker-compose.yml
docs/docs/advanced-install.md
docs/docs/self-hosting/k8s.md
docs/docusaurus.config.js
docs/zh-CN/k8s.md
install.sh
k8s/atuin.yaml

The repo now lives on an org! Move all references to the old path.

Move all references to the old repo

---

docs/docs/commands/commands.md

This is a fix for my previous rushed mess-up. 😇
Context: https://github.com/atuinsh/atuin/pull/1140#issuecomment-1661288695

fix(docs): Correct command overview paths

---

atuin/build.rs
atuin/src/command/client/sync/status.rs
atuin/src/main.rs

Useful for support - sometimes people have ran `main` without realisiing

Include revision in status

---

.github/workflows/rust.yml

Checks if client-only builds on PRs

Run check for client-only feature set

---

atuin/build.rs

I forgot nix builds in a sandbox, so my laziness earlier meant that the nix build fails - sandbox has no git!

Fix nix build

---

install.sh

Only setup shell plugin if it's not already there

---

README.md

Happy to support a startup, but Amazon can sponsor us if they want a link in the README ;P

Remove fig from README

---

atuin/src/command/client/search/interactive.rs

Adds mouse selection support.
closes #160

feat: mouse selection support

---

atuin-client/src/api_client.rs
atuin-server/src/handlers/history.rs
atuin-server/src/router.rs

better sync error messages

---

install.sh

[`paru`](https://github.com/morganamilo/paru) is more popular these days :bear:

feat(installer): try installing via paru for the AUR

---

.github/DISCUSSION_TEMPLATE/support.yml

fyi @conradludgate - if I've forgotten any other questions we normally ask people, please lmk

Add support template

---

atuin-client/src/api_client.rs
atuin-server-postgres/src/lib.rs
atuin-server-postgres/src/wrappers.rs
atuin.nix
atuin/tests/sync.rs

fix sync timestamps

---

atuin/src/shell/atuin.nu

handle empty keybindings list for nushell

---

atuin/src/command/client/search/engines/skim.rs

This should Fix #1220, as the FilterMode::Workspace was not handled in skim engine

fix(1220): Workspace Filtermode not handled in skim engine

---

.github/workflows/rust.yml

Reverts atuinsh/atuin#1294
aaaand it's gone again 🙃 
who knew, 🌩️  and 💻 don't mix. I'll fix for real when I'm home.

Revert "Revert "Use github runners for unit tests (for now)""

---

atuin-common/src/utils.rs
atuin/src/command/client/search/interactive.rs
atuin/src/shell/atuin.fish
atuin/src/shell/atuin.zsh
docs/docs/config/config.md

Also fixes shell detection. Who trusted me to write jetlagged code last night huh?

Add fish support for `enter_accept`

---

atuin-client/src/secrets.rs

Remove the anchoring! Otherwise they will never work

Correct some secrets filter regex

---

Cargo.lock
atuin/Cargo.toml
atuin/src/command/client/search/interactive.rs

See here: https://github.com/ratatui-org/ratatui/pull/530
Replaces #1330

Fix for breaking change in ratatui 0.24.0

---

atuin-server/src/router.rs

Rest in peace 😔
https://nivenly.org/memorials/krisnova/

Add Kris Nova to X-Clacks-Overhead

---

atuin-server/src/handlers/history.rs
atuin-server/src/handlers/record.rs

more than just the http stuff we have atm

feat: add some metrics related to Atuin as an app

---

atuin/src/command/client/stats.rs

This change allows users to use spaces in their custom prefixes/subcommands.
A user could, for example, use both `cargo` and `cargo build` as subcommands and it would work as expected, with `cargo build foo` showing up as its own command.
I hit this because I use [script-directory](https://github.com/ianthehenry/sd) to organize my personal scripts, so I end up with heirarchically named shell scripts, and it makes sense to be able to separate them out.

feat: allow spaces in stats prefixes

---

.github/dependabot.yml

It gets a little annoying running daily

chore: run dependabot weekly, not daily

---

.github/dependabot.yml

chore: don't group deps

---

install.sh

fix: respect ZSH's $ZDOTDIR environment variable

---

README.md
docs/docs/advanced-install.md

docs: add Void Linux install instruction

---

atuin/src/shell/atuin.bash

These are the refactoring commits mentioned in #1467. Again, see the commit messages.

refactor(bash): refactor and optimize `__atuin_accept_line`

---

atuin/src/shell/atuin.bash
docs/docs/integrations.md

I saw #1479 for the zsh-autosuggestions integration. A similar setup is possible with ble.sh.

feat(bash): provide auto-complete source for ble.sh

---

CHANGELOG.md
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-server-database/Cargo.toml
atuin-server-postgres/Cargo.toml
atuin-server/Cargo.toml
atuin/Cargo.toml

Fix a typo with the default config, preventing servers from starting without TLS settings

chore(release): prepare for release v17.2.1

---

atuin-server/src/router.rs

It was fun, but it wasn't as informative as it needs to be
I'm leaving the function name though :)

chore: remove the teapot response

---

atuin/src/command/client/search/interactive.rs

This enabled the Kitty Keyboard Protocol
Read more here: https://sw.kovidgoyal.net/kitty/keyboard-protocol/
No change on unsupported terminals, but means in the future we can be more creative with keybinding depending on terminal.
Tested on Alacritty and events come through with all modifiers supported.
Will be useful for #193

feat: enable enhanced keyboard mode

---

atuin-client/src/secrets.rs
docs/docs/config/config.md

to keep atuin login details out

include atuin login in secret patterns

---

atuin/src/command/client/search/interactive.rs

replace old Ctrl-L shortcut and remove the opposite one (Ctrl-H).
fixes #1507.

feat(ui): add redraw

---

atuin/src/command/client/account/register.rs

feat: make it clear what you are registering for

---

atuin-client/src/api_client.rs

Hopefully this helps users get more descriptive errors, and give more descriptive bug reports

feat: add better error handling for sync

---

CONTRIBUTING.md

Thanks to Ellie and Pete's help on this forum post: https://forum.atuin.sh/t/migration-was-previously-applied-but-is-missing-in-the-resolved-migrations/84

docs: Mention environment variables for custom paths

---

atuin/src/command/client/stats.rs

stats: Misc improvements

---

Cargo.lock
Cargo.toml
atuin-server-postgres/Cargo.toml
atuin-server/Cargo.toml

chore: use resolver 2, update editions + cargo

---

Cargo.lock
atuin-server/Cargo.toml
atuin-server/src/handlers/history.rs
atuin-server/src/handlers/mod.rs
atuin-server/src/handlers/record.rs
atuin-server/src/handlers/status.rs
atuin-server/src/handlers/user.rs
atuin-server/src/handlers/v0/record.rs
atuin-server/src/lib.rs
atuin-server/src/metrics.rs
atuin-server/src/router.rs
atuin-server/src/settings.rs
atuin/tests/sync.rs

closes #1567
closes #1565
closes #1564
closes #1422

chore: update axum

---

atuin-client/config.toml
atuin-client/src/settings.rs
atuin/src/command/client/history.rs
atuin/src/command/client/search.rs

feat: make history list format configurable

---

.github/workflows/rust.yml

Now that we're using a GitHub-hosted runner, re-enable the cache for tests
Also make checks their own step

chore(ci): re-enable test cache, add separate check step

---

atuin/src/command/client/history.rs
atuin/src/command/client/sync.rs

I think this makes more sense as a manual action

feat: disable auto record store init

---

atuin-client/src/record/sync.rs

fix: correct download list for incremental builds

---

.github/workflows/rust.yml
atuin-client/src/history/store.rs
atuin-common/src/utils.rs

I don't see too much point in also running the format/clippy on all platforms, and integration tests are maybe a little too much. Otherwise, this should ensure we don't break builds for mac/windows by accident
Note: This is still not "true" support for windows. I'd like to ensure builds/tests run OK, but I'd like to be able to properly test on that platform before we commit to supporting it.

chore(ci): run rust build/test/check on 3 platforms

---

CHANGELOG.md
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-server-database/Cargo.toml
atuin-server-postgres/Cargo.toml
atuin-server/Cargo.toml
atuin/Cargo.toml

chore(release): prepare for release v18.0.1

---

atuin-client/config.toml

Resolves #1687.  Some minor formatting updates to the default config.

minor formatting updates to the default config.toml

---

atuin/src/command/client/init/fish.rs

fix: fish init

---

atuin/src/command/client/config/alias.rs

Allow listing aliases, and provide feedback when setting them.
Error if trying to delete an unset alias

feat: add alias feedback and list command

---

atuin/src/command/client/sync.rs
atuin/src/command/client/sync/status.rs

fix: check session file exists for status command

---

atuin/src/command/client/history.rs

fix: ensure sync time is saved for sync v2

---

Cargo.lock

chore(deps): `cargo update`

---

atuin/src/command/client/doctor.rs

feat: add checks for common setup issues

---

docker-compose.yml

docs: update docker compose

---

atuin/src/command/client/doctor.rs

fix(doctor): use a different method to detect env vars

---

atuin/src/command/client/sync.rs

This means that the freshly imported records are immediately synced, and the user doesn't need to run `atuin sync` once more

fix(store-init): re-sync after running auto store init

---

atuin/src/command/client/sync/status.rs

chore: do not show history table stats when using records

---

.github/workflows/rust.yml

chore(ci): setup nextest

---

atuin/src/command/client/doctor.rs

fix: doctor shell wording

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
atuin-client/Cargo.toml
atuin-server-database/Cargo.toml
atuin-server-postgres/Cargo.toml
atuin-server/Cargo.toml
atuin/Cargo.toml

chore(release): prepare for release v18.1.0

---

atuin-dotfiles/Cargo.toml

fix(crate): add missing description

---

atuin/src/command/client/search.rs

feat(search): allow specifying search query as an env var

---

atuin/src/command/client/search.rs

fix(search): allow empty search

---

README.md

docs: add security contact

---

.github/ISSUE_TEMPLATE/bug.yaml

Hopefully this helps ensure we get all required data, and don't need as much back-and-forth

chore: add issue form

---

.github/ISSUE_TEMPLATE/bug.yaml

chore: require atuin doctor in issue form

---

.github/ISSUE_TEMPLATE/bug.yaml

chore: add section to issue form

---

atuin/src/shell/atuin.nu

Cf [fix: pass search query in via env by ellie · Pull Request #1865 · atuinsh/atuin](https://github.com/atuinsh/atuin/pull/1865).

fix: pass search query in via env for *Nushell*

---

atuin-client/src/database.rs

fix(search): case insensitive hostname filtering

---

Cargo.toml
ui/backend/Cargo.lock
ui/backend/Cargo.toml

Need to update the other lockfile now that it's split

chore(gui): cargo update

---

atuin-common/src/api.rs
atuin-server/src/handlers/v0/me.rs
atuin-server/src/handlers/v0/mod.rs
atuin-server/src/router.rs
atuin/src/command/client/sync/status.rs

For now just support getting the username. In future, we can read and edit all profile information this way

feat(server): add me endpoint

---

atuin-client/src/settings.rs
atuin/src/command/client/history.rs

feat: allow ignoring failed commands

---

crates/atuin/README.md

chore: fix atuin crate readme

---

crates/atuin-common/src/shell.rs

So far tested on a couple of Linux machines

fix: support not-mac for default shell

---

crates/atuin-dotfiles/src/shell.rs

fix(dotfiles): fish alias import

---

README.md
docs/zh-CN/README.md

`atuin` was moved into the `crates/` directory in 95cc4720

docs: fix "From source" `cd` command

---

crates/atuin-dotfiles/src/shell.rs

Serves me right for assuming fish mostly is POSIX.

fix(dotfiles): more fish alias import

---

Cargo.lock
crates/atuin/Cargo.toml
crates/atuin/src/command/client/search/interactive.rs

Fix ratatui update

---

.github/workflows/release.yaml

fix(ci): release workflow

---

ui/backend/Cargo.lock
ui/backend/Cargo.toml
ui/backend/src/dotfiles/mod.rs
ui/backend/src/dotfiles/vars.rs
ui/backend/src/main.rs
ui/src/components/dotfiles/Vars.tsx
ui/src/pages/Dotfiles.tsx
ui/src/state/models.ts
ui/src/state/store.ts

feat(ui/dotfiles): add vars

---

crates/atuin/src/command/client/search/interactive.rs

Closes https://github.com/atuinsh/atuin/issues/1969

fix: adapt help to `enter_accept` config

---

Dockerfile

fix: add protobuf compiler to docker image

---

install.sh

Add Tuxedo OS to the list of Debian-compatible OSes.

Update install.sh adding Tuxedo OS

---

crates/atuin-client/config.toml

chore: clarify default config file

---

crates/atuin-daemon/src/server/sync.rs

fix: save sync time in daemon

---

ui/backend/Cargo.lock
ui/backend/src/main.rs
ui/src/pages/Home.tsx
ui/src/state/models.ts
ui/src/state/store.ts

Ensure the GUI works fine if the user is not logged in for sync

fix(ui): handle being logged out gracefully

---

Cargo.lock
crates/atuin-client/Cargo.toml

chore: bump rusty_paseto and rusty_paserk

---

Cargo.lock
crates/atuin-client/Cargo.toml
crates/atuin-client/src/lib.rs
crates/atuin-client/src/login.rs
crates/atuin-client/src/register.rs
crates/atuin/src/command/client/account/login.rs
ui/backend/Cargo.lock
ui/backend/src/main.rs
ui/package.json
ui/pnpm-lock.yaml
ui/src/App.tsx
ui/src/components/Button.tsx
ui/src/components/LoginOrRegister.tsx
ui/src/components/history/Stats.tsx
ui/src/components/ui/dialog.tsx
ui/src/state/client.ts
ui/src/state/models.ts
ui/src/state/store.ts

feat(ui): add login/register dialog

---

crates/atuin-history/src/stats.rs

Fix stats generation for commands starting with a pipe

---

Cargo.lock
Cargo.toml
crates/atuin-server/Cargo.toml
ui/backend/Cargo.toml

Cherry-picking from the last PR so that things are easier when the next release is cut

Relax sqlx dependency

---

crates/atuin/src/main.rs
ui/.gitignore
ui/backend/rust-toolchain.toml
ui/src/pages/Dotfiles.tsx
ui/src/pages/History.tsx

1. Use my atuin email
2. small ui tweaks

chore: update email, gitignore, tweak ui

---

crates/atuin/src/command/client/store.rs

docs: add docs for store subcommand

---

CHANGELOG.md
cliff.toml

chore: show scope in changelog

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
cliff.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release v18.3.0

---

crates/atuin-daemon/Cargo.toml

`cargo publish --dry-run` should really catch this.

fix(crate): add description to daemon crate

---

install.sh

Start by removing distro-specific installs, and replacing them with a binary install. Also, where possible, replace installing from source with a binary install.

feat: use cargo-dist installer from our install script

---

.github/workflows/installer.yml

chore: add installer e2e tests

---

crates/atuin/Cargo.toml

Resolve #2111
Tested with
`cargo binstall atuin --manifest-path=./crates/atuin/Cargo.toml`

fix: cargo binstall config

---

ui/backend/Cargo.lock
ui/backend/Cargo.toml

I'll sort CI for this soon, though the build process will be quite different

fix(gui): update deps

---

.github/dependabot.yml
ui/backend/Cargo.lock

chore: setup dependabot for the ui

---

Cargo.lock
ui/pnpm-lock.yaml

chore: cargo and pnpm update

---

flake.nix
rust-toolchain.toml

Twice in a day so I can get familiar with the nix thing 😂

chore: update to rust 1.79

---

.github/workflows/release.yml
Cargo.toml

chore: update to cargo-dist 0.16, enable attestations

---

crates/atuin-common/src/shell.rs
ui/backend/src/install.rs
ui/src/pages/Home.tsx

On windows, this makes the default shell `powershell` and adds support for checking if atuin is installed on windows in the gui

fix(gui): add support for checking if the cli is installed on windows

---

ui/src/pages/Home.tsx

feat(gui): toast with prompt for cli install, rather than auto

---

.github/workflows/nix.yml
.github/workflows/rust.yml

It's a waste of compute. Introduce separate CI for the UI later

chore(ci): do not run current ci for ui

---

Cargo.lock
crates/atuin/Cargo.toml

chore(deps): update ratatui to 0.27

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
cliff.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml
ui/backend/Cargo.toml

chore(release): prepare for release v18.4.0-beta.1

---

README.md

It's now compliant with sh, and doesn't require input

docs: update quickstart install command

---

crates/atuin-server-postgres/migrations/20240702094825_idx_cache_index.sql

Should have been in the last PR 🙃

fix: add idx cache unique index

---

crates/atuin-server-postgres/src/lib.rs

fix: ambiguous column name

---

Cargo.lock
crates/atuin-daemon/Cargo.toml
crates/atuin-daemon/src/client.rs
crates/atuin-daemon/src/server.rs

chore(deps): update to tonic 0.12, prost 0.13

---

Cargo.lock
crates/atuin-daemon/Cargo.toml

chore(deps): update prost-types

---

ui/src/lib/utils.ts
ui/src/state/store.ts

cc @YummyOreo, thanks for letting me know I broke windows again 😂

fix(gui): weekInfo call on Edge

---

ui/src/components/runbooks/editor/blocks/RunBlock/index.tsx

fix: add \r for windows (shouldn't effect unix)

---

crates/atuin-client/src/settings.rs

I'm now pretty confident in the automatic migration. Let's cut people over so they have a better experience

chore: enable record sync by default

---

ui/backend/Cargo.lock
ui/backend/Cargo.toml
ui/backend/src/main.rs
ui/backend/src/run/migrations.rs
ui/backend/src/run/mod.rs
ui/backend/tauri.conf.json
ui/package.json
ui/pnpm-lock.yaml
ui/src/App.tsx
ui/src/components/runbooks/List.tsx
ui/src/components/runbooks/editor/Editor.tsx
ui/src/components/runbooks/editor/blocks/RunBlock/index.tsx
ui/src/main.tsx
ui/src/pages/Runbooks.tsx
ui/src/state/runbooks/runbook.ts
ui/src/state/store.ts

Runbooks are not yet synced, and are currently stored in a SQLite db. In future we can properly sync a yjs doc
I've also made some adjustments to the UI, such as hiding the menu bar

feat(gui): add runbook list, ability to create and delete, sql storage

---

ui/README.md

docs(gui): update README

---

ui/src/App.tsx
ui/src/components/runbooks/editor/Editor.tsx
ui/src/components/runbooks/editor/blocks/RunBlock/index.tsx
ui/src/components/runbooks/editor/blocks/RunBlock/terminal.tsx
ui/src/main.tsx
ui/src/pages/Home.tsx
ui/src/pages/Runbooks.tsx

fix(gui): terminal resize overflow 

---

ui/backend/src/run/pty.rs
ui/src/App.tsx
ui/src/components/runbooks/List.tsx
ui/src/components/runbooks/editor/Editor.tsx
ui/src/components/runbooks/editor/blocks/RunBlock/index.tsx
ui/src/components/runbooks/editor/blocks/RunBlock/terminal.tsx
ui/src/main.tsx
ui/src/state/store.ts

Firstly, we now allow for background terminals to continue running even when the user navigates elsewhere. Like a proper multiplexer :)
Also added a status indicator on the runbook list to show how many are running on that runbook.
Otherwise, a bunch of UI tweaks and improvements. Most made due to me actually using it

feat(gui): a bunch of tweaks and changes

---

ui/backend/Cargo.lock
ui/backend/src/main.rs
ui/backend/src/run/pty.rs
ui/src/state/models.ts

1. add command for fetching cli settings
2. use the db_path
3. cargo fmt

fix(gui): do not hardcode db path

---

ui/src/components/runbooks/List.tsx

Also clear selection when the active doc is deleted

fix(gui): cursor positioning on new doc creation

---

ui/src/components/runbooks/editor/blocks/RunBlock/terminal.tsx

feat(gui): allow interacting with the embedded terminal

---

ui/backend/Cargo.lock
ui/backend/Cargo.toml
ui/backend/capabilities/migrated.json
ui/backend/src/main.rs
ui/backend/src/run/pty.rs
ui/package.json
ui/pnpm-lock.yaml
ui/src/components/runbooks/editor/blocks/Directory/index.tsx

feat(gui): folder select dialogue for directory block

---

ui/src/components/runbooks/editor/blocks/Directory/index.tsx
ui/src/components/runbooks/editor/blocks/Run/index.tsx
ui/src/pages/History.tsx
ui/src/pages/Runbooks.tsx

fix(gui): random ts errors

---

crates/atuin-daemon/src/client.rs

fix: windows build error

---

.codespellrc

fix: codespell config still references the ui

---

.github/workflows/codespell.yml

I think I've spent more time tweaking codespell than it's saved spelling 🤔

chore(ci): codespell again

---

Cargo.lock
Cargo.toml
crates/atuin-common/src/lib.rs

This included some breaking changes, see: https://github.com/launchbadge/sqlx/pull/2973
Luckily not too much effort to fix :)

chore(deps): update to sqlx 0.8

---

Dockerfile

chore(deps): update to debian bookworm, rust 1.80

---

Cargo.lock
crates/atuin-server/Cargo.toml
crates/atuin-server/src/lib.rs
crates/atuin-server/src/settings.rs

Updated rustls and axum-server to the current versions. Sync was tested with my self-hosted server.

Update rustls and axum-server

---

Cargo.toml
flake.lock
flake.nix
rust-toolchain.toml

chore: update to rust 1.82

---

crates/atuin/src/command/client/account/login.rs
crates/atuin/src/command/client/account/register.rs

feat: provide additional clarity around key management

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

It's been a while... Sorry! I've had an awful lot to sort out these past few months.

chore(release): prepare for release 18.4.0-beta.4

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.4.0-beta.5

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release v18.4.0

---

Cargo.lock
crates/atuin-daemon/build.rs
crates/atuin-server-database/src/lib.rs

chore(deps): cargo update

---

flake.lock

Reverts atuinsh/atuin#2463
I'll be honest I don't really want to debug Nix, so if anyone would like to solve this one I'd appreciate it

Revert "chore(deps): update flake.lock"

---

Cargo.lock
crates/atuin-client/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin/Cargo.toml
crates/atuin/src/command/client/search/history_list.rs
crates/atuin/src/command/client/search/inspector.rs
crates/atuin/src/command/client/search/interactive.rs

- [v] I am happy for maintainers to push small adjustments to this PR, to speed up the review cycle
- [v] I have checked that there are no existing pull requests for the same thing

chore(deps): bump ratatui to 0.29.0

---

crates/atuin/src/command/client/init/fish.rs

fix: up binding key for fish 4.0 (#2613)

---

install.sh

NOTE: draft while I test on Linux (with GNU sed) and on a fresh macOS VM
Comments and feedback welcome in the mean time

fixes #2603: support fish plugin in install script

---

crates/atuin/src/command/client/search/interactive.rs

fixes #2610: multiline command does not honour max_preview_height

---

.github/workflows/release.yml
dist-workspace.toml

chore(deps): update cargo-dist to 0.28

---

Cargo.toml
rust-toolchain.toml

chore: update to rust 1.85.1

---

crates/atuin/src/command/client/search.rs

fix: allow -ve values for timezone

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.5.0-beta.3

---

.github/workflows/release.yml
CHANGELOG.md
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.5.0

---

crates/atuin/tests/common/mod.rs

Found via `typos --hidden --format brief`

chore: fix typos

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-scripts/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

Pushing now as a fix for #2704 - will do a real release very soon

chore(release): prepare for release 18.6.0-beta.1

---

Cargo.lock
crates/atuin-server/Cargo.toml
crates/atuin-server/src/handlers/user.rs

The original code was using the server token there, and iiuc this has a lower privilege than account.

Update postmark to 0.11

---

Cargo.lock
crates/atuin-client/Cargo.toml

had a correctness bug reported to 0.1.1, should probably update.

update minspan to 0.1.5

---

CHANGELOG.md
CONTRIBUTORS
Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-kv/Cargo.toml
crates/atuin-scripts/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.6.0

---

crates/atuin/src/command/client/search/interactive.rs

Revert "fix: selection vs render issue"

---

crates/atuin-client/src/api_client.rs

Partially fixes #2455
Closes #979

fix(api): Allow trailing slashes in sync_address

---

crates/atuin-server-database/src/lib.rs

Add check for postgresql prefix

---

Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-kv/Cargo.toml
crates/atuin-scripts/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server-sqlite/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.7.1

---

crates/atuin-client/config.toml
crates/atuin-client/src/settings.rs
crates/atuin/src/command/client/search/interactive.rs
crates/atuin/src/shell/atuin.bash
crates/atuin/src/shell/atuin.fish
crates/atuin/src/shell/atuin.zsh

Allow for smart completion of commands ending in && or ||

feat: command chaining

---

crates/atuin-server-postgres/src/lib.rs

I never switched on the idx cache because a bunch of reads showed up as inconsistent and i was scared of races. The write logic did seem ok, though
I think this might have been why

fix: use transaction for idx consistency checking

---

crates/atuin-server-sqlite/Cargo.toml

Matches the config from the `atuin-client` crate this way

fix(build): enable sqlite feature for sqlite server

---

Cargo.lock
Cargo.toml
crates/atuin-client/Cargo.toml
crates/atuin-daemon/Cargo.toml
crates/atuin-dotfiles/Cargo.toml
crates/atuin-history/Cargo.toml
crates/atuin-kv/Cargo.toml
crates/atuin-scripts/Cargo.toml
crates/atuin-server-database/Cargo.toml
crates/atuin-server-postgres/Cargo.toml
crates/atuin-server-sqlite/Cargo.toml
crates/atuin-server/Cargo.toml
crates/atuin/Cargo.toml

chore(release): prepare for release 18.8.0

---

crates/atuin/src/command/client/search/interactive.rs

feat(tui): select entries using number in vim-normal mode. closes #2368

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
Dockerfile
crates/atuin-common/src/lib.rs
crates/atuin/src/command/client/doctor.rs
crates/atuin/src/command/client/search/inspector.rs
flake.lock
flake.nix
rust-toolchain.toml

Hopefully this one is mergeable as is, unlike the 1.89 upgrade.
Fixes: #2915

chore: update to Rust 1.90
